### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by felixjet** [devbridge/jQuery-Autocomplete#128]
Im getting **Uncaught TypeError: Cannot read property 'length' of undefined** error. the line is:

631 `if (suggestions.length && typeof suggestions[0] === 'string') {`

Its something caused by my options ?

EDIT: forgot **suggestions[]** in the json code.

**Comment by KicksaintNick** [comment]
Can you explain what you mean by forgot suggestions in the JSON code. I'm having the same issue

**Comment by tkirda** [comment]
He meant that your response should look like:

    { suggestions: [] }

**Comment by KicksaintNick** [comment]
Thanks, managed to get it working. Thanks for the great work on this repo :+1:
