### ISSUE TITLE
Parameters are not dynamically bind

### ISSUE THREAD

**Issue by jackswei** [devbridge/jQuery-Autocomplete#139]
$('#srtb_proname').autocomplete({
               serviceUrl: '/Program/Stock/DataService.asmx/GetPorName',
              //  lookup: countries,
               params: { 'type': $("#sear_ddl_type option:selected").val() },
               onHint: function (hint) {
                   $('#autocomplete-ajax-x').val(hint);
               }
            });
params:Parameters are not dynamically bind ;bind only one, i select sear_ddl_type the vaue no change

**Comment by bharathirasa** [comment]
Change the params like below.

$('#srtb_proname').autocomplete({
    serviceUrl: '/Program/Stock/DataService.asmx/GetPorName',
    params: { 'type': $("#sear_ddl_type option:selected").val() },
    onSearchStart: function (){
        $(this).autocomplete().setOptions({
 
            params:{ type: $("#sear_ddl_type option:selected").val() }
        });
    },
    onHint: function (hint) {
        $('#autocomplete-ajax-x').val(hint);
    }
});

**Comment by Tusko** [comment]
@tkirda 
How may I send params like JSON, not string?

**Comment by netmou** [comment]
```js
 onSearchStart: function (){
        $(this).autocomplete().setOptions('params', { 
            type: $("#sear_ddl_type option:selected").val() 
        });
    },
``
It looks weird, but it works;
why not modify parameters directly in the callback at onSearchStart(Chang the function signature  likes 
 onSearchStart(element,option)),
so code like follow:
```js
 onSearchStart: function (ele,option){
            option.params['type']=$("#sear_ddl_type option:selected").val() 
},
```
