### ISSUE TITLE
Letters with accents not matched

### ISSUE THREAD

**Issue by pixmin** [devbridge/jQuery-Autocomplete#155]
Would it be possible to match the letters that have accents when typing in the same letter without the accent?

Ex: If I type "Me" I would like "Mé" to be matched...

**Comment by NekoKetsu** [comment]
Thanks !

i use this  : 

```javascript
var _formatRegexp = function(q) {
    q = q.replace(/[eéèêëEÉÈÊË]/i,'[eéèêëEÉÈÊË]');
    q = q.replace(/[aàâäAÀÁÂÃÄÅÆ]/i,'[aàâäAÀÁÂÃÄÅÆ]');
    q = q.replace(/[cçC]/i,'[cçC]');
    q = q.replace(/[iïîIÌÍÎÏ]/i,'[iïîIÌÍÎÏ]');
    q = q.replace(/[oôöÒÓÔÕÖ]/i,'[oôöÒÓÔÕÖ]');
    q = q.replace(/[uüûUÜÛÙÚ]/i,'[uüûUÜÛÙÚ]');
    q = q.replace(/[yYÿÝ]/i,'[yYÿÝ]');
    return q;
};
```

For total accents and case insensitive

**Comment by tkirda** [comment]
This matching first occurrence only. You probably want global match:

    q = q.replace(/[eéèêëEÉÈÊË]/gi,'[eéèêëEÉÈÊË]');

**Comment by NekoKetsu** [comment]
Yeah true !
i just realize by testing thanks

**Comment by rodrigopires** [comment]
You guys rock! Came here to solve one problem, and ended up solving an additional one I had no idea that existed!

Cheers! :beers:

**Comment by dariusll** [comment]
with franck34 solution autocomplete becomes vulnerable with xss for me
