### ISSUE TITLE
It autocomplete's only once how about to autocomplete multiple words in a text area

### ISSUE THREAD

**Issue by chakas** [devbridge/jQuery-Autocomplete#169]

**Comment by GrazingScientist** [comment]
For anyone also coming across this issue:
I tried to achive an Google-like effect. So, while typing, the autosuggester realizes that a term (which may contain multiple words) is done (without commas) and a new term is just coming up. I came up with this solution:

```
    onSearchComplete: (query, suggestions) ->
      QuerySplit = query.split(' ')
      if suggestions.length is 0 and QuerySplit.length isnt 0
        $(this).data.options.delimiter = QuerySplit.slice(0, -1).join(' ') + ' '
```
So, as soon as there are no suggestions found for a word (that is not the word currrently written), it is added to the delimiter. Works so far and may be a starting point for someone else.
