### ISSUE TITLE
Reset field to empty and minChars no longer works

### ISSUE THREAD

**Issue by ziplizard** [devbridge/jQuery-Autocomplete#173]
I've found that after I select an item from the autocomplete list and then click a "Add" button I have, which resets the autocomplete field to empty - the minChars is no longer recognized. 
Example: 
I have minChars set to 0
I use jQuery to reset the value like so: $('#autocomplete').val('');
Result: I click on the field and the autocomplete does not work until I start typing.
Expected result: Since minChars is set to 0 - the autocomplete should work as soon as I click (focus) on it.
It continues to work if I put focus on it, then focus off, and then focus once again. It's just the initial focus that does not recognize the minChars and does not do the autocomplete.
FYI - I'm doing this using Bootstrap 2.3.2.

**Comment by maege85** [comment]
$('#autocomplete').val('').autocomplete('onValueChange');

This is absolutely wonderful! I would mention this somewhere in the readme file.
Thank you very much!
