### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by pgeza** [devbridge/jQuery-Autocomplete#235]
Do you plan? With typescript definition maybe?

**Comment by mapsdev** [comment]
This looks like a great autocomplete - any chance the TypeScript definition has been written?

**Comment by tkirda** [comment]
Not yet. Pull request is welcome :)

**Comment by mapsdev** [comment]
Ok - I'm happy to have a go at this. I haven't written a TypeScript definition before, so I'll have a look. Can you suggest any existing guides or guidelines for writing this for this jQuery module?

**Comment by tkirda** [comment]
I say just take a look at other plugin definitions here: https://github.com/borisyankov/DefinitelyTyped

**Comment by tkirda** [comment]
No plans on publishing Nuget package.
