### ISSUE TITLE
Autocomplete order

### ISSUE THREAD

**Issue by changeinn** [devbridge/jQuery-Autocomplete#270]
<input id="programs" placeholder="Input program name"/>
    var programs = [
                    {value:'PBSValue', data:'PBS'},
                    {value:'HBOValue', data:'HBO'},
                    {value:'ABCValue', data:'ABC'},
                    {value:'HBOFamilyValue', data:'HBO Family'}
                    ];
    $('#programs').devbridgeAutocomplete({
        lookup: programs
    })

When I input "A", it lists all values in original order. Is it supposed to put "ABCValue" on the top? Thanks!

**Comment by Aloha276** [comment]
If someone need to sort by relevance, here is what i did:
transformResult: function(response, originalQuery){
                    response = $.parseJSON(response);
                    var resultSuggestions = [];
                    $.map(response, function (jsonItem){
                        if(typeof jsonItem != "string"){
                            $.map(jsonItem, function (suggestionItem){
                                resultSuggestions.push({ value: suggestionItem });
                            });
                        }
                    });
                    resultSuggestions.sort(function(a, b){
                        var aStart = String(a.value).match(new RegExp('^'+originalQuery, 'i')) || [],
                              bStart = String(b.value).match(new RegExp('^'+originalQuery, 'i')) || [];
                        if(aStart.length != bStart.length) return bStart.length - aStart.length;
                        else return a > b ? 1 : -1;
		   });
		   response.suggestions = resultSuggestions;
		   return response;
}

**Comment by deliaahm** [comment]
I have these jquery autocomplete, and i also want to order results :

**Comment by deliaahm** [comment]
I have these code and i also want to order results
![image](https://user-images.githubusercontent.com/38059468/40096422-fd838098-58fa-11e8-8bb3-ccf392211feb.png)
