### ISSUE TITLE
Unable to overwrite options in onSearchStart

### ISSUE THREAD

**Issue by ssteeg** [devbridge/jQuery-Autocomplete#280]
I'm using the `onSearchStart` option to change the autocomplete options, similar to https://github.com/devbridge/jQuery-Autocomplete/pull/47 and am trying to rewrite the query option. As an example:

``` JavaScript
onSearchStart: (query) -> $(this).autocomplete().setOptions({params: {query: "TEST"}})
```

However, the `query` field isn't being overwritten, because of, I believe, this line: https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L218:

``` JavaScript
$.extend(options, suppliedOptions);
```

It seems like I could change the line to the following to overwrite the options properly, but I must be misunderstanding something..

``` JavaScript
$.extend(true, options, suppliedOptions);
```

Is this a change that can be made or am I going about this incorrectly? Thanks!

**Comment by fuxifex** [comment]
i'm having the same issue .. is there a fix yet?

**Comment by tkirda** [comment]
`onSearchStart` receives `params` object. You need to mutate that object.
