### ISSUE TITLE
IE10 - focused input show suggestions after initialisation

### ISSUE THREAD

**Issue by ondrejspilka** [devbridge/jQuery-Autocomplete#285]
Hi,
this code invoke suggestions  when put in the init event of jQuery.
How to prevent autocomplete from showing suggestions for the first time?
I was able to cancel it only via timer, but suggestions have shown for a while...so this is only workaround

Thanks
		$('#query').focus();
		$('#query').devbridgeAutocomplete(
			{
			serviceUrl: '/suggest.php',
			minChars: 2
			});

**Comment by tkirda** [comment]
Closing this since it not clear what the issue is and steps to reproduce it.

**Comment by ondrejspilka** [comment]
Hi tkirda,

what is unclear? just create input box, set autocomplete on it.
focus shows suggestions...
the questuion is how to set focus without showing suggestions.

**Comment by tkirda** [comment]
That is intended behavior. If you focus and don't want to show suggestions, call `hide` on the autocomplete instance:

    $('#myinput').focus();
    $('#myinput').autocomplete('hide');

or disable before focus and then enable:

    $('#myinput').autocomplete('disable');
    $('#myinput').focus();
    $('#myinput').autocomplete('enable');
