### ISSUE TITLE
Randomly error : Provisional headers are shown

### ISSUE THREAD

**Issue by alecasciaro** [devbridge/jQuery-Autocomplete#286]
Hi, 
I receive this randomly error especially when i write fast  "Provisional headers are shown" and the request is cancelled. 
I tried almost of solution but nothing resolve my problem.

This image are chrome degger log and request detail.

![7unay](https://cloud.githubusercontent.com/assets/5084564/5358251/4686848c-7fb2-11e4-9e16-7ce6480e08cf.png)
![cu49x](https://cloud.githubusercontent.com/assets/5084564/5358252/468bb128-7fb2-11e4-8188-47d5ccf456fd.png)

**Comment by vigneshmuthukrishnan** [comment]
give me some other  options above url u had mentioned is not working
