### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by benziane** [devbridge/jQuery-Autocomplete#288]
Line: 768 : if (suggestions.length && typeof suggestions[0] === 'string') {
Tested with Chrome

**Comment by slifin** [comment]
I was getting this error then I changed my response to this:
    {"query":"t","suggestions":[]}
now there is no error but jQuery Autocomplete only triggers on first keypress but none after that which 
renders it pretty useless, am I doing something wrong?
