### ISSUE TITLE
onSelect event does not work properly sometimes

### ISSUE THREAD

**Issue by ARACOOOL** [devbridge/jQuery-Autocomplete#289]
if suggestion value is equal to user request this is being event call, but user didn't selected any of suggestions.

**Comment by atefBB** [comment]
Hi @tkirda . 
I set `triggerSelectOnValidInput` to `false` but still doesn't work (doesnot `log` anything)!
My code looks like:
![code_snippet](https://user-images.githubusercontent.com/10966925/41858106-ef16287a-7890-11e8-9250-4df7193e35eb.PNG)

**Comment by tkirda** [comment]
@atefBB In your case it should be set to `true`.

**Comment by atefBB** [comment]
Excuse me @tkirda but the `onSelect` function looks confusing to me, it will be triggered if the `suggestion.value` match the searched `query`! Am I wrong? It SHOULD (as I expected) be triggered if `suggestion.value` `includes` the `query` (not the exact match) ?! 
Any suggestion!?
Thanks.

**Comment by tkirda** [comment]
@atefBB Your understanding is incorrect in this case. `onSelect` is triggered when user selects value from suggested list, or when user types full value that is matching. If suggestion only includes value then you get list of suggestions.

**Comment by atefBB** [comment]
I think I understand it as you describe, but as I describe the `onSelect` function doesn't do anything -in my case- even I clicked an item in the suggestion list.
