### ISSUE TITLE
jQuery-Autocomplete crashes Safari on IOS 7/8 (iPhone)

### ISSUE THREAD

**Issue by yetanotherchris** [devbridge/jQuery-Autocomplete#290]
Hi, we're having an issue with the autocomplete plugin on IOS (just iPhone) devices, where the plugin is causing a crash on IOS 7 and 8 devices (possibly 6 too).

I've put logging throughout the plugin, via alerts or document.writes, but can't tie down where it's happening. The entire browser crashes, and you have to kill the process via the home button and swiping to get Safari back up again.

The parts of the code that I've managed to rule out:
- Caret selection
- Ajax (I tried using an array, and the issue persists)
- Any of the callback functions: select, searchComplete etc.
- Explicitly calling destroy, `unbind()` and re-binding inside`$("#textbox").focus` makes no difference.

We have `noCache` set to true, and `triggerSelectOnValidInput` set to false.

It appears to happen after tabbing out of the textbox, then tabbing back in, or clearing the textbox. It won't happen immediately - it usually takes about 5 or 6 autocomplete suggestions appearing before the browser bombs.

I have a suspicion that it's related to setInterval but we're not able to put a debugger on the phone, and the debugger crashes as well.

Are there any areas in the code likely to cause the issue, that we could investigate?

All other browsers are absolutely fine, including iPads.

**Comment by tkirda** [comment]
Unable to reproduce, if you can share isolated case feel free.
