### ISSUE TITLE
Combine multiple ajax requests

### ISSUE THREAD

**Issue by nmaves** [devbridge/jQuery-Autocomplete#292]
We need a way to combine the results of two ajax calls into the search results.  Is there a way to control the actual ajax call?

**Comment by tkirda** [comment]
Yes, you can issue your own ajax call, just provide a function that will lookup results:

    $('.your-input').autocomplete({
        lookup: function (query, done) {
            // ajax call one
            // ajax call two
            // combine results
            // var results = { suggestions: [ ... ] }
            done(results);
        }
    });

**Comment by nmaves** [comment]
Perfect!  The docs are not clear about this option.

lookup: Lookup array for the suggestions. It may be array of strings or suggestion object literals.
suggestion: An object literal with the following format: { value: 'string', data: any }.

**Comment by tkirda** [comment]
Yes, this has been added recently and I need to update documentation.

**Comment by nmaves** [comment]
So do you still need to provide a serviceUrl option?  I just tried your example and it is not using the lookup callback.

**Comment by tkirda** [comment]
If you provide `lookup` function you don't need to specify `serviceUrl`.
