### ISSUE TITLE
populateTextField replacement?

### ISSUE THREAD

**Issue by nmaves** [devbridge/jQuery-Autocomplete#293]
This used to be available but I just upgraded and it is gone.  I don't want my input field to reflect their selection as they mouse though them.

**Comment by nmaves** [comment]
Never mind I found the issue from when I first asked for this.  Looks like I had to write my own.

https://github.com/devbridge/jQuery-Autocomplete/issues/112

**Comment by nmaves** [comment]
It looks like this is now an undocumented feature.  Any chance you could add this to the docs?

preserveInput: true

**Comment by tkirda** [comment]
This is in the docs. Was added in the following commit: https://github.com/devbridge/jQuery-Autocomplete/commit/54f24951e34aa0424f5af6d11590e47ee1faeb4f

**Comment by nmaves** [comment]
I think I found a bug with this.  In the code below I don't think that you should be checking the preserveInput option.  The preserveInput option should only apply to navigating the suggestions.  Not when you actually select one.

```
        onSelect: function (index) {
            var that = this,
                onSelectCallback = that.options.onSelect,
                suggestion = that.suggestions[index];

            that.currentValue = that.getValue(suggestion.value);

            if (that.currentValue !== that.el.val() && !that.options.preserveInput) {
                that.el.val(that.currentValue);
            }

            that.signalHint(null);
            that.suggestions = [];
            that.selection = suggestion;

            if ($.isFunction(onSelectCallback)) {
                onSelectCallback.call(that.element, suggestion);
            }
        }
```
