### ISSUE TITLE
Trigger when suggestions box visible

### ISSUE THREAD

**Issue by mgntrn** [devbridge/jQuery-Autocomplete#296]
Is it possible to trigger code when the suggestions box becomes visible, and trigger different code when the suggestions box disappears? I'm trying to alter the CSS of the search input when the box is visible, and reset the search input CSS when the suggestions box disappears/is invisible.

**Comment by tkirda** [comment]
Out of the box, no. You will need to modify source and add callbacks or raise events in the `suggest` and `hide` methods.
