### ISSUE TITLE
Grouping undefined Issue

### ISSUE THREAD

**Issue by stephanfriedrich** [devbridge/jQuery-Autocomplete#298]
Hy, i use your Awesome Jquery.autocompletion with Grouping. 
In my case we have Data with and without Group association. 

Here is my json Example:
{
    "q": "query",
    "suggestions": [
        { "value": "United Arab Emirates", "data": { "category": "Group1" }},
        { "value": "United Kingdom", "data": { "category": "Group1" }},
[1]        { "value": "Norway"},
[2]        { "value": "Netherlands", "data": { }},
    ]
}

Solution [1] result in an TypeError: suggestion.data is undefined.
Solution [2] puts out a Sting "undefined".

How can i show Values without a Group and "undefined" GroupPhrase.

**Comment by tkirda** [comment]
This case is not supported, because it is not clear what should be expected behavior.

**Comment by stephanfriedrich** [comment]
@tkirda Why are you closing this issue?
I think this is still an Error. 
It would be nice if i could deactivate the "undefined" GroupPhrase for Values without a Group.
