### ISSUE TITLE
personalize json

### ISSUE THREAD

**Issue by stephanfriedrich** [devbridge/jQuery-Autocomplete#299]
Hy, i think it would be nice, to use my own json with your lib.

In Example with grouping:
{
    "q": "query",
    "suggestions": [
        { "value": "United Arab Emirates", "group": "Group1"},
        { "value": "United Kingdom", "group": Group2" },
    ]
}

{
    "q": "query",
    "suggestions": [
        { "group1": "United Arab Emirates","Netherlands", "France" },
        { "group2": "United Kingdom" },
    ]
}

**Comment by tkirda** [comment]
You can send your own JSON format but then will have to transform it using `transformResult`.
