### ISSUE TITLE
group-sorting for received json-data

### ISSUE THREAD

**Issue by stephanfriedrich** [devbridge/jQuery-Autocomplete#300]
Ahoi, is it possible to sort grouped Values with your Javascript, if not it would be nice if you build these functionality. It would be nice if i could switch-on group-sorting.

Now with this json, i get following output:

{
    "q": "query",
    "suggestions": [
        { "value": "United Arab Emirates", "data": { "category": "Group1" }},
        { "value": "Netherlands", "data": { "category": "Group1" }},
        { "value": "United Kingdom", "data": { "category": "Group2" }},
        { "value": "Antarctica", "data": { "category": "Group1" }},
    ]
}

Group1:
United Arab Emirates
Netherlands
Group2:
United Kingdom
Group1:
Antarctica

**Comment by tkirda** [comment]
You can sort then in `transformResult` callback. It by group and then by value. This is not part of the plugin because same sorting is not something that works for everyone. It will display results in the order that are returned.

**Comment by bnekras** [comment]
Example:
transformResult: function(res){
            return {
                suggestions: JSON.parse(res).suggestions.sort(function(a, b){
                    return a.data.occupation.localeCompare(b.data.occupation);
                })
            }
        }
