### ISSUE TITLE
autocompletion focus error

### ISSUE THREAD

**Issue by stephanfriedrich** [devbridge/jQuery-Autocomplete#301]
After i search something and the autocompletion appear.
I click into the Browser Window ( e.g Browser Menubar ) and autocompletion won't lose its focus.

It works with jQueryUI http://jqueryui.com/autocomplete/#categories.

**Comment by tkirda** [comment]
If your input field looses focus then suggestions are hidden. I just check and jQuery UI seems to work the same way.
