### ISSUE TITLE
showNoSuggestionNotice to true does not work 

### ISSUE THREAD

**Issue by phisu** [devbridge/jQuery-Autocomplete#302]
I have set showNoSuggestion to true, grabbed the latest copy  (1.2.16) of autocomplete.js but still not working.

    $('#name').autocomplete({
	serviceUrl: 'autocomplete.php',
	autoSelectFirst: false,
	triggerSelectOnValidInput:false,
	params: {typ:'n'},
	forceFixPosition: true,
	orientation: 'auto',
	appendTo: '#itmName',
	minChars:3,
	deferRequestBy:250,
	showNoSuggestionNotice: true,
	noSuggestionNotice: "No results matched",
})

**Comment by EricAlla** [comment]
try this:
add a div tag in your html page 
<div id="noMatchingResultJavaScript">No results matched</div>
then replace your parameter value with the parameter value below
noSuggestionNotice: $('#noMatchingResultJavaScript').html()

**Comment by yakou32** [comment]
This does not work.

Actually, with no results and showNoSuggestionNotice set to true, there is an error : 
`Uncaught TypeError: Cannot read property 'length' of undefined`
at this line :
`if (suggestions.length && typeof suggestions[0] === 'string') {`

**Comment by tkirda** [comment]
See second demo from the top: http://devbridge.github.io/jQuery-Autocomplete/
