### ISSUE TITLE
Multiple query inputs

### ISSUE THREAD

**Issue by SgtOddball** [devbridge/jQuery-Autocomplete#304]
When using Ajax, would it be possible to pass back more than one query value?

So for example a users ID or a previously selected category? (there are work around's but I was wondering if it was something possible or already done, though I couldn't see easy way round at the moment)

**Comment by tkirda** [comment]
You can pass any additional values, but you need to set them up.

Other option, setup `serviceUrl` as function which formats query for suggestions and you can manipulate parameters yourself.
