### ISSUE TITLE
Suggestion list flipping when triggerSelectOnValidInput is set to false

### ISSUE THREAD

**Issue by EricAlla** [devbridge/jQuery-Autocomplete#307]
Issue: Suggestion list shows up and disappears immediately when using triggerSelectOnValidInput:false.

Scenario 1 (undesirable behaviour): enter 'a' in the input box and select 'Afghan afghani' from the suggestion list with the mouse pointer. 
action: click into the input box and the suggestion list will appear and disappear immediately.

Scenario 2 (desirable behaviour):  enter 'a' in the input box and select 'Afghan afghani' from the suggestion list with the mouse pointer.
action 1: click anywhere on the page except in the input field. 
action 2: click in the input field and the suggestion list will show up and stay visible

The scenarios were performed with the javascript and HTML below (tested with IE v11, chrome v40 and ff v35)

$(function(){
  var currencies = [
    { value: 'Afghan afghani', data: 'AFN' },
    { value: 'Albanian lek', data: 'ALL' },
    { value: 'Algerian dinar', data: 'DZD' },
  ];
  
  // setup autocomplete function pulling from currencies[] array
  $('#autocomplete').autocomplete({
    lookup: currencies,
    onSelect: function (suggestion) {
      var thehtml = '<strong>Currency Name:</strong> ' + suggestion.value + ' <br> <strong>Symbol:</strong> ' + suggestion.data;
      $('#outputcontent').html(thehtml);
	  },
	 triggerSelectOnValidInput:false,
onSearchError: function() {
        // do nothing - suppress error
    },
  });
});

and HTML:
<!doctype html>
<html lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
  <title>Input Autocomplete Suggestions Demo</title>
  <link rel="shortcut icon" href="http://designshack.net/favicon.ico">
  <link rel="icon" href="http://designshack.net/favicon.ico">
  <link rel="stylesheet" type="text/css" media="all" href="style.css">
  
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script>
  <script type="text/javascript" src="js/jquery.autocomplete.js"></script>
  <script type="text/javascript" src="js/currency-autocomplete.js"></script>
  
 
	
</head>

<body>
  <div id="topbar"><a href="http://designshack.net">Back to Design Shack</a></div>
  <div id="w">
    <div id="content">
      <h1>World Currencies Autocomplete Search</h1>
      <p>Just start typing and results will be supplied from the JavaScript. Check out <a href="https://github.com/devbridge/jQuery-Autocomplete">jQuery Autocomplete</a> on Github.</a></p>
      
      <div id="searchfield">
        <form><input type="text" name="currency" class="biginput" id="autocomplete"></form>
      </div>
      
      <div id="outputbox">
        <p id="outputcontent">Choose a currency and the results will display here.</p>
      </div>
    </div>
  </div>
</body>
</html>

**Comment by tkirda** [comment]
Scenario 1 that you described should not be happening. Code should decide show or not suggestions and then update UI. Without live sample or way to reproduce the issue I can not help.

**Comment by EricAlla** [comment]
The javascript was attached to the message I posted, you just need to test it...
The way to reproduce the issue is described in scenario 1

The issue is still opened, you should not close it.
If you say it works, please provide the version of jquery and devbridge you're using and I'll test on my side.

--------------------------------------------
En date de : Mer 28.1.15, Tomas Kirda <notifications@github.com> a écrit :

 Objet: Re: [jQuery-Autocomplete] Suggestion list flipping when triggerSelectOnValidInput is set to false (#307)
 À: "devbridge/jQuery-Autocomplete" <jQuery-Autocomplete@noreply.github.com>
 Cc: "EricAlla" <eric_allal@yahoo.fr>
 Date: Mercredi 28 janvier 2015, 21h18
 
 Scenario 1 that you described
 should not be happening. Code should decide show or not
 suggestions and then update UI. Without live sample or way
 to reproduce the issue I can not help.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by EricAlla** [comment]
Attached is the code required to reproduce the issue. I've simplified the html and javascript code to keep the strict minimum only.
Please, try the 2 scenarii I've described in the ticket and you'll see this strange and unwanted behaviour.

Directory structure:
./index.html 
./style.css 
./js/currency-autocomplete.js
./js/jquery.autocomplete.js
./images/bg.gif


--------------------------------------------
En date de : Mer 28.1.15, Tomas Kirda <notifications@github.com> a écrit :

 Objet: Re: [jQuery-Autocomplete] Suggestion list flipping when triggerSelectOnValidInput is set to false (#307)
 À: "devbridge/jQuery-Autocomplete" <jQuery-Autocomplete@noreply.github.com>
 Cc: "EricAlla" <eric_allal@yahoo.fr>
 Date: Mercredi 28 janvier 2015, 21h18
 
 Scenario 1 that you described
 should not be happening. Code should decide show or not
 suggestions and then update UI. Without live sample or way
 to reproduce the issue I can not help.
 
 —
 Reply to this email directly or view
 it on GitHub.
