### ISSUE TITLE
selecting suggestions with Up or Down key

### ISSUE THREAD

**Issue by kumold** [devbridge/jQuery-Autocomplete#313]
No indication of selecting suggestion (which is inserted into input). No way to style suggestion, selected by up or down keys. Please fire some event or add some class to selected suggestion, so we could style it.

**Comment by tkirda** [comment]
It does add `autocomplete-selected` class. See styling section: https://github.com/devbridge/jQuery-Autocomplete#styling

Also check demo: http://devbridge.github.io/jQuery-Autocomplete/
