### ISSUE TITLE
Local search after a first query returned results

### ISSUE THREAD

**Issue by vialcollet** [devbridge/jQuery-Autocomplete#314]
Is it possible (using callbacks I guess) to cache a first result (after 3 characters have been entered for example) and switch to local if the user adds more characters?
Right now if we add characters to the same root search a new ajax call is triggered.
This would save a lot of time and save the server.
I could use the onSearchComplete in order to setup variables after a first search and then onSearchStart for the next search where I would check the variables (search term should have the same root and previous suggestions should not be empty) and then I switch from ajax source to local source.
My issue is that I don't think I can change the source to local from within the onSearchStart callback.

Please note I am not a js expert...ie my question.

Thanks

**Comment by tkirda** [comment]
You can use your own function for lookup. Just updated documentation, see custom lookup function in usage. You can have any logic that works for you here.
