### ISSUE TITLE
onSelect triggered when one item matches text

### ISSUE THREAD

**Issue by OlafurTr** [devbridge/jQuery-Autocomplete#317]
Hi,
The onSelect function is triggered if a single suggestion in the list matches and not only when the user "selects"

This means that a list autocomplete list with ~ 500 items will run the onSelect function if a single item matches. 
f.i. user is typing names. Types "jenny" and if there is a match for "Jenny" in the list of 500 others names, the onSelect will be triggered, even though the user is still typing.

This makes it impossible to include a redirect clause on user select, since it can be fired without any user action.

Is it possible to rename this to "onMatch" which seems to better reflect the behaviour or add another callback for "onClick" or something similar?

**Comment by tkirda** [comment]
Set `triggerSelectOnValidInput` to `false`, so that it would not trigger anything without user action. I will change the default to be `false` in future releases.

**Comment by OlafurTr** [comment]
Ah thanks.  I thought I had gone over the documentation but clearly I hadn't
