### ISSUE TITLE
up and down key sets the value of input. 

### ISSUE THREAD

**Issue by raj333** [devbridge/jQuery-Autocomplete#318]
while using up and down key on results, it selects the value of that particular suggestion without pressing enter.

Can it be disabled? that is the input element  should only be set on onselect.

**Comment by tkirda** [comment]
It just temporary replaces current value, if you escape of it, it will restore original value. You can disable this by setting `preserveInput` to `true`.

**Comment by raj333** [comment]
Thanks tkirda. It worked. You have an awesome job.
