### ISSUE TITLE
Show suggestions on click

### ISSUE THREAD

**Issue by lekastillo** [devbridge/jQuery-Autocomplete#319]
I need to do that when user click or focus the field text, the sugggestions show it. Help me please

**Comment by tkirda** [comment]
If you set minChars to zero it will show suggestions when you focus into the field.

**Comment by lekastillo** [comment]
Thank for your help

**Comment by Kristiansky** [comment]
Well, it's not working in my code man.

**Comment by BiteBit** [comment]
helpful
