### ISSUE TITLE
BUG: lookup entry.length < 3

### ISSUE THREAD

**Issue by azev** [devbridge/jQuery-Autocomplete#321]
The plugin won't work/load if there is an entry in the lookup array with length < 3
Eg:
myLookupArray = ['tag1', 'tag2', 'tag99' ] // ok:
myLookupArray = ['tag1', 'tag2', 'tg', 'tag99' ] // bug ('tg' length < 3)

**Comment by tkirda** [comment]
There is something incorrect in your setup. Length of the values has nothing to do with logic. Maybe you set `minChars` to 3 so it does not kick in until you type in 3 characters.

**Comment by azev** [comment]
I did not set `minChars`. It simply won't work for me if there is a lookup array with an entry which length<3

**Comment by tkirda** [comment]
Can not reproduce. Do you have a demo?

**Comment by azev** [comment]
Hello Thomas.

Thanks for answering!
I rewrote my code (related to the issue) from scratch and it works now.
I can't tell where it was wrong.
I get an array [] coming from an ajax call.

Thanks.
