### ISSUE TITLE
Implement searching via a webworker

### ISSUE THREAD

**Issue by tschallacka** [devbridge/jQuery-Autocomplete#322]
I have a really realy extensive searchlist(10.000+) and I would like to see that the search evaluation would happen in a webworker.
Right now when I wish to start typing in the textfield it takes about 1300 ms before I actually get something. The entire UI freezes.

Now if the onkeydown event would post its data to a webworker it would post back when it has it's compiled results, removing the need for an interval listener.

It might mean a significant rewrite to be redundant for browsers that don't support webworkers(ak. fall back to current mechanism) but it would add a great feature to this awesome script.

**Comment by tkirda** [comment]
It makes sense to offload search to web worker. However it makes sense only when you have a lot of data and logic how it should be filtered can vary from solution to solution. Simplest would be implementing worker logic yourself and then just plugging it in:

```javascript
    $('.your-input').autocomplete({
        lookup: function (query, done) {
            // ofload work to worker
            // do work
            // when done call 'done' and pass 'results'
            done(results);
        }
    });
```

Good luck!

Tomas
