### ISSUE TITLE
Launch function if no match found 

### ISSUE THREAD

**Issue by Wa3aR** [devbridge/jQuery-Autocomplete#323]
Hy ^^ 

First of all, thank you for this plugin, it's simple to use and very customizable ^^ a great plugin! 

The question is in the title. I tried to use plugin options but I didn't find a way to do that. 

Thanks in advance and sorry for my english ^^

**Comment by tkirda** [comment]
To display message you can set `showNoSuggestionNotice: true`. If you want to execute callback, you can use `onSearchComplete` and then check if there are any suggestions found.
