### ISSUE TITLE
Demo with Grouping Results for two Ajax lookup

### ISSUE THREAD

**Issue by Borak100** [devbridge/jQuery-Autocomplete#327]
Can you include some demo with Grouping Results for two Ajax lookup.
For example - how Grouping Results for:

$('#autocomplete-ajax1').autocomplete({
     serviceUrl:'autocomplete-ajax1.json',
});

$('#autocomplete-ajax2').autocomplete({
     serviceUrl:'autocomplete-ajax2.json',
});

Thanks!

**Comment by tkirda** [comment]
Not sure I understand the concept. Closing this since this is not really an issue.
