### ISSUE TITLE
Continue search if input matches suggestion

### ISSUE THREAD

**Issue by fschuetz04** [devbridge/jQuery-Autocomplete#332]
Is there a way to continue the search (ajax requests to the server), if the input value matches the only displayed suggestion?
The reason for this is: I've implemented a input dropdown for folder name suggestions, so if you type `Folder1` for example, the server would return all subfolders of `Folder1` for such a query, but Autocomplete doesn't continue the search because `Folder1` matches the displayed suggestion.

**Comment by tkirda** [comment]
You can pass slash as `delimiter` and it will continue. You just want to capture current entered path and pass it with a query.

**Comment by fschuetz04** [comment]
But it'd be much more user-friendly / intuitive if the suggestions would continue to display. At least in my opinion.

**Comment by tkirda** [comment]
Set `triggerSelectOnValidInput` to `false` and it will continue until user selects an item.

**Comment by fschuetz04** [comment]
Ah ok thanks :+1:
