### ISSUE TITLE
autocomplete frozen after first XHR

### ISSUE THREAD

**Issue by slifin** [devbridge/jQuery-Autocomplete#333]
Here is my server response: 

    {"query":"t","suggestions":[]}

When I go to type the next letter, then it doesn't send the next XHR to the server, there is no JavaScript error,

However if I change my back end code to return null instead of a empty array for the suggestions key then the functionality works (and subsequent ajax calls are made) but I get a lot of JavaScript errors complaining about length of null not existing:

    Uncaught TypeError: Cannot read property 'length' of null

Is there somewhere in the documentation where I am missing the full specification for the server response?

**Comment by tkirda** [comment]
This is intended behavior, you can set `preventBadQueries` to `false`, if you want to continue firing request with the same root.
