### ISSUE TITLE
Issue about back button

### ISSUE THREAD

**Issue by pablojacobi** [devbridge/jQuery-Autocomplete#334]
Hi, I'm using your plugin in a shopping form to auto complete the cities of my country. Everything in general works fine, but when the user press next, and (for any reason) wants to back to the previous step (the step with the auto complete), all the user fields remains except for the auto complete's value, which is empty.

This is a problem for me because I calculate the shipping cost depending on the city, so I need to ask to the user this value again.

Please let mw know how to fix this or if it is a bug.

Thanks in advance

Regards

**Comment by tkirda** [comment]
Autocomplete just sets input value. If there is anything else that needs to be preserved it is your  responsibility.
