### ISSUE TITLE
Suggestions stays open even if the query does not match result

### ISSUE THREAD

**Issue by saurabh-gohil** [devbridge/jQuery-Autocomplete#335]
Hi,
I am facing this issue where even if the input query does not match the result suggestion box stays open displaying all the results. I have used the no result option bu not luck with that also.
could you please suggest the fix.
thanks

**Comment by tkirda** [comment]
There is something wrong with the setup. Can not help without ability to reproduce the issue.

**Comment by saurabh-gohil** [comment]
Will it help if I provide my initialization and php code? and I am setting autocomplete with only one option minimum characters as 1.

**Comment by tkirda** [comment]
Do you have a live demo?

**Comment by saurabh-gohil** [comment]
After some searching I found that issue was with mysql query. I was sending all the result instead of using LIKE in mysql query. rectified the query and tweaked the json array little bit solved my issue.
Thanks for the awesome plugin and support
