### ISSUE TITLE
Is it possible to disable toLowerCase conversion?

### ISSUE THREAD

**Issue by mkrssl** [devbridge/jQuery-Autocomplete#338]
Hello,

Is is it possible to disable somehow lowercasing option for input field as well as for the result list? I couldn't find this in the settings list.

Best,
Marcin

**Comment by tkirda** [comment]
Not sure what you mean by this, there is no explicit lowercasing if you want to do case sensitive comparisons.

**Comment by mkrssl** [comment]
Hello,

What I mean is I start typing my search term like "Mar" and suddenly it's lowercased to "mar". 

Hope that explanation helps ;)

**Comment by mkrssl** [comment]
Nevermind. I found the right setting for that which is 
```javascript
preserveInput: true
```

Thanks anyway for quick reply. Issue can be closed I guess.
