### ISSUE TITLE
Enter/Tab key override option

### ISSUE THREAD

**Issue by akousmata** [devbridge/jQuery-Autocomplete#339]
This is somewhat more of a feature request because my use cases are specific but, I have 2 use cases to address that seem to conflict and cause the form to be submitted twice:

1.  The user types in the value and hits the enter key (handled by checking the keycode on the keyup event and then calling an ajax handler if it's the enter key to "submit" the form).
2.  The user arrow keys down to a suggestion and then hits the enter key.  In this scenario, the ajax is firing twice.  Once for the enter keypress handler and once for the onSelect handler.  I need the onSelect handler to work in every other case (mouseclick, etc.) the way it does right now, but need to prevent the second ajax call from happening.

I'm sure there's a workaround and am willing to implement one if you have a suggestion, but it would be nice to be able to turn off the tab/enter keys as firing the onSelect events so I can handle those myself.

**Comment by tkirda** [comment]
Not even sure how to handle this, you can fork the code and make changes so that it works for you. 

Or handle keyboard event on a parent node. Then if there is suggestion is being selected with ENTER key, this event should not propagate up because it is canceled by calling:

            e.stopImmediatePropagation();
            e.preventDefault();
