### ISSUE TITLE
onChange no longer supported?

### ISSUE THREAD

**Issue by vsdotnetguy** [devbridge/jQuery-Autocomplete#342]
We would like your autocomplete to handle both onSelect and onChange so that if the user just enters a value and presses enter or tab key, autocomplete will trigger the onChange event or at least trigger the onSelect and pass something that tells me the user did not select any suggestion.

Is this possible with version 1.2.16 as I can't seem to get the onChange event to trigger.

Thanks in advance,
Bob Baldwin
aka VSDotNetGuy

**Comment by tkirda** [comment]
Not quite sure what is the value of onChange. There is native [onchange](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/onchange) event on the input element.
