### ISSUE TITLE
Not Able to render suggestions as html

### ISSUE THREAD

**Issue by sheeshmohsin** [devbridge/jQuery-Autocomplete#343]
I want to render the suggestion as html. 
e.g my data is { "value": "<img src='/media/image.jpg'/> Caption", "data" : "anything" }
But the problem is that its not detecting the image src as html , it is simply shown as text. 
How can i render the value as html?
Please guide me.

**Comment by tkirda** [comment]
Use `formatResult` function if default implementation is not working for you.
