### ISSUE TITLE
Issues with empty result data / Character data not in suggestion list

### ISSUE THREAD

**Issue by AlphonsW** [devbridge/jQuery-Autocomplete#344]
I was using Version 1.2.14 of Ajax Autocomplete

There are issues (JavaScript Debugger hops in) when entering character data that could not be matched. The errors occur on two positions:

Position 1 (aroung line number 777): inside  processResponse: function (result, originalQuery, cacheKey) {
when following assignment is made:
result.suggestions = that.verifySuggestionsFormat(result.suggestions);

When result is empty, this call fails. 

Cure: 
       processResponse: function (result, originalQuery, cacheKey) {
            var that = this,
                options = that.options;
			// change
			if( !result ) return;
			// end
			result.suggestions = that.verifySuggestionsFormat(result.suggestions);

Position 2 (around line number 570): 

Cure:
                that.currentRequest = $.ajax(ajaxSettings).done(function (data) {
                    var result;
                    that.currentRequest = null;
                    result = options.transformResult(data);
                    // change, introduced check for result
					if( result ) {
						that.processResponse(result, q, cacheKey);
						options.onSearchComplete.call(that.element, q, result.suggestions);
					} else { // else part introduced
						options.onSearchComplete.call(that.element, q, []);
					} // change end

Since I have no practical experince with GITHUB yet I am not sure how to introduce these fixes. Therfore I just post this them hoping the behaviour could be verified and the fix can be introduced for the next release.

**Comment by tkirda** [comment]
Result can not be empty. If there are no suggestions it should return empty array.

Use `transformResult` if your server is returning different format.

**Comment by AlphonsW** [comment]
Thank you for the advice and hint (now I am generating correctly formatted empty suggestions on the server side.) ... and of course for sharing the library. It helped me a lot.

One final thought:
I do understand your view that result should not be empty, but you never know what users like me might end up doing.

All the best and thanks again for autocomplete.
