### ISSUE TITLE
Focus out event on mouse select

### ISSUE THREAD

**Issue by anubhav-aggarwal129** [devbridge/jQuery-Autocomplete#348]
I'm using form validation in an input field which has autocomplete on it.
The issue is when I select the option with mouse click, focus out event is called and it validates the field and throws validation error. The same is working fine if I hit Enter from keyboard.

I believe the issue here is focus not returning to the input field.
I didn't find any property like 'tabDisabled' to bring back focus to the input field.

Is there a way to handle this?

**Comment by tkirda** [comment]
There is no way to select item without loosing focus for the input field. You need to adjust your validation logic, or focus and blur input in the `onSelect` callback if this makes input valid.

**Comment by nroose** [comment]
I had this problem. One field form with autoselect and I wanted my users to be able to hit return after select.

coffeescript:
```coffeescript
      onSelect: ->
        setTimeout ->
          $navbarSearchTerm.focus()
        , 10
```

javascript:
```javascript
        onSelect: function() {
          return setTimeout(function() {
            return $navbarSearchTerm.focus();
          }, 10);
        }
```

**Comment by BlingPiece** [comment]
I had same problem, just call valid in the onSelect method. e.g.
```
$(".user-list").autocomplete({
                serviceUrl: '@Url.Action("GetAdUserNamesBeginningWith", "Services")',
                onSelect: function () {
                    $(this).valid();                    
                }
            });
```
However you will likely run into the same problem I now have which is when the user selects from the list using the keyboard and tab/enter it moves onto the next field as expected. However if the user selects with the mouse then the value appears in the input box validated correctly but the next input field must be manually clicked on to gain focus. 
I've tried setting the focus in the onSelect e.g.
```
$(".user-list").autocomplete({
                serviceUrl: '@Url.Action("GetAdUserNamesBeginningWith", "Services")',
                onSelect: function () {
                    if ($(this).valid() === true) {
                        if (this.name === 'Owner') {
                            $('#next-field').focus();
                        }
                    }
                }
            });
```
Now works fine... WITH MOUSE click. But if user uses keyboard and then Tab, the onSelect is called putting the focus into the next field. but then the tab event is fired so it goes onto the NEXT field (missing out the one I want).
