### ISSUE TITLE
Problem with example

### ISSUE THREAD

**Issue by fabiuz7** [devbridge/jQuery-Autocomplete#349]
THERE is a bug in the example from the website (https://www.devbridge.com/sourcery/components/jquery-autocomplete/): when I have 2 or more words, one prefix of the others, when the shortest one matches the query the suggestions for the longer
 disappear. This is not normal: in the official website this doesn't happen, neither with jQueryUI.

In this screen should be the suggestion for Dominicana and Dominica and Dominican Republic...

Maybe the problems are some settings, but for example jQueryUI works without any particular settings...

![screen shot 2015-04-10 at 23 14 54](https://cloud.githubusercontent.com/assets/7937648/7098354/720e102c-dfd7-11e4-9cb2-72e662cc9a58.png)

**Comment by tkirda** [comment]
Set `triggerSelectOnValidInput` to `false`.
