### ISSUE TITLE
Blur event doesn't apply the choice

### ISSUE THREAD

**Issue by iFgR** [devbridge/jQuery-Autocomplete#356]
When you use the arrows to navigate throw the options list and click in another element on the page you don't have the suggestion callback.

**Comment by tkirda** [comment]
From what you just described, there should not be callback, since you did not select anything.You need to hit element to select or hit ENTER.

**Comment by iFgR** [comment]
Yes, you're right!
I'm not speaking english correctly and I don't know to express correctly what I mean.

I get the Name and the ID of an item from ajax(PHP+MySql) with the autocomplete.
The name will be showed as text on a textfield and the ID will be stored in data-id tag on the same textfield.

When you are navigating with the arrow keys , the text is displayed in the text field as you change your choice but any ajax request are made and my textfield now have the text that I want but without the correctly data-id. If the user click in another field of my form I will have a trouble.

I did some adaptations in my fork to run correctly in my necessity. If you have another solution, please, teach me

**Comment by borgy65** [comment]
Hi Guys, newbie programmer here. I can't make this work with Php, MySql and jQuery. Care to help?
