### ISSUE TITLE
afterRender event?

### ISSUE THREAD

**Issue by vsdotnetguy** [devbridge/jQuery-Autocomplete#358]
Hi Tomas,

We really like this tool.  In certain situations, we use it within an IFrame based popup.  However, when the autocomplete textbox is near the bottom of the window, the suggestion container is clipped at the bottom of the window.

We would like to have an afterRender (after DOM injection) event so that we can call the RadWindow autoresize method in order to resize the IFrame to fit.

Is this a potential enhancement?

Thanks...VSDotNetGuy

**Comment by tkirda** [comment]
You can use `beforeRender` for this. `beforeRender` is called just before displaying it. So if inside your callback you do anything asynchronously, it will be the same as doing it in after render:

    beforeRender: function (element, container) {
        console.log('I am called before rendering.');
        setTimeout(function () {
            console.log('I am called after rendering.');
        }, 0);
    }

Makes sense?
