### ISSUE TITLE
Not Able to stop autoselect

### ISSUE THREAD

**Issue by sheeshmohsin** [devbridge/jQuery-Autocomplete#359]
when one of suggestions completely matches the user input, it gets auto selected, i want to avoid this because if user wants to input `superreceptionist`, but it autoselect another one which is `sup`. I tried using `autoselect` option and `tabDisabled` option. But these didn't work in this case. Please suggest some ways if it exists. You can see it live at http://scan.appwatch.io/

**Comment by tkirda** [comment]
Set `triggerSelectOnValidInput` to `false`.

**Comment by sheeshmohsin** [comment]
Thanks for quick response, works like charm :+1:
