### ISSUE TITLE
onSelect Event triggered on focus

### ISSUE THREAD

**Issue by dutchman71** [devbridge/jQuery-Autocomplete#360]
Hi,

First, thanks very much for creating this plugin - great job!
I have this issue: I'm initializing the autocomplete as shown below. For some reason, after an item was already selected, the 'onSelect' event is triggered when the input field receives focus. That doesn't seem practical since whenever a user clicks in the input field to make a different selection, another onSelect is triggered for the previously selected item.

Can you please advise how to prevent this?

Thanks!

$("input[name*='o_menu_items']").autocomplete({
						lookup: menuItems,
						onSelect: function (suggestion) {
							var menuItemId = suggestion.data;
							var menuItemName = suggestion.value;
							console.log('You selected: ' + menuItemName + ', ' + menuItemId);
							o.showSuccess('Ok',"The '"+menuItemName+"' was added to your order");
							
							RoomServiceOrderService.addToOrder(menuItemId, menuItemName);
						}
					});

**Comment by Earl977** [comment]
Hey, had this problem myself and I found the cause on lines 209 - 215

```
onFocus: function () { 
            var that = this;
            that.fixPosition();
            if (that.options.minChars <= that.el.val().length) {
                that.onValueChange();
            }
        },
```

Just remove the `  that.onValueChange();` from there for a quick fix.
For some weird reason every time the inputs gets focus, "value change" function gets triggered.

**Comment by dutchman71** [comment]
awesome! thanks for the snippet.

**Comment by tkirda** [comment]
Set `triggerSelectOnValidInput` to `false` to avoid automatic onSelect trigger.
