### ISSUE TITLE
triggerSelectOnValidInput when multiple suggestions are left

### ISSUE THREAD

**Issue by jvanegmond** [devbridge/jQuery-Autocomplete#361]
I ran into a problem when having a drop down with place names. The places are named as following:

Almere
Almere Haven
Almere Buiten

When an end user would type the first half of Almere Haven, Almere would automatically be selected and the suggestions for Almere Haven and Almere Buiten would disappear. This can confuse the end user.

A potential solution is disabling triggerSelectOnValidInput. However, in most cases you only have a single suggestion for the input so it makes a lot of sense to keep it enabled. 

The solution I thought of was to add a check for the number of given solutions. If it is greater than a single remaining one, don't close the suggestions box just yet. This would make a reasonable default behavior.

**Comment by jvanegmond** [comment]
This little bit of code, which is duplicated in 2 places, can be changed as following:

if (options.triggerSelectOnValidInput) {
	index = that.findSuggestionIndex(value);
	if (index !== -1 && that.suggestions.length == 1) {
		that.select(index);
		return;
	}
}

**Comment by tkirda** [comment]
Actually I was able to simplify this even further. Thanks for opening the issue.
