### ISSUE TITLE
Altering/Filtering Suggestions

### ISSUE THREAD

**Issue by Sigma-90** [devbridge/jQuery-Autocomplete#362]
I'm currently missing a callback to make changes to the suggestions before the HTML output is generated. This is quite an important feature (especially when using a local lookup), because the lookupFilter function only works on a per-suggestion basis but there is no way to maniplulate all suggestions as a group, which is important for tasks like sorting.

To implement this feature, only a few lines of code have to be changed:

Function "getSuggestions" (defined in line 526): 
Line 527 ff:
```javascript
var response,
    ...
    modifySuggestions = options.modifySuggestions,
    ...
```
Line 545 (was line 544 before adding the line above):
```javascript
if ($.isFunction(modifySuggestions)) {
    data.suggestions = modifySuggestions.call(that.element, data.suggestions, q);
}
```
Line 566 (before: 562):
```javascript
if ($.isFunction(modifySuggestions)) {
    response.suggestions = modifySuggestions.call(that.element, response.suggestions, q);
}
```

Line 589 (before: 582):
```javascript
if ($.isFunction(modifySuggestions)) {
    result.suggestions = modifySuggestions.call(that.element, result.suggestions, q);
}
```

Alternatively, the function could be added to the option defaults like this:
```javascript
modifySuggestions: function(suggestions, query){ return suggestions; },
```
That would remove the need to check for the function's existence before executing it, thus reducing the amount of lines to be added from 10 to 5. Both solutions are viable and both worked fine during my tests. I ended up with the second version, though, better for minification.

##### Why it should be added:

To understand why I think this is an important feature that should be included in future releases, let me present my current use-case that made it necessary to make these changes to the plugin's source code:

The client wanted to be able to enter multiple search terms divided by spaces and then the results were to be sorted based on how many of the terms a suggestion contained, so a search for "Blue Jeans" would find any entires with "blue" or "jeans", but those entries that contain both would be placed on top of the suggestion list. 

The first part was not that complicated, I just had to pass custom functions to options.formatResult and options.lookupFilter. For anyone interested, here's what I did:

formatResult: I copied the default Autocomplete.formatResult function and the utils.escapeRegExChars helper function from the source and then changed the line that defined the regex pattern to this, replacing any whitespace with a regex OR:
```javascript
var pattern = '(' + escapeRegExChars(currentValue).replace(/\s/g, '|') + ')';
```

And here's my custom lookupFilter:
```javascript
function (suggestion, originalQuery, queryLowerCase) {
    var words = $.trim(queryLowerCase).split(/\s/g);
    var is_match = false;
    for(i in words){
        if(suggestion.value.toLowerCase().indexOf(words[i]) !== -1){
            is_match = true;
        }
    }
    return is_match;
}
```

Worked like a charm, but now came the really tricky part: 
I had to sort all the suggestions based on match weight. On top of that, I also had another requirement: The lookup data contained alternate keywords for main terms that pointed to the main result. 
Example: 
```javascript
lookup: [{value: '@@@Pants', data: 1}, {value: 'Blue Jeans ( > Pants)', data: 1}, {value: 'Blue Shorts ( > Pants)', data: 1}, {value: '@@@Shirts', data:2}],
```
The tricky part: Only one suggestion of those that pointed to the same result was supposed to show up in the suggestion list. If the main term was matched directly, all alternate ones had to be removed (i.e. when searching for "pan", the 2nd and 3rd example suggestions are matches but have to be removed before rendering, because the first one is matched as well and is a 'parent term', indicated by the "@@@" - of course that marker tag gets removed before rendering). If only alternates for one main term were matched, only the first of the alternate terms with the highest amount of matches was to make it into the suggestion list (i.e. when searching for "blue j", the 2nd and 3rd suggestion would be matched because they both contain "blue", but only the second would be shown because it matches "j" as well, although in this case it would also be chosen if the second word was something that didn't match, because no.2 and no.3 both have 1 match and no.2 is the first of the two). 

All these necessary re-arrangements, string manipulations and filter-actions required that the suggestion array can be maniplulated before it is transformed into HTML, so the beforeRender function was out of the question. Therefore, I had no choice but to make the changes described above. 

I realized that this could be useful for all sorts of other tasks as well, for example to sort the suggestions based on some value in "data", or to rearrange the results so that those results are on top where the match occurs at the beginning of the suggestion instead of somewhere in the middle (basically, sorting by the result of "indexOf(query)"). That's why I decided to present my source code modifications here and make a case for the feature's future implementation.

Keep up the good work Tomas and thank you for creating this magnificient plugin!
And if you have actually read everything up to here, I'd also like to thank you for your patience. ;-)

**Comment by tkirda** [comment]
If you doing something fancy and custom, it is best to use custom `lookup` function where you can handle everything. API is already quite big and I don't want to add new things if it is possible to work with existing.

**Comment by laodemalfatih** [comment]
You can change default filtering function with property `formatResult`, example:

```
$("input").autocomplete({
   formatResult: function(suggestion, currentValue){
      return suggestion.value;
   }
});
```
Configuration above give input suggestion without any filter.Property `formatResult` have default function like code below:
[https://github.com/devbridge/jQuery-Autocomplete/blob/c8f6072ad9964203fda2a9f8cd5261afef5c15ee/src/jquery.autocomplete.js#L136-L151](https://github.com/devbridge/jQuery-Autocomplete/blob/c8f6072ad9964203fda2a9f8cd5261afef5c15ee/src/jquery.autocomplete.js#L136-L151)
