### ISSUE TITLE
Get suggestions in beforeRender()

### ISSUE THREAD

**Issue by bnekras** [devbridge/jQuery-Autocomplete#364]
Is there any way to get suggestions related to current items in beforeRender? For now I using some hack, but have feeling there must be an easier way.
Usecase: prepend suggestion item with related image from suggestions array

**Comment by tkirda** [comment]
If you updating item in a suggestion list, then it would be better to use `formatResult`. Otherwise it's probably ok to use `beforeRender`.

**Comment by bnekras** [comment]
But how to manipulate DOM inside formatResult?
