### ISSUE TITLE
No ajax lookup with leading zeros

### ISSUE THREAD

**Issue by oscargilfc** [devbridge/jQuery-Autocomplete#369]
I'm working on a zipcode finder.

    $(obj.ZCo).autocomplete({
		serviceUrl : 'script/CP',
		onSelect : function(suggestion) {
                       //Code here never executes when there are leading zeros.
		}
	});

I checked with chrome network tool and dicovered when there are leading zeros only performs one lookup with 0 and nothing after that.

![image](https://cloud.githubusercontent.com/assets/4994515/8021975/015a9752-0c7c-11e5-99fa-81c199742e79.png)

**Comment by tkirda** [comment]
Set `noCache` to `true`, it assumes that there are no suggestions for provided root.
