### ISSUE TITLE
Using named functions for onSelect/clearing selection value after onSelect

### ISSUE THREAD

**Issue by iampeatv** [devbridge/jQuery-Autocomplete#373]
Is it possible to define a function outside the .autocomplete () construction but still use it within the onSelect: config option and use the suggestion object that it returns?

Also, is there a way to clear the value for the input field as part of the onSelect function (i.e. selecting the value from the list of suggestions will do something with that suggestion object and return the value in the input field to null?

**Comment by tkirda** [comment]
Yes and yes. It's just plain JavaScript:

``` JavaScript
    $('.my-input').autocomplete({
        serviceUrl: '/my-service',
        onSelect: myOnSelectHandler
    });

    function myOnSelectHandler(suggestion) {
        // Do anything you want...

        // Reset input value
        // this is bound to input element
        $(this).val('');
    }
```
