### ISSUE TITLE
Binding autocomplete to dynamically created elements

### ISSUE THREAD

**Issue by ostumpfs** [devbridge/jQuery-Autocomplete#374]
Any thoughts on how to accomplish this?

Example:

```javascript
$(function() {
  $('.add_product').click(function(e) {
    e.preventDefault();
    id = $(this).data('product-id');
    template = '<input type="text" name="order[products][' + id + ']" id="product_' + id + '_name" />';
    $('#products').after(template);
    $('#product_' + id + '_name').autocomplete({
      lookup: products,
      onSelect: function (suggestion) {
        $('#product_' + id + '_lookup_name').val(suggestion.data);
      }
    });
  });
})
});
```

**Comment by tkirda** [comment]
This should work (ignoring the fact that JavaScript is sloppy, missing var when declaring varialbes). 

Inside `onSelect` you can use `this`, because it is bound to input element.

    onSelect: function (suggestion) {
          $(this).val(suggestion.data);
    }

**Comment by karmendra** [comment]
I did something as following using jquery on() with focus event for my table with dynamically added rows with an input filed.

`$('#mytable').on('focus', '.autocomplete-input', function () {
        $(this).autocomplete({
            serviceUrl: '/searchproduct',
            dataType: 'json',
            onSelect: function (suggestions) {
                 $(this).val(suggestion.data);
            }
        });

    });`

**Comment by Wave21as** [comment]
@karmendra It works for onSelect but not for onInvalidateSelection. Every time when u move cursor to .autocomplete-input, new Autocomplete object is assigned to element and all previous data are lost.
