### ISSUE TITLE
Problem with url

### ISSUE THREAD

**Issue by Emyleen** [devbridge/jQuery-Autocomplete#375]
Hello, I don't understand the documentation.
My ajax url is in this form : '../rpc.php?p=entreprises&a=ajax_get_list_site_user_not_child&admin=1'
and when I use it in the plugin I have a jquery error : TypeError: this.source is not a function
...complete-loading"),this.cancelSearch=!1,this.source({term:e},this._response())},...

I don't understand why? I want to formated my datas as you precognize but I can't print them in the console because I have this jquery error.

If I must use lookup function, can you show me how to do that? Because I don't understand the coments : // Do ajax call or lookup locally, when done,
            // call the callback and pass your results:

Thank you for your answer

**Comment by tkirda** [comment]
Looks like you are using other plugin. jQuery UI Autocomplete? There is not `cancelSearch` anywhere in the code.
