### ISSUE TITLE
Trigger onSelect

### ISSUE THREAD

**Issue by hotmeteor** [devbridge/jQuery-Autocomplete#378]
I'd like to optionally populate an autocomplete field from a querystring and trigger that field manually. Is this possible? I've tried every event in the plugin but none trigger an AJAX lookup.

Thanks!

**Comment by tkirda** [comment]
Call `instance.onValueChange()` on autocomplete instance after you set the value, or:

    $('.your-input').autocomplete('onValueChange');

This is not public API, but it should not change any time soon.

**Comment by hotmeteor** [comment]
Thank you!
