### ISSUE TITLE
Conflict with jQuery UI autocomplete

### ISSUE THREAD

**Issue by marcuzy** [devbridge/jQuery-Autocomplete#379]
jQuery UI have the same method.

**Comment by tkirda** [comment]
It is listed under known issues. If you are loading jQuery UI, then instead of `autocomplete` call `devbridgeAutocomplete`: https://github.com/devbridge/jQuery-Autocomplete#known-issues

**Comment by geekonthepc** [comment]
Still works today - had this issue with Joomla jQuery Autocomplete conflicting with use of jQuery UI in the theme.
Much appreciated workaround.

**Comment by Shnoulle** [comment]
@geekonthepc https://github.com/devbridge/jQuery-Autocomplete#known-issues …
