### ISSUE TITLE
Suggestion: method to trigger autocomplete

### ISSUE THREAD

**Issue by robertsinton** [devbridge/jQuery-Autocomplete#381]
I have a use case where the user is searching for a product, and can change which field they are searching on e.g. description, item code etc. (Not the best UX in the world, but the client insists…)

![image](https://cloud.githubusercontent.com/assets/788763/8563839/4a1a91d8-2598-11e5-81e4-7740d86341de.png)

I'd like to be able to trigger the autocomplete to run again if the user changes their choice of search criteria after starting to type a search value. A 'trigger' method feels like the right way to accomplish this.

At the moment I'm achieving the desired result with this rather cumbersome approach:

```
$(document).on('change', 'input[name="search_field"]', function() {
    var current_val = $('input[name="search_value"]').val();
    $('input[name="search_value"]')
        .val('').trigger('change')
        .val(current_val).trigger('change')
        .focus();
});
```

**Comment by tkirda** [comment]
You can simply call:

    $('input[name="search_value"]').autocomplete('onValueChange');

This will force plugin to do a lookup, you may also need to clear autocomplete cache, depends on how you formatting request url.

**Comment by robertsinton** [comment]
Ah — thank you, that's exactly what I was looking for!

I didn't see it in the documentation; would be worth adding :)

**Comment by tkirda** [comment]
This is not documented, but I probably should, because you are not the firs asking for this.
