### ISSUE TITLE
Auto open options list on focus

### ISSUE THREAD

**Issue by masimao** [devbridge/jQuery-Autocomplete#383]
Hi,

Is it possible auto open the options list when the user focus the input? [Here is an example](http://demo.mysamplecode.com/JQuery/pages/dropdownUsingAutoComplete.jsp) with another plugin.

**Comment by pyrux** [comment]
Simply set  minChars: 0 

"""
var tags = [
         { value: 'California', data: 'CA' },
];

$('#filter')
   .autocomplete({
        lookup: tags,
        minChars: 0,
});
"""
