### ISSUE TITLE
Autocomplete loading very slow with while trying to remove accents.

### ISSUE THREAD

**Issue by SimonKomlos** [devbridge/jQuery-Autocomplete#388]
I have a list of over 120,000 rows that I'd like a user to be able to search through. At the moment it is quite unresponsive. When I type a letter it feels like it takes a good second before it actually displays the letter. 

The problem isn't really the large list, but I have found out that the problem in fact is that I am trying to remove accents from the search so that if someone types in `a` or `ä` they get the same results. 

My settings are: 

    lookup: list,
    lookupLimit: 5,
    minChars: 3,
    delay: 200,
    lookupFilter: _autocompleteLookup,
    formatResult: _autocompleteFormatResult, 

Here is how I am trying to remove the accents:

      var _formatRegexp = function(q) {
          q = q.replace(/e/i,'[eéèêëEÉÈÊË]');
          q = q.replace(/a/i,'[aáàâäåæAÀÁÂÃÄÅÆ]');
          q = q.replace(/c/i,'[cçC]');
          q = q.replace(/i/i,'[iïîíìIÌÍÎÏ]');
          q = q.replace(/o/i,'[oôöœøOÒÓÔÕØÖ]');
          q = q.replace(/u/i,'[uüûúùUÜÛÙÚ]');
          q = q.replace(/y/i,'[yYÿýÝŸ]');
          q = q.replace(/z/i,'[zžZYŽ]');
          q = q.replace(/s/i,'[ŠšsS]');
          q = q.replace(/n/i,'[nNñÑ]');
          return q;
      }
      
      var _autocompleteLookup = function (suggestion, originalQuery, queryLowerCase) {
              var pattern = '(\\b|^)('+$.Autocomplete.utils.escapeRegExChars(queryLowerCase)+')';
              pattern = _formatRegexp(pattern);
              var matcher = new RegExp(pattern);
              var ret = suggestion.value.toLowerCase().match(matcher);
              return ret;
      };

      var _autocompleteFormatResult = function (suggestion, currentValue) {
             var pattern = '(\\b|^)('+$.Autocomplete.utils.escapeRegExChars(currentValue)+')';
              pattern = _formatRegexp(pattern);
              return suggestion.value.replace(new RegExp(pattern, 'gi'), '<strong>$1$2<\/strong>');
      };

Is there anything I can do to make the autocomplete faster? I really do need the checking for accents since a lot of my values in my list contain them. Any thoughts? 

Thanks.

**Comment by tkirda** [comment]
You should normalize list of values that you have and then when user enters value normalize that value and check against your list using `indexOf`. This will be MUCH faster.

``` javascript
function normalizeValue(q) {
    q = q.replace(/[éèêë]/g, 'e');
    q = q.replace(/[áàâäåæ]/gi, 'a');
    q = q.replace(/[ç]/gi, 'c');
    q = q.replace(/[ïîíì]/gi, 'i');
    q = q.replace(/[ôöœø]/gi, 'o');
    q = q.replace(/[üûúù]/gi, 'u');
    // ...
    return q;
};
```
Your lookup then should be:

``` javascript
function _autocompleteLookup(suggestion, originalQuery, queryLowerCase) {
    var normalizedQuery = normalizeValue(queryLowerCase);
    var ret = suggestion.data.normalizedValue.indexOf(normalizedQuery) === 0;
    return ret;
};
```
Format result can stay the same.

**Comment by SimonKomlos** [comment]
@tkirda I'm getting an error of `Cannot read property 'indexOf' of undefined` for the `var ret` line. I can't quite see what the issue is. I thought at first it was the misspelling of `normalizeValue` but that doesn't seem to be the case. Any insight? Thanks.

**Comment by tkirda** [comment]
You need to prepare this property in advance on your data. `normalizedValue` or you can call anything you want should be a string.

**Comment by SimonKomlos** [comment]
@tkirda Thanks for replying so quickly. I'm not sure I understand.. Could you elaborate a bit more?

**Comment by tkirda** [comment]
You have an array of lookup data. Before you initialize autocomplete you need to prepare your data, so that lookup is fast:

```javascript
var lookupArray = [...];

lookupArray.forEach(function (suggestion) {
    suggestion.data = { normalizedValue: normalizeValue(suggestion.value) };
});
```

**Comment by SimonKomlos** [comment]
Sorry to bother you again. Everything seems to be working well, but the combobox doesn't seem to show a drop down after typing. 

Does something have to be changed in the `FormatResults` function?

        var _autocompleteFormatResult = function (suggestion, currentValue) {
               var pattern = '(\\b|^)('+$.Autocomplete.utils.escapeRegExChars(currentValue)+')';
               pattern = normalizeValue(pattern);
               return suggestion.value.replace(new RegExp(pattern, 'gi'), '<strong>$1$2<\/strong>');
        };

--`autocompleteLookup`

        function _autocompleteLookup(suggestion, originalQuery, queryLowerCase) {
            var normalizedQuery = normalizeValue(queryLowerCase);
            var ret = suggestion.data.normalizedValue.indexOf(normalizedQuery) === 0;
            return ret;
        };

**Comment by tkirda** [comment]
I have no idea without seeing it live.
