### ISSUE TITLE
Is there a way to display results with animation

### ISSUE THREAD

**Issue by TyrionGraphiste** [devbridge/jQuery-Autocomplete#390]
Hi,

I recently used the library and need to display results from the AJAX request with specific animation.
I tried some tests with given methods in configuration and presentation settings but it seems there is no way to do this.

Is there another way ?

Thank you.

**Comment by tkirda** [comment]
Have never tried doing animations, may try playing with CSS transitions, otherwise change current implementation.

**Comment by TyrionGraphiste** [comment]
There is no way with CSS transitions in the current state of the script, so I modified.
