### ISSUE TITLE
Back button issue

### ISSUE THREAD

**Issue by orrd** [devbridge/jQuery-Autocomplete#393]
When hitting the browser back button any values entered by the user into the debridge autocomplete input fields are lost. This issue was previously submitted as issue #334, but it was closed because I think tkirda misunderstood what problem they were describing.

When you use the back button to go back to a form, as long as the page is cached, normally the form fields are displayed with the same values you entered intact.  But any fields that use devbridge autocomplete lose the values that were entered by the user, and instead it shows the original field values instead.  

It turns out jQuery UI's autocomplete has the same issue, and I found [a blog post](http://www.bradoncode.com/blog/2012/03/jquery-ui-autocomplete-back-button.html) that explains the problem and a solution.  The problem is that autocomplete sets `autocomplete=off`.  That's what's causing Firefox and Chrome to not correctly remember the user's input.  

Possible solutions/workarounds: Maybe make devbridge autocomplete not set `autocomplete=off`at all (if it doesn't really have to be turned off)?  Or at least make that an option.  If the web browser autocomplete is a problem, maybe just turn it off when the field is selected, but turn it back on when the field loses focus?

Edit:
- http://bugs.jqueryui.com/ticket/7790 - jQuery UI's solution was to remove the "autocomplete" DOM attribute with a `beforeunload` function.  See https://github.com/jquery/jquery-ui/blob/master/ui/autocomplete.js#L328-L335.

**Comment by mamcx** [comment]
+1

I hit the same issue

**Comment by tkirda** [comment]
This will not be fixed. Use jQuery autocomplete if this still an issue.
