### ISSUE TITLE
Triggers select on exact match when more than one suggestion is available

### ISSUE THREAD

**Issue by Rjs37** [devbridge/jQuery-Autocomplete#398]
I use this for a username search against a very large database and I recently came across this strange quirk. If there's an exact match found, it will trigger the select even if there's more than one suggestion being returned.

I was able to get around this by setting triggerSelectOnValidInput to false, but really it should be checking for an exact match AND just one result returned before triggering the select.

For example, if my username was "RobertJS" but you had Robert, Robert2, RobertS all in the database, as soon as you type "Robert" all the other suggestions will disappear. When you have tens of thousands of usernames then this situation becomes rather common!

**Comment by tkirda** [comment]
You may just need to upgrade to latest version. This has been updated a while ago:

https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L494
