### ISSUE TITLE
When searching for '&' the suggestion box shows '&amp; as highlight.

### ISSUE THREAD

**Issue by MiscoriaDennis** [devbridge/jQuery-Autocomplete#399]
Title is quite self explanatory :)

When searching with query "&" the suggestion shows:
"This is the first suggestion with an &amp;"

When searching with query "first" the suggestion shows the ampersand correct:
"This is the first suggestion with an &"

So I believe it has something to do with the highlighting of an ampersand.

Regards

**Comment by tkirda** [comment]
It was addressed in the https://github.com/devbridge/jQuery-Autocomplete/commit/3328147b93c1650beb78278b41aab79ad4ad9173

I just need to release new version, should be done later tonight.

**Comment by tkirda** [comment]
New version has been released, you can get it via NPM, Bower or direct download.
