### ISSUE TITLE
Bug closing list when using $(document).on ...

### ISSUE THREAD

**Issue by leslie-UFT** [devbridge/jQuery-Autocomplete#400]
Good evening! I Modified plugin, because usually when you use fields Insertion via ajax , and this field has an autocomplete . So always use:
 $ ("# field ' ) . Autocomple ( ... )
step using the following:
$ (document) .no ( ' keyup ', '' # field ' , function () {
      $ (This) .autocomple ( ... ) ;
});
I liked the send commit with update but I'm not getting. How I can contribute?

**Comment by leslie-UFT** [comment]
I update code of line 966-968 and 970 removed lines and modify to:
// If instance already exists, destroy it:
if(instance === undefined) {
      instance = new Autocomplete(this, options);
}

**Comment by leslie-UFT** [comment]
I update code of line 966-968 and 970 removed lines and modify to:
// If instance already exists, destroy it:
if(instance === undefined) {
      instance = new Autocomplete(this, options);
}

With I solved my problem!

**Comment by tkirda** [comment]
I'm glad you solved your issue,
