### ISSUE TITLE
Documentation : dataType can be "json" too (instead of just "text" or "jsonp")

### ISSUE THREAD

**Issue by H-Max** [devbridge/jQuery-Autocomplete#401]
This way, returned string result will be a casted to object (if it can be).

Most useful when using non standard query/results.

**Comment by tkirda** [comment]
`text` and `json` is the same, even if it's text you will get parsed JSON by default, unless you receiving response that is not valid JSON and want to transform it yourself. Adding `json` to the list.

**Comment by H-Max** [comment]
Well if I set dataType to 'text' it's not working for me (response remains a string and generates 'Uncaught TypeError: Cannot read property 'length' of undefined'), but it does work if I set dataType to 'json' (it does not either if I set it to 'jsonp', obviously).

So 'text' being the default value, I have to explicitely set it to 'json'.

I'm using Chrome 44.0.2403.155, and my JSON response is valid JSON (used a validator to double check that).

(BTW, this plugin rocks)

**Comment by tkirda** [comment]
Hm, which line gives you this error? 

Also, if returning json, set response headers for `Content-Type` to `Content-Type: application/json` and jQuery automatically will parse response.

**Comment by H-Max** [comment]
The response content type is actually :
```
Content-Type:application/json;charset=utf-8
```

The error append with jQuery $.map because response is not an object : 

```javascript
return {
    suggestions: $.map(response.values, function(dataItem) {
        return { value: dataItem.name, data: dataItem.id };
    })
};
```
