### ISSUE TITLE
lookup array with serviceUrl

### ISSUE THREAD

**Issue by maxsalven** [devbridge/jQuery-Autocomplete#404]
I'd like to use both a local array and an Ajax call. I have the most commonly used results of my autocomplete stored on the client side as a javascript array, which I can feed to the lookup parameter. I then also want to make an Ajax query that appends whatever it returns to the local array.

However if `lookup` is set to an array, it seems to never fire an Ajax call.

I can write my own `lookup` function:
```javascript
lookup: function (query, done) {
  var result = { suggestions: localResults.filter(option => option.value.toLowerCase().indexOf(query.toLowerCase()) > -1) };
  if (result.suggestions.length) done(result);
  $.ajax({
    url: '/movements/autocomplete?query=' + query,
    dataType: 'json',
    type: 'GET',
    success: function(data) {
      result.suggestions = result.suggestions.concat(data.suggestions);
      if (data.suggestions.length) done(result);
    }
  });
}
```

But then I lose access to things like `preventBadQueries` and also a lack of caching: if there are matching results in both the local and remote datasets, I get a weird flicker (with every keystroke, it draws first just the matching local result, and then subsequently draws the ajax result, and then with the next keystroke, it draws just the local result and deletes the previously visible ajax result and then redraws it once the query completes).

Is there a 'best way' to do this? If not, is there a way to access the 'old' suggestions object when in the `lookup` function so I can do my own caching?

**Comment by tkirda** [comment]
That's a complicated use case, why don't you wait for server response and then display combined suggestions. That callback should really be called once.

Regarding caching, if you need it, you should cache results yourself, it is fairly straightforward.

Same thing with bad queries, you would need to track it. Basically if you are doing lookup yourself, then it's up to you what to return for a given query.
