### ISSUE TITLE
Autocomplete results only appear after a user has finished typing

### ISSUE THREAD

**Issue by benstevens48** [devbridge/jQuery-Autocomplete#410]
As far as I can tell from the code (sorry if I'm wrong), if the server takes more time than the time between keystrokes to return the suggestions then the autocomplete list will not be shown until after the user has finished typing because the ajax request is aborted. I suggest having a pending request as well as a current request, and not aborting the current request when the input changes, but instead replacing the pending request, which is called after the current request has completed. I can imagine more complicated systems as well involving simultaneous requests and queues etc... but this issue is preventing the autocomplete from being much use to me in a search box as the user has already finished typing their query before it offers any suggestions.

**Comment by tkirda** [comment]
Not sure what you mean by "replacing pending request", also if default implementation is not good enough, you can provide your own `lookup` function, where you can have full control over xhr requests.

Aborting actually benefits performance, since there is limit on concurrent requests from a single domain.

**Comment by benstevens48** [comment]
Ok, I will have a go at implementing my own lookup function - I like the fact that there are a lot of configuration options. 

My suggestion was that there is still only one request made at a time, but you always wait for it to complete rather than aborting it. By 'pending request' I meant storing the next request to be made after the current request has completed. I can see that this might have other side effects so it might have to be enabled via a configuration option or something, but at least the user would get some suggestions whist they are typing. As far as I can see, at the moment, if the getSuggestions function is called before the current request is complete, then the current request is aborted, meaning that if a user types fast in the text box associated with the autocomplete list then they don't get any suggestions until after they have finished typing (compare this behaviour against eg Google search).

Also I'd like to add that I really like this component apart from this issue. I've been using it for a while but I only noticed this problem recently, I think because I was running everything on my local machine and have only just started to test it on an actual server.

**Comment by tkirda** [comment]
If you stack xhr requests, performance will just get worse, because you would delay other requests.

Displaying suggestions based on what was typed a moment ago, may not actually be right suggestions, especially if data set that we are working against is large. It might be ok in some cases. Therefore I chose to display suggestions only for the current query assuming that results from the server or local lookup are fast enough.

If server responds slowly then whole concept of suggestions falls apart.

**Comment by benstevens48** [comment]
Yes I think I might have to speed up my server response.

I also think that any other implementation like the one I suggested is probably going to end up being too specific to include as default behaviour so overriding the lookup function as you suggest is probably the best way.

I wasn't necessarily thinking about a stack of requests, just a current one, and one to be made after the current one has completed (which would use the most recent user input at the time the current request completes). It would introduce a bit of lag though, I agree. What I imagine is that the server would send more suggestions than are actually intended to be displayed, and then these could be filtered client-side based on the most recent user input. This is probably a bit too complicated for the default implementation though.

Something that's slightly related is the parameter that allows you to delay requests. I think it would be better if this set the minimum time between making requests. At the moment, as far as I can see (please correct me if I'm wrong), the timeout is restarted whenever the user input changes.

**Comment by tkirda** [comment]
Yes, delay is just to prevent issuing requests if user types quickly. This is useful if you want to save server resources. I prefer just issue request, but then discard it if it is no longer needed.

**Comment by sharmun** [comment]
How can I show all suggestions before the user typing anything?

**Comment by tkirda** [comment]
Set `minChars` to `0`, for suggestion to be displayed when input receives focus.
