### ISSUE TITLE
Making suggestions width equal to ipunt width

### ISSUE THREAD

**Issue by xikobe** [devbridge/jQuery-Autocomplete#414]
My input had 400.3px so the suggestion box width was always rounded to 400:
![wrong_width](https://cloud.githubusercontent.com/assets/6670607/10016625/4c5668fa-6120-11e5-9748-06b59823b617.jpg)

if you use :

if (that.options.width === 'auto') {
   styles.width = (that.el[0].getBoundingClientRect().width) + 'px';
}

instead of:

if (that.options.width === 'auto') {
    styles.width = (that.el.outerWidth() - 2) + 'px';
}

the width is not rounded and the size is correct.

![right_width](https://cloud.githubusercontent.com/assets/6670607/10016662/8b5e134a-6120-11e5-9304-9b1581a8654f.png)

thanks for the great plugin!!

**Comment by nicmon** [comment]
+1

**Comment by swey** [comment]
+1

At the moment it's not working with different box-sizings and needs a 1px border.

Also not working is 100%in a container because 'px' is always added.

**Comment by swey** [comment]
I created a pull request for that (as you can see above).
