### ISSUE TITLE
How to highlight suggestions when using formatResult

### ISSUE THREAD

**Issue by vestaxpdx** [devbridge/jQuery-Autocomplete#417]
Hi,

Amazing plugin! Best autocomplete by far.

However when I am using formatResult so I can customize the result set the highlighting of what you have typed function stops working.

````
formatResult: function (suggestion, currentValue) 
{
      return '<div class="my-class"><img src="..." /><span>'+ suggestion.value +'</span></div>';
}
````

Am I doing something totally wrong here? The only way I could get it to work was by copying your Autocomplete.formatResult function and placing it outside your plugin so I can call it like so:

````
return '<div class="my-class"><img src="..." /><span>'+ formatResult(suggestion.value, currentValue) +'</span></div>';
````

I am sure I am doing something wrong but can't see any examples in the docs.

Hope you can help.

Thanks,

**Comment by tkirda** [comment]
Yes, because highlighting is part of the default formatResult. In your callback you can call it like this:

```javascript
    formatResult: function (suggestion, currentValue) 
    {
          return '<div class="my-class"><img src="..." /><span>'+ $.Autocomplete.formatResult(suggestion, currentValue) +'</span></div>';
    }
```

**Comment by vestaxpdx** [comment]
Awesome thanks for the speedy answer!

**Comment by Tushant** [comment]
```javascript
$(document).ready(function(){
    'use strict';
    $('#q').autocomplete({
    serviceUrl: "/search/autocomplete/",
    minChars: 2,
    dataType: 'json',
    type: 'GET',
    formatResult: function (suggestion, currentValue) {
        return '<a href="'+suggestion.url+'"><li class="list-group-item">'+$.Autocomplete.formatResult(suggestion, currentValue) +'</li></a>';
    },
});
});

```

Why clicking in the suggestion item, I am not redirected to another page, though I am using anchor tag?

**Comment by qqilihq** [comment]
FYI:

> `$.Autocomplete.formatResult(suggestion, currentValue)`

… this wasn’t available in my case. I had to use the following to get the default implementation:

> `$.Autocomplete.defaults.formatResult`

(probably also caused due to the minification)

**Comment by atefBB** [comment]
@Tushant How did you solve `redirecting to another page` prob?!
