### ISSUE TITLE
Possible Performance improvement [Client Side]

### ISSUE THREAD

**Issue by sdkcarlos** [devbridge/jQuery-Autocomplete#418]
Actually , the autocomplete is creating an AJAX Request everytime the user press a key and if there's a quick press again, the previous Request is **cancelled** which makes only 1 request at the server, perfect.

The problem is the performance get involved in the client side, see the times in the following image.

![See the times](https://cloud.githubusercontent.com/assets/11634719/10094827/34179000-632a-11e5-810d-a3512a7d3345.png)

**The time that takes canceling the previous AJAX is considerable ... and causes extensive waiting times for the user to see the result !**

There's a way to prevent this ? 

If is not, there's a way to improve that request by something like the following ?

```javascript
var previousTimer = 0;

 $("#emailrecheckform").on('keydown', function() {
  // cancel any previously-set timer
    if (previousTimer ) {
       clearTimeout(previousTimer );
    }

     previousTimer = setTimeout(function() {
        /// HERE SEND FINAL REQUEST OF DEVBRIDGE
     }, 400); //delay time in milliseconds
  });
```

Thanks !

**Comment by tkirda** [comment]
See `deferRequestBy` option in documentation, it does exactly what you described.
