### ISSUE TITLE
Ajax request not populating suggestions box.

### ISSUE THREAD

**Issue by CuppaJoseph** [devbridge/jQuery-Autocomplete#419]
I've built a simple ajax plugin using Autocomplete to check residential addresses against a database. 
The autocomplete was working perfectly on my local server, but when I moved the plugin to a live server the suggestions box is not populating with the suggestions.

In my console, i can see the GET response is retrieving the right information but the suggestions div isn't loading it.

**Comment by tkirda** [comment]
Can not help you based on information you provided. There is something on your end.
