### ISSUE TITLE
Autocomplete not working well in Laravel

### ISSUE THREAD

**Issue by aaesis** [devbridge/jQuery-Autocomplete#421]
Hi I am implementing autocomplete via service link json.

here is the code:
Link: http://blah.com/application/getjsonuser 
Link above generate json sample:
{"suggestions": [{"value": "Mich Yo", "data": 1},{"value": "Adams Apple", "data": 2 } ... ]}

Issue is when I added a text on the autocomplete field with same value I want to search, some of the items won't disappear. As you can see screenshot below:

Adams Apple should only be seen.

![screenshot](https://cloud.githubusercontent.com/assets/802180/10355640/01a58b64-6da1-11e5-9a17-e6715cabb1ca.jpg)

I just follow the instructions I clone this repo and use the script files. Am I missing something?

**Comment by tkirda** [comment]
If you know all values ahead and result set is relatively small then assign those values to lookup. If you hitting server for lookup, return already filtered list.

**Comment by aaesis** [comment]
what do you mean hitting server for lookup?

**Comment by tkirda** [comment]
Is your lookup using ajax or is it local lookup? By server lookup, I mean responding to ajax request as user types.

**Comment by aaesis** [comment]
this is the  code: using Ajax

    $('#autocomplete-ajax').autocomplete({
	    serviceUrl: '/application/getjsonuser',
	    dataType: 'json',
	    paramName: 'bla',
	    type: 'GET',
	    onSelect: function (suggestion) {
	        alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
	    }
	});

**Comment by tkirda** [comment]
This means that as user types, server needs to return filtered already, whatever server returns will be displayed in suggestions.

**Comment by aaesis** [comment]
thats the the use of paramName its like /applications/getjsonuser?query=Adams

so my php codes needs to return a filtered query already. Am I correct?

**Comment by tkirda** [comment]
Yes

**Comment by aaesis** [comment]
ughh sorry for a very not a smart question :( . thumbs up to you tkirda. Thanks for your time :)
