### ISSUE TITLE
sort before suggestion limit

### ISSUE THREAD

**Issue by radosavljevic** [devbridge/jQuery-Autocomplete#425]
Hi, this is a great plugin, thank you for you efforts.

Can you sort the suggestion array before it gets sliced (lookupLimit)?

**Comment by radosavljevic** [comment]
Here's one way to do it:

            if (limit && data.suggestions.length > limit) {
                if (typeof options.sortBeforeLimit != "undefined" && typeof options.sortBeforeLimit == "function") {
                    data.suggestions = options.sortBeforeLimit(data.suggestions);
                };
                data.suggestions = data.suggestions.slice(0, limit);
            }

**Comment by tkirda** [comment]
Best would be to pass lookup as a function which returns results to be displayed, then you can filter and sort any way you want.
