### ISSUE TITLE
.autocomplete not bound to elements loaded later

### ISSUE THREAD

**Issue by jakenoble** [devbridge/jQuery-Autocomplete#426]
If a new element with the class autocompletes is added into the DOM then `.autocomplete` does not pick this up and the autocomplete fails. Is there anyway around this?

```
$('.autocompletes').autocomplete({
});
```

I would usually do something like this and bind the event to a container, but I cannot see how to do this with `.autocomplete`.

```
$(".container").on("click", ".something", function(e){
});
```

**Comment by tkirda** [comment]
For dynamically added components you may listen for focus event and if there is no autocomplete instance attached you can initialize it there.

**Comment by mricherzhagen** [comment]
I encountered this problem and solved it by disposing the old autocomplete instances when a different element that matches the class is focused.
First i tried to dispose the instances when the unfocus(blur) happens, but that made it impossible to select suggestions with a mouseclick.

```javascript
var autocompleteOptions = {/*...*/}
(function () {
    var currentautocomplete = null;
    $(document).on('focus', '.autocompletes', function(){
        if (currentautocomplete != null && currentautocomplete != this) {
            $(currentautocomplete).autocomplete().dispose();
        }
        $(this).autocomplete(autocompleteOptions);
        currentautocomplete = this;
    });
})();
```

Are there any problems with this approach i should be aware of?

**Comment by tkirda** [comment]
Looks like that should be OK.
