### ISSUE TITLE
Multiple search parameters

### ISSUE THREAD

**Issue by tr33m4n** [devbridge/jQuery-Autocomplete#428]
Hello there,

Just wondering whether there's a way of having the autocomplete find entries when using, for example, a product name and product code? So the end user could type in either the product name or the product code and the autocomplete would return the same results

Cheers

**Comment by vialcollet** [comment]
Hi
I guess you would have to manage this at the server level. The REST call should trigger a query where you filter on name OR code.

**Comment by tr33m4n** [comment]
Cool, will give that a try, thanks

**Comment by DarkCobalt** [comment]
You can send more parametrs using url, like this:
                `serviceUrl: '/admin/autocomplete/model_car?model='+$('#autocomplete_marka_id').val(),`

**Comment by tkirda** [comment]
`serviceUrl` can be a function which returns url with any number of parameters.
