### ISSUE TITLE
Problem with position fixed

### ISSUE THREAD

**Issue by CavalcanteLeo** [devbridge/jQuery-Autocomplete#430]
My site has a navigation bar on top, that is fixed

and as soon as I scroll the page, the .autocomplete-suggestions div scrolls together with the page

How to set to .autocomplete-suggestions to be fixed too, instead of absolute?

**Comment by tkirda** [comment]
In your case it would be best to provide custom container where to render suggestions and you can position it any way you like.

See `appendTo` property in the documentation.
