### ISSUE TITLE
All Items if I don't know what can I type (like combobox)

### ISSUE THREAD

**Issue by enti333** [devbridge/jQuery-Autocomplete#431]
Hello. This control is perfect but I didn't find the solution how to achieve that this control will also work like a combo box...Many users know what they are looking for so they start to typing the text but much more users don't know what can they type so they need to choose from all options (like in combo box). Hmm...Is this possible somehow...Thank you

**Comment by tkirda** [comment]
Currently there is no way make it work like combo box. Pull requests are welcome.
