### ISSUE TITLE
minChars: 0 inserts tons of tags

### ISSUE THREAD

**Issue by matthew-dean** [devbridge/jQuery-Autocomplete#434]
The suggestion for auto-showing the dropdown is to set ```minChars: 0``` in the options. This sort of works, unless you have a long list. I was wondering why it took so long to display until I looked at the DOM.

<img width="190" alt="screen shot 2015-11-01 at 2 37 47 pm" src="https://cloud.githubusercontent.com/assets/414752/10871809/cea350c0-80a6-11e5-99f0-c12faefe4dac.png">

It inserts empty strong tags everywhere, which, in my case, means that the auto-suggest box takes several seconds before it opens each time, because of so much repainting that has to happen.

Compounding this is adding ```display: none``` when you're hiding the box. This causes document reflows (as does visibility: hidden) because the browser has to measure all the elements again in order to figure out scroll height. If you set something like ```margin-left: -9000px;```, then showing / hiding is instantaneous because it's just repainting that little area (and the box is only measured once), not reflowing/repainting the entire document.

Also, it would make sense to not add ````<strong>``` matches at all for elements that are off-screen (scrolled out of view), but that gets a bit more advanced.

**Comment by tkirda** [comment]
Yes, this was side effect of highlighting suggestions, because regex matched everything between characters when current value was empty.

**Comment by mshka** [comment]
Wow thank you so much for the fix that was a real issue in some languages, looking forward for the realise of this version...when is it expected ? :fireworks: :grin: :grin: :+1:
