### ISSUE TITLE
Keep suggestions list visible on blur

### ISSUE THREAD

**Issue by fidoboy** [devbridge/jQuery-Autocomplete#435]
Hi, I'm trying to keep the suggestions list with results visible when the input field looses the focus. There is any option or method to achieve that? How can I keep the list displayed even when the input does not have the focus on it?

**Comment by tkirda** [comment]
Intention is to hide suggestions when user navigates away from input field. You will need modify source to change this behavior.

**Comment by fidoboy** [comment]
Thanks @tkirda. There is no plans to add such option to the plugin? May be it could be useful for other users too

**Comment by tkirda** [comment]
No plans for now.
