### ISSUE TITLE
Not only matched suggestions in the list

### ISSUE THREAD

**Issue by ProctaInternetSolutions** [devbridge/jQuery-Autocomplete#436]
I do a json lookup and I get the data back. Everything is working but the list with suggestions shows any result and not only the matched ones.
Doing the same locally, everything is working perfect.
???

**Comment by ThomasDK81** [comment]
Got the same issue. The whole list is shown though the matches are put in a strong container.
Don't wan't the whole list, only matches.

**Comment by jamesburrow23** [comment]
I also experienced this issue...Its caused by not calling the lookup filter function for remotely called json data...I've been going crazy trying to get it to filter properly and finally have success...I'll attach my code snippets that solved the problem for me

1. Copy the code below and paste into line 533 at beginning of getSuggestions function of the jquery.autocomplete.js file
```
getSuggestions: function (q) {
            var response,
                that = this,
                options = that.options,
                filter = options.lookupFilter,
                serviceUrl = options.serviceUrl,
                queryLowerCase = q.toLowerCase(),
                params,
                cacheKey,
                ajaxSettings;

            if ($.isFunction(options.lookup)){
                options.lookup(q, function (data) {
                    var filteredData = {
                        suggestions: $.grep(data.suggestions, function (suggestion) {
                            return filter(suggestion, q, queryLowerCase);
                        })
                    }
                    that.suggestions = filteredData.suggestions;
                    that.suggest();
                    options.onSearchComplete.call(that.element, q, data.suggestions);
                });
                return;
            }
```
Here is my javascript file that is handling the fetch from PHP
```
$('#searchInput').autocomplete({
    lookup: function (query, done) {
        $.ajax({
           url: 'path to php',
           type: 'get',
           dataType: 'JSON',
           async: true,
           data: 'query=' + query,
           success: function(data) {
             done(data);
           }
        })
        // Do ajax call or lookup locally, when done,
        // call the callback and pass your results:
    },
    onSelect: function (suggestion) {
        alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
    }
});
```

and lastly the php code that returns the values
```
$arr = array("suggestions" => array( array("value"=>"foo","data"=>"bar"), array("value"=>"foo2","data"=>"bar2") ) );

	echo json_encode($arr);
```

**Comment by tkirda** [comment]
Looks like this is duplicate: https://github.com/devbridge/jQuery-Autocomplete/issues/441

**Comment by francisalfanta** [comment]
The current function is like below. Shall I replace the entire getSuggessions with yours? 
     
    getSuggestions: function (q) {
            var response,
                that = this,
                options = that.options,
                serviceUrl = options.serviceUrl,
                params,
                cacheKey,
                ajaxSettings;

            options.params[options.paramName] = q;
            params = options.ignoreParams ? null : options.params;

            if (options.onSearchStart.call(that.element, options.params) === false) {
                return;
            }

            if ($.isFunction(options.lookup)){
                options.lookup(q, function (data) {
                    that.suggestions = data.suggestions;
                    that.suggest();
                    options.onSearchComplete.call(that.element, q, data.suggestions);
                });
                return;
            }

            if (that.isLocal) {
                response = that.getSuggestionsLocal(q);
            } else {
                if ($.isFunction(serviceUrl)) {
                    serviceUrl = serviceUrl.call(that.element, q);
                }
                cacheKey = serviceUrl + '?' + $.param(params || {});
                response = that.cachedResponse[cacheKey];
            }

            if (response && $.isArray(response.suggestions)) {
                that.suggestions = response.suggestions;
                that.suggest();
                options.onSearchComplete.call(that.element, q, response.suggestions);
            } else if (!that.isBadQuery(q)) {
                that.abortAjax();

                ajaxSettings = {
                    url: serviceUrl,
                    data: params,
                    type: options.type,
                    dataType: options.dataType
                };

                $.extend(ajaxSettings, options.ajaxSettings);

                that.currentRequest = $.ajax(ajaxSettings).done(function (data) {
                    var result;
                    that.currentRequest = null;
                    result = options.transformResult(data, q);
                    that.processResponse(result, q, cacheKey);
                    options.onSearchComplete.call(that.element, q, result.suggestions);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    options.onSearchError.call(that.element, q, jqXHR, textStatus, errorThrown);
                });
            } else {
                options.onSearchComplete.call(that.element, q, []);
            }
        },

**Comment by itsmekps** [comment]
after applying @jamesburrow23 code getting multiple alerts when string in input field gets matched with the data even without selecting it
