### ISSUE TITLE
groupBy dont work on ajax/json request

### ISSUE THREAD

**Issue by pablfr** [devbridge/jQuery-Autocomplete#437]
Hello,

This code work, but he dont groupeBy :

```
    $(function(){
    options = {
        source:'/?controller=search',
        groupBy: 'category',
        dataType : 'json',
        transformResult: function(response) {
            return {
                suggestions: $.map(response, function(dataItem) {
                    return { value: dataItem.valueField, link:dataItem.valueField , data: dataItem.dataField };
                })
            };
           }
    };
    a = $('#q').autocomplete(options);
});


// This code work witch groupBy, but its lookup

var teams =  [
              { value: 'Chicago Blackhawks', link :'http://google.com', data: { category: 'NHL' } },
              { value: 'kk qdqsd', link :'http://ggg.com', data: { category: 'NHL' } },
              { value: 'Chicago Bulls', link :'http://ssdfsdf.com',  data: { category: 'NBA' } }]


$('#q').autocomplete({
        lookup: teams,
        groupBy: 'category',
        transformResult: function(response) {
            return {
                suggestions: $.map(response, function(dataItem) {
                    return { value: dataItem.valueField, link:dataItem.valueField , data: dataItem.dataField };
                })
            };
           }
    });
```

Do you have an idea ?

**Comment by SuN-80** [comment]
I bet this is an issue with an array defined in plain text instead of using the array() function. Check how you generate your json server side.

For example, (let's assume you're inserting a record in a foreach loop) setting your value for the data key like this will work: 
`'data'	=> array( 'category' => 'NHL' )`
This won't:
` 'data'	=> "{ category: 'NHL'}"`

**Comment by tkirda** [comment]
It does not matter if it is ajax or local lookup. Same logic is used.

**Comment by SuN-80** [comment]
I know, but in ajax how you create the array seems to matter. I had more or less the same issue, and this is how I fixed it.

**Comment by tkirda** [comment]
Yes, you are right. Thanks for sharing, that might help others who are using PHP on a server side.

**Comment by Aloha276** [comment]
@SuN-80 could you please show me how did you generate your json on the server side, because i'm facing the same problem with groupBy, this is my PHP:
$clubSuggestions = [
            'value' => 'Chicago Blackhawks',
            'data' => array( 'category' => 'NHL' )
        ];
return json_encode(array("suggestions" => $clubSuggestions));
