### ISSUE TITLE
onInvalidateSelection only works after selection

### ISSUE THREAD

**Issue by ruskid** [devbridge/jQuery-Autocomplete#438]
Hi, thanks for the work!
onInvalidateSelection only works if the item was selected by the user.

I got a situation where I preload some values into autocomplete input and hidden input on page load. So in this case if user will change autocomplete input then the hidden will remain the same, because nothing was selected previously.

Imagine update situation where you preload user's values.

**Comment by ruskid** [comment]
```js
onValueChange: function () {
            var that = this,
                options = that.options,
                value = that.el.val(),
                query = that.getQuery(value);

            if (that.selection && that.currentValue !== query) {
                that.selection = null;
                (options.onInvalidateSelection || $.noop).call(that.element);
            }
}
```
that.selection is mandatory. As a quick fix a changed it to "that.selection || that.currentValue !== query"
Let me know if its wrong.

**Comment by tkirda** [comment]
Just set `selection` on autocomplete instance to have an initial value when you load a page, so that it will behave same way as if user has selected it.

**Comment by ruskid** [comment]
Thanks!

**Comment by Mushr0000m** [comment]
@tkirda Can you please explain how to do that (pass the `selection` on the instance) ? I've the same issue. Thanks

**Comment by tkirda** [comment]
@Mushr0000m `selection` is not documented, I considered this internal details. You can set it's value right after you instantiate autocomplete:

```javascript
$('.my-input').autocomplete(options);

// Set selection property on the instance:
$('.my-input').autocomplete().selection = 'Any Value';
```
And selection value acts more like a flag, it does not matter what value it holds (as long as it is truthy). It is used just to indicate whether `onInvalidateSelection` should fire.

**Comment by Mushr0000m** [comment]
Thanks ! That was quick ;-)
