### ISSUE TITLE
How to store more than two items

### ISSUE THREAD

**Issue by mitsumitsumitsu** [devbridge/jQuery-Autocomplete#439]
Hi, I am new to jquery and am currently trying to figure out this plugin. I am retrieving a json file from the server with data for userId, userName, userMail. My question is, is there a way to store more than two items? because currently i can only store the ff:  value: item.userId  , data: item.userName. I am appending this data to an html element. How can I store more than three items from the json file?

**Comment by mitsumitsumitsu** [comment]
Ok I figured it out. Just had to do data: item, then access it like suggestion.data.userMail, suggestion.data.userName..

My next question is, how to I place the suggestions to a specific html element for custom design? Instead of the drop down menu that shows the suggestions by default, is there a way I can place the suggestions into individual <li> or <a> tags? 

I tried appendTo, but it only appends the drop down list to a specific html element. I would like each of the suggestion items to be placed in individual html elements, even before the user selects/ clicks a particular suggestion.

**Comment by mitsumitsumitsu** [comment]
Ok I figured it out. Just had to do data: item, then access it like suggestion.data.userMail, suggestion.data.userName..

I have another question:
How can I append an image to the suggestions container? Like for example in my JSON file I have the url to an image for each item, I know I can get the url String value simply by suggestion.data.pathToImageFile. What I don't know is how to render this url into an image that I can display along with some text in the suggestions container? For example I'd like it to look like this per suggestion:
(Image) UserName UserId
(Image) UserName UserId

How do I insert an image into the DOM of the suggestions container?

**Comment by tkirda** [comment]
You can provide your own `formatResult` function. Read the docs.
