### ISSUE TITLE
[Problem] Showed all data when call JSON file

### ISSUE THREAD

**Issue by chinhphan099** [devbridge/jQuery-Autocomplete#441]
Hi,

My json file (/data/ajson.json) had format same as https://github.com/devbridge/jQuery-Autocomplete#response-format

This is my example:
$('#txt-search').autocomplete({
  serviceUrl: '/data/ajson.json'
  //dataType: 'json',
  //paramName: 'value'
});

When I type any text, all data in my JSON file was showed.
![exam](https://cloud.githubusercontent.com/assets/7882362/11319965/ee0035d4-90bc-11e5-9151-7818b57f0281.png)

**Comment by tkirda** [comment]
Your `serviceUrl` endpoint should return filtered data already. If you want to filter on a client set your suggestion list in a `lookup` property.

**Comment by chinhphan099** [comment]
Thanks for your feedback.
I'd try:
"ajson.json" File:
[
  { "value": "United Arab Emirates", "data": "AE" },
  { "value": "United Kingdom", "data": "UK" },
  { "value": "United States", "data": "US" }
]

JS:
$.ajax({
  type: 'GET',
  url: '/data/ajson.json',
  dataType: 'json',
  success: function(data) {
    $('#txt-search').autocomplete({
      lookup: data,
      //dataType: 'json',
      //paramName: 'value',
      minChars: 3,
      maxHeight: 400,
      autoSelectFirst: true,
      zIndex: 9,
      onSelect: function (suggestion) {
        alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
      },
      appendTo: $('#search_form')
    });
  }
});

It work for me.

**Comment by tkirda** [comment]
That should work.
