### ISSUE TITLE
Cant get it working with custom AJAX

### ISSUE THREAD

**Issue by DonHansDampf** [devbridge/jQuery-Autocomplete#442]
Hey there,

i simply cant get your plugin to work with my api. I tried every constellation and never got any output from the plugin (not with my api-results. It worked fine with a test array). The only way i got it working, was this way:

```javascript
  suggestions = [];

  $('#searchbar').on("change keyup paste", function(){
  var query = $('#searchbar').val();
  var adult = "true";
  $.getJSON("https://api.themoviedb.org/3/search/person?query=" + query +
  "&include_adult=" + adult + "&api_key=" + api_key, function(result) {
    suggestions = [];
    $.each(result.results, function(index, element) {
      //result = suggestions.push({value: result.results[index].name});
      suggestions.push(result.results[index].name);
    })
  })
  $('#searchbar').autocomplete({
    lookup: suggestions
  })
});
```

But of course, it shows only on a keypress up for a split second. But anyway it shows the right autocomplete. When i try the use the same code as lookup function i get random errors and/or no results. Can you tell me why?

**Comment by tkirda** [comment]
You can provide your own `lookup` function, where you do ajax request yourself and then pass results back to provided callback. See custom lookup function under usage in the docs.
