### ISSUE TITLE
Caching behavior for full words and ajax request

### ISSUE THREAD

**Issue by xorock** [devbridge/jQuery-Autocomplete#443]
I do not fully understand how cache is stored. Let say I'm looking for word "javascript". My server will return correct response for phrase "javasc". 
When I type "java" empty suggestions array is returned. Now typing javasc, javascript will not trigger any further xhr request. Deleting word and typing again also does not work. I have to refresh whole page. Disabling cache make it working as expected. Is this correct behavior?

**Comment by tkirda** [comment]
This is not part of caching, look into the docs for `preventBadQueries`, you can set it to `false`.
