### ISSUE TITLE
How to prevent successful result on field blur?

### ISSUE THREAD

**Issue by murid-angeloop** [devbridge/jQuery-Autocomplete#445]
I have a search field where you're only supposed to type a string that will return a successful suggestion, if you type anything else other than that, it should trigger an error.

Issue: if you start typing and you leave (blur) the field mid-sentence while there are still suggestions in the list but nothing has been selected that shouldn't be valid.

**Comment by tkirda** [comment]
This is up to you to track the state if it is valid or not. Set state as valid in `onSelect` callback, then you can hook into `onInvalidateSelection` to invalidate your state.

Looks like this is what you are trying to achieve.

**Comment by murid-angeloop** [comment]
Thanks, this is the current scenario:

- suggestions are: `['aa','bb']`
- I type `'a'`
- in the suggestion list, I see `'aa'`
- I don't select any of the results
- instead I click outside, anywhere else on the page
- the suggestions list is now hidden and the input field still says `'a'`
- at this point, I would like to trigger my own function to make the field invalid

Basically, I'm trying to call my function when the following 2 conditions are met:
- no valid selection has been made
- input field has been deselected (blur)

I tried `onInvalidateSelection` but it only works when altering the content of the input field by adding/removing characters.

**Comment by tkirda** [comment]
This is tricky, you may listen to `blur` event, and if no selection has been made in 300 ms, trigger your own function.
