### ISSUE TITLE
Can user only select value from the suggestions list?

### ISSUE THREAD

**Issue by softshape** [devbridge/jQuery-Autocomplete#446]
Is there any way to limit possible values for input by only those who are provided by suggestions? In other words, user can only select value from the suggestions list. Standard HTML select won't work because it can't update its list by AJAX as user types in the input, like jQuery-Autocomplete does.

**Comment by rtarnec** [comment]
Hi, did you get any answer? Thanks in advance

**Comment by tkirda** [comment]
You can use `onSelect` and `onInvalidateSelection` to track whether selection was made from the suggestions or not.
