### ISSUE TITLE
showNoSuggestionNotice not working in 1.2.24

### ISSUE THREAD

**Issue by esseveld** [devbridge/jQuery-Autocomplete#448]
this.suggestions.length evaluates as undefined in line 631.

**Comment by tkirda** [comment]
When you returning results you must return empty array if there are no suggestions.

**Comment by esseveld** [comment]
Autocomplete works for me and it's awesome, however, I can't get
showNoSuggestion do anything or the related functions to even fire. I
gather I'm missing something?

ac_input.autocomplete({
      showNoSuggestionNotice: true,
      noSuggestionNotice: "nothing found.",
      serviceUrl: '/autocomplete/',
      onSelect: function (suggestion) {
        Lightbox.passData(suggestion.data);
        Lightbox.show();
        ac_input.val("");
      },
      onInvalidateSelection: function () {
        // Do something else
      }
  });

**Comment by tkirda** [comment]
From your first message, if you getting that error, that means `suggestions` is `undefined`. If your setup is correct you should NEVER have this as `undefined`. It must be empty array `[]`.

I suspect your server is responding with incorrect format when there are no suggestions.

**Comment by esseveld** [comment]
Ahh, now I understand your first comment. Thanks, cheers & happy holidays.
