### ISSUE TITLE
Clear selected value notification

### ISSUE THREAD

**Issue by simonfox** [devbridge/jQuery-Autocomplete#456]
I can't currently find a way to get a callback when the selection is cleared. onSelect is only called when an option is selected, but not when you remove selection.

Is there a way to do this already? Currently we workaround the issue by adding a key up directly to the input and if the text becomes empty string set our selected value to null.

Would you accept a pull request for this functionality, and if so what would be the preferred approach. I'm guessing it would be best to add a callback so onSelect behavior isn't changed for existing users?

**Comment by tkirda** [comment]
I think what you are looking for is `onInvalidateSelection`. That should do it for you.

**Comment by simonfox** [comment]
@tkirda thank you......seems I was setting the initial value incorrectly for that to work. Would something like the following be the recommended way for setting initial selection (just after the call to `$(this.input).autocomplete(...`)?

```js
$(this.input).data('autocomplete').selection = this.selectedItem;
```

**Comment by tkirda** [comment]
`onSelect` already sets this value, you shouldn't need to set it yourself.

If you want to set it initially, that should do it. After autocomplete has been initialized. Also set currentValue to the same value as input element value: https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L480

**Comment by simonfox** [comment]
@tkirda yes `onSelect` is working fine. Was just setting initial value I was interested in. My initialization looks something like the following and works

```
this.input.value = this.initialDisplayText;
$(this.input).autocomplete({
    ...,
    onSelect: this.onSelect.bind(this),
    ...
});
$(this.input).data('autocomplete').selection = this.initialSelectedItem;
```
