### ISSUE TITLE
Local lookups on AJAX data

### ISSUE THREAD

**Issue by berarma** [devbridge/jQuery-Autocomplete#459]
We're using this plugin to look up big tables. There can be many lookups running at the same time. Some of them are just a finer version of a previous one.

There's a possible optimization that would result in less hits to the server and faster lookup response. It should be possible to do lookups on the AJAX data, and there should be a maxChars option so that the plugin didn't request new data when the query string is greater than this length and there's already local data that can be looked up locally. This way most of our lookups would consists of just a 4 chars remote lookup followed by local lookups for the longer query strings.

I don't know of a way to do this with the current plugin options, in case it's possible I need some help.

Thanks!

**Comment by tkirda** [comment]
Your best option here would be provide your own `lookup` function. See `custom lookup function` in the docs, so that you have full control over when to hit the server, when to do AJAX lookup or ignore it completely.

**Comment by berarma** [comment]
I had read your answer but forgot to give some feedback. It was useful. Thanks.
