### ISSUE TITLE
Best practice for activity

### ISSUE THREAD

**Issue by digitalprecision** [devbridge/jQuery-Autocomplete#460]
Is there a best practice for indicating activity? Right now when user enters chars, there might be a slight delay depending upon traffic, and there is no indication that the request was issued and just waiting on a response.

I'd like to show the auto-complete css but instead of having suggestions, render a spinner gif or "loading" text. Right now I am thinking that I have to manually trigger the container.show(), populate that html with the activity indicator via onSearchStart callback, then remove the html and replace with suggestions when done.

Thanks.

**Comment by digitalprecision** [comment]
Looks like the following works:

`if (Autocomplete.suggestions.length > 0) {
                
     $('.autocomplete-suggestions').html('Loading...').show();
}`

**Comment by barrychapman** [comment]
this solution doesnt seem to work
