### ISSUE TITLE
dispose() Is not a function

### ISSUE THREAD

**Issue by jonasclement** [devbridge/jQuery-Autocomplete#462]
Hello,

We use this plugin where I work, and have been for many years.

I've recently replaced the old frontend dev and I'm writing code that involves use of this plugin.

We are running version 1.1.3 (don't blame me!) and I have a problem.

I have to perform an AJAX lookup of street names after the user has entered a postal code. I have it working by not having autocomplete initialize until the user has entered a valid postal code. Problem is if they go back and change the postal code, two drop downs will be created.

The way around this - I thought - would be to call dispose() on the autocomplete, like so:

```
        if( ac ) {
            ac.dispose();
        }

        ac = $( '#streetName' ).autocomplete({
            width: "100%",
            dataType: "json",
            serviceUrl: "...",
            minChars: 1
        });
```

(With ac being initialized in the global scope of course)
I'm also noticing that dataType doesn't actually seem to have any effect.

If I call .dispose() directly on `$( '#streetName' ).autocomplete()` an error will appear in the console saying `Uncaught TypeError: Cannot read property 'serviceUrl' of undefined`. The function is being called from a jquery .keyup handler.

Is this just because I'm running a horribly outdated version, or can I do something about it?
- Jonas

**Comment by tkirda** [comment]
Hard to answer now, you would be better of upgrading to new version. It should not be hard.

**Comment by jonasclement** [comment]
Whelp, I thought GitHub would somehow notice me of a response, sorry I didn't get back to you. I'm fairly new here.

Anyways, for anyone finding this from Google, I ended up overriding the a few functions to make them do as I needed - big part of the problem came from needing to look up from multiple parameters if they were filled out by the user.

Thanks for your response @tkirda :)
