### ISSUE TITLE
Multiselect from suggestions

### ISSUE THREAD

**Issue by petrosmit** [devbridge/jQuery-Autocomplete#463]
Hello, 
First of all congrats, great work.
I want the user to be able to pick more than one option for each textbox. i.e. If the suggested values of the autocomplete are a,b,c,d the user should be able to pick options a and b in the same textbox. Is that possible? Thank you in advance

**Comment by tkirda** [comment]
No, that is not possible.

**Comment by ankitkumarsuthar** [comment]
is that Multi-Select option is available now?

**Comment by tkirda** [comment]
No, it is not.
