### ISSUE TITLE
Question: Different values for list and field

### ISSUE THREAD

**Issue by markstickley** [devbridge/jQuery-Autocomplete#465]
Hi, is it possible to define the value that appears in the dropdown list and the value that gets inserted into the text field separately? Ideally I would like them to be different.

Thanks!

**Comment by tkirda** [comment]
Use `formatResult` callback and use any value you want to display in a dropdown. Then value property will be inserted into input when you select it.

**Comment by markstickley** [comment]
Awesome, thank you.
