### ISSUE TITLE
After input is selected it would be nice to see the options again

### ISSUE THREAD

**Issue by Webinsane** [devbridge/jQuery-Autocomplete#466]
We have enabled on click to see all the countries (results), but once you select any you are stuck and have to clean the result in order to list them all again.

For example in your demo if you select country for example Spain. If you decide to see all the countries again you have to delete the Spain text.

**Comment by tkirda** [comment]
Yes, that is not a dropdown, it is just suggesting based on what you typed. Maybe there are other implementations that combine suggestion and dropdown functionality.
