### ISSUE TITLE
onFocus - seems broken.

### ISSUE THREAD

**Issue by marcelsvensson** [devbridge/jQuery-Autocomplete#467]
I've been trying to utilize the onFocus-function, example:

Typing in a word and getting suggestions, then clicking elsewhere on the page avoiding trigger the onSelect-function. Focusing on the input with autocomplete again sure does trigger the onFocus but it does not trigger onValueChange hence not displaying the suggestions again. It looks like this:

`onFocus: function () {
            var that = this;
            that.fixPosition();
            if (that.options.minChars === 0 && that.el.val().length === 0) {
                that.onValueChange();
            }
}`

having options of minChars to 0 makes no sense to me and if the length of my input is 0 then there is no suggestions to be displayed anyway. I'll suggest changing it into:

`onFocus: function () {
            var that = this;
            that.fixPosition();
            if (that.el.val().length >= that.options.minChars) {
                that.onValueChange();
            }
}`

so that the suggestions will indeed display again if the length of the input is greater or equal to the minimum chars in options.

**Comment by tkirda** [comment]
That is current implementation already:

```javascript
        onFocus: function () {
            var that = this;

            that.fixPosition();

            if (that.el.val().length >= that.options.minChars) {
                that.onValueChange();
            }
        },
```
