### ISSUE TITLE
There's a way to show only the substring area that match with search?

### ISSUE THREAD

**Issue by gheleri** [devbridge/jQuery-Autocomplete#468]
Hi, I am feeding the autocomplete with strings and when I search for a word which is in the end of the string It doesn't show the match characters.

How I could show only the area that matched?

For example in the image link below, when I am looking for "cell death", the last suggestion 
contains the search in the end (positive regulation of programmed cell death) but I can't see where it matched for longer strings.

http://imgur.com/H1VXwu4

**Comment by philwig** [comment]
Make your drop down wider, or write a formatter which behaves very strangely?

**Comment by tkirda** [comment]
Agree with @philwig
