### ISSUE TITLE
Append hard coded option below list of options

### ISSUE THREAD

**Issue by stefanlesik** [devbridge/jQuery-Autocomplete#469]
This plugin is great. But I want to hard code an option at the end of the list of options that calls a function onclick. Like this:

`$('.autocomplete-suggestions').append('<a href="javascript:manualEntry();">Enter manually</a>'); `

This appends the a href, but the link, in this case a function call is ignored and the 'onselect' behaviour is called instead. How can I call this 'manualEntry' function instead?

Any help would be awesome - thanks!

**Comment by tkirda** [comment]
Look into `beforeRender` method, you can manipulate DOM before suggestions are displayed.

**Comment by stefanlesik** [comment]
Great! so how would that look with my example?

**Comment by tkirda** [comment]
```JavaScript
$('input').autocomplete({
    // Other settings...
    beforeRender: function (container) {
        container.append('<a href="javascript:manualEntry();">Enter manually</a>');
    }
});
```
