### ISSUE TITLE
jQuery UI conflict != than known issue

### ISSUE THREAD

**Issue by thecenz1** [devbridge/jQuery-Autocomplete#471]
Hi,

I use jquery ui 1.11.4 together with your plugin. 
As from the doc, I instanciate using the full name : 

```
`$('#testautocomplete').devbridgeAutocomplete({
                lookup: cases_directory,
                onSelect: function (suggestion) {
                    selectCustomer(suggestion.index);
                    global_case_id = suggestion.index;
                    global_folder_name = suggestion.folder;
                }`
```

But I would like to use the jQuery UI autocomplete on some other inputs and of course it doesn't work.
Is there a way to have both plugin work at the same time ?

**Comment by tkirda** [comment]
You can change order of scripts. If you will load in that order:

1. jQuery
2. jQuery-Autocomplete
3. jQuery UI

You should be able to use jQuery UI autocomplete.
