### ISSUE TITLE
Plugin doesn't work correctly when combined with turbolinks

### ISSUE THREAD

**Issue by StanBright** [devbridge/jQuery-Autocomplete#473]
First, thanks for the good work! In general, this plugin works flawlessly and is pretty easy to set up. 

I'm integrating this in one Ruby on Rails project, and using turbolinks is more or less a common practice. The issue I'm facing is that the plugin works on a newly opened page; however, as soon as I start browsing (with turbolinks active), the autocomplete's highlighting stops working. It works, I can select the results, and their values are shown in the relevant input box, but **there is no highlighting**. Note, highlighting works if I go over the results with the mouse.

I'm using jQuery-Autocomplete 1.2.24, jquery 2.2.2, turbolinks 2.5.3, and jquery-turbolinks 2.1.0

Any idea what could be causing this and how I could debug it?

Thanks!

**Comment by tkirda** [comment]
Looks like issue that you have is related to styling. Inspect styles that are applied, it just wraps highlighted text using <strong> tag.

**Comment by StanBright** [comment]
By "highlighting" I mean "showing" the styles that are applied to ".autocomplete-selected". Again, the styles are present. If I perform a mouse-over the ".autocomplete-selected" class is applied and the visual effects are present. If I move around the results with UP/DOWN, the ".autocomplete-selected" class is applied but there is no visual effects on the items. 

How do I know that the "selected" class is applied when using the arrow keys? - I added a simple console log of the active element 

```
if (that.selectedIndex !== -1 && children.length > that.selectedIndex) {
                activeItem = children.get(that.selectedIndex);
                console.log(activeItem);
                $(activeItem).addClass(selected);
                return activeItem;
}
```

**Comment by tkirda** [comment]
You should see class changes when inspecting DOM using chrome dev tools.

**Comment by StanBright** [comment]
That is the missing part. The class changes are being applied to "some" elements, as seen through the console.log output, but that isn't represented to the DOM. 

In general, similar issues are tightly related to the way turbolinks work, and I hoped that **jquery.turbolinks** will resolve this issue. Unfortunately it didn't.

**Comment by StanBright** [comment]
@tkirda thanks for trying to help!

I upgraded to turbolinks 5 (beta2), and everything works as expected. At least seemingly. 

I'm closing this. Although, I presume others may face this issue if they use "Turbolinks - Classic".
