### ISSUE TITLE
How to post query with json format

### ISSUE THREAD

**Issue by bjzhanghao** [devbridge/jQuery-Autocomplete#474]
The server side api requires json format request and I can't modify it, how to post a query with json format?

**Comment by tkirda** [comment]
Use `lookup` callback and issue ajax query yourself. This way you can choose any transport method.

**Comment by skftn** [comment]
@tkirda Do I understand correctly that this would need a synchronous ajax request? Could you provide an example?

**Comment by philwig** [comment]
Just set the options to do it:
```
            type: "POST",
            dataType: "json"
```

Even if you have $.ajax defaults set, you need to do this.
