### ISSUE TITLE
Custom class per auto-suggestion

### ISSUE THREAD

**Issue by tychovbh** [devbridge/jQuery-Autocomplete#477]
In my project I really need to be able to give every auto-suggestion a custom class. I solved this for now by changing the autocomplete.js on line 675 to:
````js
var customClass = '';
if (suggestion.customClass) {
     customClass = suggestion.customClass;
}
html += '<div class="' + className + ' ' + customClass + '" data-index="' + i + '">' + formatResult(suggestion, value) + '</div>';
````
After that i was able to use the transformResult like this:

````js
return {
    suggestions: $.map(response.suggestions, function (suggestion) {
        return {
            value: suggestion.value,
            link: suggestion.link,
            customClass: suggestion.customClass
        };
    })
};
````

Is it possible to implement something like this?

**Comment by tkirda** [comment]
You can pass `formatResult` and wrap suggestion into anything you want and just adjust styling of it.
