### ISSUE TITLE
How to setup default options for all instances?

### ISSUE THREAD

**Issue by DrDeath72** [devbridge/jQuery-Autocomplete#478]
like this one http://craftpip.github.io/jquery-confirm/#globaldefaults

**Comment by tkirda** [comment]
Defaults are not exposed now. The only way to use same values is to pass same configuration to each instance.

**Comment by Gouigouix** [comment]
@tkirda, @DrDeath72 

If it can help, I updated the "[jquery.autocomplete.d.ts](https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.d.ts)" file you want me to do a PR in your repository? The ideal would be to add on https://github.com/DefinitelyTyped/DefinitelyTyped with test file "jquery.autocomplete-test.ts"

Thx.

**Comment by tkirda** [comment]
@Gouigouix I think it would not hurt to have it in both places.

**Comment by Gouigouix** [comment]
@tkirda 

Ok, I do a pull request to validate the definition file.

**Comment by philwig** [comment]
Work around:

1. create an options object
2. $.extend that object every time you run an autocomplete. Works fine.

**Comment by DrDeath72** [comment]
sux
