### ISSUE TITLE
Cant pass another form element value through params option

### ISSUE THREAD

**Issue by slicinga** [devbridge/jQuery-Autocomplete#480]
Why can't I pass the value of another input element in the form using params parameter ?
$('.city-zip-auto-complete').autocomplete({
		serviceUrl: base_url + '/admin/address/get-cities',
		type : "POST",
		dataType: "json",
		minChars: 2,
		params: {province_id: $('#province_id').val()}
});

Though if I put a static value in province_id: 20, then it works. Is it possible to append/prepend province_id in the query with onStartSearch ? I tried but didn't work.

**Comment by iamraju** [comment]
I also want to know if it is doable as I want to pass another value from the form.

Thanks.

**Comment by tkirda** [comment]
`onSearchStart` receives params object as a reference, so technically it should work if you will modify it:

```javascript
onSearchStart: function (params) {
  params.province_id = $('#province_id').val();
}
```

Other option would be doing `lookup` via custom function, so you can form you request anyway you want.

**Comment by iamraju** [comment]
Thanks tkirda !
