### ISSUE TITLE
Uncaught TypeError: $(...).autocomplete is not a function

### ISSUE THREAD

**Issue by srijitcoder** [devbridge/jQuery-Autocomplete#481]
![23](https://cloud.githubusercontent.com/assets/10809211/15422353/cffe2d04-1e95-11e6-8e07-2b1fbeb10604.PNG)
![24](https://cloud.githubusercontent.com/assets/10809211/15422354/d0066d66-1e95-11e6-8f28-6332ff01a443.PNG)
How to solve this error

**Comment by tkirda** [comment]
Looks like you did not include plugin on the page before trying to initialize it.

**Comment by simmtechnology** [comment]
SOLVED
======
In my case  I noticed the order in which header scripts and css are imported or linked matters.
autocomplete.js must be the first , then others can follow

**Comment by kikatuso** [comment]
Sorry, for such a dumb question, but...how do you include the plugin on your page? what do you have to install and what to include in your page?

**Comment by tkirda** [comment]
You need to include script (after jquery) which is located under:

https://github.com/devbridge/jQuery-Autocomplete/tree/master/dist

To get script, you can download directly from github or use npm install and then include from node_modules.
