### ISSUE TITLE
Setting paramName to "q" causes jquery to return error.

### ISSUE THREAD

**Issue by llanginger** [devbridge/jQuery-Autocomplete#482]
This is making the difference between me being able to use your amazing plugin and not. It seems like I can set the paramName parameter to just about anything other that "q" which is what the service I'm using requires. The full error thrown is: "Uncaught TypeError: Cannot read property 'length' of undefined... jquery.autocomplete.min.js:8". My js chops aren't really at a point where I feel comfortable modifying that source code. I've tried just about everything I can think of the "trick" the code but it seems pretty adamant that "q" will not pass. Any thoughts at all would be highly appreciated!

**Comment by tkirda** [comment]
Should be able to set it to anything. From error description seems that returned results may not have correct format.

If you can use uncompressed version then it would clear what error means. Now it does not mean much.

**Comment by llanginger** [comment]
Ah, ok, I see!

The error with the uncompressed version is: "jquery.autocomplete.js:771 Uncaught TypeError: Cannot read property 'length' of undefined". 

This lines up with what you suggested about any results not returning correctly-formatted. I can PROBABLY figure this out from here but if you have any specific suggestions I'd be glad of them!

**Comment by tkirda** [comment]
If you consistently return results in a correct format you should not be getting this error. 

Good luck figuring it out.
