### ISSUE TITLE
Input value set by jQuery not trigger the autocomplete

### ISSUE THREAD

**Issue by Wayne-Shen** [devbridge/jQuery-Autocomplete#487]
Hello,

How to make the autocomplete work if I use jQuery to set the input field value.

Thank you very much for your help!!

**Comment by tkirda** [comment]
After you set value via jQuery call `onValueChange` on autocomplete instance to trigger suggestions.

```JavaScript
$('.my-input')
  .val('new value')
  .autocomplete('onValueChange');
```

**Comment by Wayne-Shen** [comment]
Thank you very much, it works perfect!
