### ISSUE TITLE
Set a class or ID on the suggestions container

### ISSUE THREAD

**Issue by zenichanin** [devbridge/jQuery-Autocomplete#490]
Is it possible to set a `class` or `ID` on the suggestions container?  The reason I need to do this is because I will have 2 different autocomplete fields on the page and they each need to have different styling. I know I can set it on each individual row via the `formatResult` method, but it would be better to do it on the container since I would have more control over it. i.e. I could set `border` or `box-shadow` on the auto complete container.

**Comment by tkirda** [comment]
Yes, you can pass `containerClass` option wheni initializing autocomplete:

https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L78
