### ISSUE TITLE
Undefined error: result.suggestions

### ISSUE THREAD

**Issue by Trialen** [devbridge/jQuery-Autocomplete#492]
Could not get this to work using an ajax request. 

Error message:

Uncaught TypeError: Cannot read property 'length' of undefined                jquery.autocomplete.js:779

Traced this to:

result.suggestions = that.verifySuggestionsFormat(result.suggestions);

Replaced with:

result.suggestions = that.verifySuggestionsFormat(result);

Now working.

**Comment by tkirda** [comment]
This just means that your response format is not what it expects. It should be an object with `suggestions` property.
