### ISSUE TITLE
Indicate on initializing element whether suggestions box is open or not

### ISSUE THREAD

**Issue by zenichanin** [devbridge/jQuery-Autocomplete#493]
Is there a native way to attach a class or attribute to the initializing element (input field) to indicate when the suggestions box is open or not?  This is mainly for CSS purposes so that the input field can be styled one way when suggestions box is closed, and another way when it is open.

If there is no built in solution, do you have a tip or suggestion how to add it in, like if I can attach it to some method that fires up when suggestion box and no suggestion box opens and closes?

I'm loving this plugin BTW, best autocomplete jQuery plugin I have found. 👍

**Comment by tkirda** [comment]
There is `onHide` callback. Although there is no on show. You may hook into `onSearchComplete` and add class if it has any results.

Or extend the code with `onShow` callback.
