### ISSUE TITLE
Publish TypeScript definition

### ISSUE THREAD

**Issue by stonio** [devbridge/jQuery-Autocomplete#497]
Publish TypeScript definition to make it discoverable via tsd, typings, NuGet...

**Comment by tkirda** [comment]
Where do you expect it to be published?

Typing can be found here:
https://github.com/devbridge/jQuery-Autocomplete/tree/master/typings/jquery-autocomplete

**Comment by stonio** [comment]
I mean visible easily with commands like `typings search autocomplete` or `tsd query '*autocomplete*'` .

**Comment by tkirda** [comment]
Not sure I understand what you mean, have not worked with TS for a while.

**Comment by stonio** [comment]
@Gouigouix mentioned in #478 that he wants to publish definitions on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by Gouigouix** [comment]
@stonio I found an error in the definition and I have not made pull request. I'll do it quickly. Thank you.

**Comment by Gouigouix** [comment]
I added in pull request #501

**Comment by stonio** [comment]
@Gouigouix Do you consider also to publish as [NuGet package](https://docs.nuget.org/create/creating-and-publishing-a-package)? See  #235.
