### ISSUE TITLE
Why autocomplete is running on focus?

### ISSUE THREAD

**Issue by lfbittencourt** [devbridge/jQuery-Autocomplete#498]
Why autocomplete is running on focus since 1.2.25? IMHO, it makes no sense hit the server again if input value did not changed.

I know it's more a question than an issue, but it completely broke my app today :-/

**Comment by tkirda** [comment]
I don't think anything has changed recently with on focus. Did you just upgrade recently? If you have caching enabled it should not hit server, just get suggestions from cache.

**Comment by simonfox** [comment]
This is the commit fef68b6e4c352b0ee6afdbcc423e005751bed08a in question. It is from Nov 2015 but 1.2.25 is the first release that includes it.

I don't think it makes sense either to call `onValueChanged` on focus? Why would you want to do anything when the control has a selected item and the only change is the focus state?

**Comment by tkirda** [comment]
I guess you can have arguments that you may want to trigger lookup again on focus and for some it is not needed. I guess we may introduce a flag signaling how to behave when field receives focus.

**Comment by simonfox** [comment]
@tkirda would you like a PR for that? any preference on the config setting?

**Comment by shimikano** [comment]
I'm sorry about this unsubstantial comment, but just would like to add that I would appreciate a possibility to turn off triggering on focus too...

**Comment by Asenar** [comment]
to turn it off you can set minChars to 1, or do some additional checks in `onSearchStart`

**Comment by tkirda** [comment]
I really don't want to add more options. After you create an instance just clear focus listener:

```javascript
$('#myinput').off('focus.autocomplete');
```

**Comment by achuinard** [comment]
Set `triggerSelectOnValidInput` to false on the autocomplete options?
