### ISSUE TITLE
Prevent invalid characters

### ISSUE THREAD

**Issue by aristotelis79** [devbridge/jQuery-Autocomplete#499]
How can prevent an ajax call to the serviceUrl who contains only invalid characters.

i.e. searchTerm = @#.$ is invalid.
i.e. searchTerm = @.Abc is valid.

Also I don't want to put all the searches with @.... e.g in badQueries 

Thanks.

**Comment by tkirda** [comment]
Implement your own `lookukp` callback and disable caching. You can implement your own caching logic in custom lookup implementation..
