### ISSUE TITLE
Populate and show list on click

### ISSUE THREAD

**Issue by eldyvoon** [devbridge/jQuery-Autocomplete#504]
Is there any option that allow popup the list whenever user focus on the field? The current behaviour is when the user type and the list start to show.

**Comment by tkirda** [comment]
onFocus it should trigger suggestion display if it equals or greater than minChars option value.

**Comment by zeeshanhive** [comment]
@tkirda how do i show all the suggestions on focus of input

**Comment by tkirda** [comment]
If minChars is set to zero and input is empty, then it will display whatever you return in your code.

**Comment by zeeshanhive** [comment]
@tkirda  minChars work only when i press a space then all my suggestion show. how can i fix that

**Comment by roysG** [comment]
any updates about that?

**Comment by mbm-code** [comment]
any update ?
