### ISSUE TITLE
Uncaught TypeError: $(...).devbridgeAutocomplete is not a function

### ISSUE THREAD

**Issue by slins1** [devbridge/jQuery-Autocomplete#508]
Trying to add autocomplete to my company's web app for a quick search function. We use jQueryUI, so I'm using the devbridgeAutocomplete alias, written as such:

$("#quickSearch").devbridgeAutocomplete(...);

However, the autocomplete does not instantiate, and the Chrome Dev Console displays the above error.

I've included the minified js file correctly, so I don't know what I'm doing wrong. My coworkers are stumped as well. Any thoughts?

**Comment by tkirda** [comment]
That just confirms that you don't have it loaded. You sure you don't have multiple versions of jQuery? 
Also check if you are using latest version of a plugin.

**Comment by slins1** [comment]
Nope, just 1.7.2 of jQuery. And the file is showing up in the network tab in chrome.

![image](https://cloud.githubusercontent.com/assets/12113984/16598750/5a7d9a54-42cd-11e6-861c-ead40b00c741.png)

**Comment by tkirda** [comment]
Check in a console if there is an autocomplete loaded on your jQuery instance, by typing jQuery.fn.devbridgeAutocomplete in the console.

It should be available, try it here: http://devbridge.github.io/jQuery-Autocomplete/

**Comment by slins1** [comment]
Well, you're right. It returns the function on the page you linked to, but it returns undefined on my page.

I will say that our company has modified and customised the jQueryUI files for its own purposes. Do you think that's what's messing it up?

**Comment by tkirda** [comment]
Do you have a link to your page?

**Comment by slins1** [comment]
Unfortunately it's a private web app, I'm not sure I'd be allowed to send you the link

**Comment by tkirda** [comment]
Well then you just have to figure it out.

**Comment by slins1** [comment]
Yeah, I figured as much. Sorry I can't provide more info, thanks for your help
