### ISSUE TITLE
Is it possible to customize the suggestion container?

### ISSUE THREAD

**Issue by bhellman1** [devbridge/jQuery-Autocomplete#514]
I'd like to customize the suggestion container but haven't been able to do that in beforeRender. The end goal is something like:
From:
<div class="autocomplete-suggestion" data-index="1">XXX</div>
To:
```
<div class="autocomplete-suggestion" data-index="1">
  <div class="photo" ></div>
  <div class="meta" ></div>
</div>
```

Is this possible with the available APIs? thanks

**Comment by tkirda** [comment]
I don't think it is possible with current API.

**Comment by tomasbarao** [comment]
So we can't customize the HTML in the suggestions container, to include images and media objects, for example?

**Comment by tkirda** [comment]
For that you can use `formatResult` and customize a row any way you want. Maybe I misunderstood the question.

**Comment by bhellman1** [comment]
@tkirda perfect. thank you
