### ISSUE TITLE
AJAX single result clicking in field causes onSelect to fire?

### ISSUE THREAD

**Issue by carlhussey** [devbridge/jQuery-Autocomplete#518]
I have a search page with a text field on it and autoComplete on that field. Once you click an item, it redirects to a searchResults page and shows the content. This page also has a search input on it that I fill with the query they used.

When clicking back in this field, if there are multiple results, it will pull all the suggestions again for this query, which is fine. However, if there is only a single result in that dataset, focus on the input field seem to cause a onSelect event on that result, in my case, redirecting them back to the same page they are on with a single search result (loop).

Curious if this is a bug where a single result would cause an onSelect even to fire when trying to reload the suggestions?

**Comment by tkirda** [comment]
Set option `triggerSelectOnValidInput` to `false`.

**Comment by andrewmtoy** [comment]
Thanks! This was helpful.

**Comment by atefBB** [comment]
Same issue here and setting `triggerSelectOnValidInput` to `false` doesn't do anything!
Any Ideas?
