### ISSUE TITLE
Uncaught TypeError: $(...).autocomplete is not a function

### ISSUE THREAD

**Issue by saf-itpro** [devbridge/jQuery-Autocomplete#522]
I'm getting the above error on following html file in ASP.NET Core project. I'm using [autocomplete wideget](http://jqueryui.com/autocomplete/):

[Test15.txt](https://github.com/devbridge/jQuery-Autocomplete/files/391286/Test15.txt)

**Comment by tkirda** [comment]
You are using jQuery UI and not jQuery-Autocomplete plugin.

**Comment by fireworkskardtech** [comment]
?What is solution>
