### ISSUE TITLE
Highlight multi suggestion format result 

### ISSUE THREAD

**Issue by razord-ice** [devbridge/jQuery-Autocomplete#523]
hello, this is very useful for ajax autocomplete, i thanks to developer. 
Ok, i have problem in multi result.. because my search input is search a name and sku
how to highlight result. if i search name, the result highlight name. And also i search the sku, the result highlight sku. Because in this case just highlight name. if i search sku, the sku not highlight

```
formatResult: function (suggestion, currentValue)
                  {
                    return '<div class="fastadd-row" data-index="'+suggestion.data.id+'"><div class="fastadd-title"><p>' +$.Autocomplete.formatResult(suggestion, currentValue)+ '</p><span>'+$.Autocomplete.formatResult(suggestion.suggestions.data.sku,currentValue)+'</span></div></div>';
                  },
```

`$.Autocomplete.formatResult(suggestion, currentValue)`
for name

`$.Autocomplete.formatResult(suggestion.suggestions.data.sku,currentValue)`
for sku, the result is undefined

This my JSON

```
"suggestions":[{"value":"Sword Toys","data":{"sku":"LBBCP","id":"11015"}}
```

thank you very much...

**Comment by tkirda** [comment]
You need to implement custom `formatResult` with custom highlighting.
