### ISSUE TITLE
dynamic serviceUrl

### ISSUE THREAD

**Issue by uromay** [devbridge/jQuery-Autocomplete#524]
is it possible to concatenate in the serviceUrl, a url with the value of the input field?
I have an API URL that is something like '/api/user/{value}'
I would like to set it this way:
serviceUrl: '/api/user/' + queryValue

**Comment by uromay** [comment]
I found the sollution
    serviceUrl: function () {
        return ('/api/user/' + $(this).val());
    }

**Comment by DannyBen** [comment]
@uromay - thanks for this, it helped. I also have a similar case, where I want to get the API endpoint by the value of the `rel` attribute of the text field.

This is my coffeescript

```coffee
$ ->
  $('.autocomplete').autocomplete
    serviceUrl: ->
      return 'http://my.api.com/' + $(this).attr('rel')
    minChars: 2
    triggerSelectOnValidInput: false
    autoSelectFirst: true
```

I think this use case should maybe be added as an example in the README?
