### ISSUE TITLE
How to store Devbridge Autocomplete instance into a javascript variable, for reuse

### ISSUE THREAD

**Issue by aklougbo** [devbridge/jQuery-Autocomplete#527]
In the below code , using Autocomplete version 1.2.6, I am getting error 
"Uncaught TypeError: a1.disable() is not a function" on my page.
I have declared the variable **a1**, globally at the beginning of the script.
But it looks like the line a1.disable(),  a1 does not get set.

This has worked for me very well in version 1.1.3 and I really want to use the latest version for this project.  Please can someone tell me, what I am doing  wrong ?

I ve seen some other people use the same variable use , as in issue #462

Thank you all per advance.
I badly need to have this working.

```
<script type="text/javascript">
   var a1;

    $(function() {

                 a1 = $('#tablename').autocomplete({
                            serviceUrl:'/lookup',
                            minChars:3,
                       });

                      a1.disable();   //   <==== I am getting error here
             });                 
  </script>
```

**Comment by ccloli** [comment]
Also happens here with 1.2.26 when using `dispose()` method. It seems that now `autocomplete(optionObj)` returns the original jQuery DOM, so you should try `$(selector).autocomplete().disable()`, or `$(selector).autocomplete('disable')`. As it returns the original jqDOM, you can also use `a1.autocomplete().disable()` or `a1.autocomplete('disable')` in your code.
