### ISSUE TITLE
Ajax return all suggestions

### ISSUE THREAD

**Issue by g0nzo** [devbridge/jQuery-Autocomplete#531]
```
var options = {
                serviceUrl: '/GetTips',
                minChars: 1,
                autoSelectFirst: true,
};
$('#keyword').autocomplete(options);

```

Why this always return all suggestions even if i type something which does not occur?
Everything works great when im using lookup, not serviceUrl

**Comment by tkirda** [comment]
when using `serviceUrl` it should return only values that need to be displayed. It should be used when you have large data sets.
