### ISSUE TITLE
Close autocomplete on resize

### ISSUE THREAD

**Issue by patrickbjohnson** [devbridge/jQuery-Autocomplete#532]
Is there a method available to close the autocomplete on resize. 

Noticed in the source code the only thing autocomplete does on `(window).on('resize')` is reapply the appropriate width. 

I'm trying to include autocomplete in a nav bar that slides in/out of view. When its out of view I want the autocomplete markup visually hidden. This works just fine. However, when we resize the autocomplete markup does not go away.

**Comment by tkirda** [comment]
There is no such method. However, you may render it into your custom container and you may show / hide as you wish. See `appendTo`.

**Comment by patrickbjohnson** [comment]
Are there any events fired when the autocomplete div is open/closed (has a height)? 

Even using `appendTo` it is still almost impossible to show/hide this based on a resize considering the plugin [hi-jacks positioning on any re-size](https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L205).

Ultimately, I'd just like to know when its open/close so I can control the appearance of its container.
