### ISSUE TITLE
Request with slashes "/" 

### ISSUE THREAD

**Issue by ilempi** [devbridge/jQuery-Autocomplete#533]
I have names with slashes in it and autocomplete doesn't work. Could you help me?

**Comment by tkirda** [comment]
It should work fine if you properly escape them.

**Comment by ilempi** [comment]
I should replace or delete them? Is it impossible to see slashes in result?

**Comment by tkirda** [comment]
I just tried including slash and it works fine.

**Comment by dugwood** [comment]
@ilempi use proper functions to encode your responses. For example if you're requesting a PHP backend, use `json_encode()` and you'll be fine. Else post an example of your response. A correctly formatted string in JSON with slash would be: `"my string\/my string"`
