### ISSUE TITLE
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by prafulbagai** [devbridge/jQuery-Autocomplete#538]
I'm getting a `Syntax JSON PARSE` error . Following is the case.

I've a file b.js wherein I've initialized the autocomlete as follow:-

```
$(function() {
    'use strict';
    $('#ad_location').autocomplete({
        lookupLimit: 3,
        lookup: ArrayData,
        // autoSelectFirst: true,
    });
});
```

Now, I'm getting the  `ArrayData` from an API endpoint in a.js file as follow:-

```
var ArrayData;
$.getJSON('/api/location/', function(json){
	ArrayData = $.map(json, function(value, key) {
	    return {
	        value: value,
	        data: key
	    }
    })
});

```

On my HTML page, the order of importing the files is as follow:-

```
<script type="text/javascript" src="a.js"></script>
<script type="text/javascript" src="jquery.autocomplete.js"></script>
<script type="text/javascript" src="b.js"></script>

```

While I start typing-in, a GET request is send back to the server with the same url as current one, but appended query-parameter  `query=INPUT CHARACTERS`. As expected, the server responds back witht the HTML content and hence it is unable to JSON parse the data.

So, my question is why a GET request is being sent to the server, when `lookup` variable is provided?

**Comment by prafulbagai** [comment]
Is it a possibility that getting the data from the API `(a.js)` is taking a lot of time and by that time the autocomplete has been initialized?

**Comment by tkirda** [comment]
Yes, you need to initialize autocomplete after you loaded data.

**Comment by prafulbagai** [comment]
Any idea how can I make sure that the data is loaded before initialisation? Because the order is correct in this case.

**Comment by tkirda** [comment]
Need to rearrange how you are loading the code;

```
$.getJSON('/api/location/', function(json){
    var ArrayData = $.map(json, function(value, key) {
        return {
            value: value,
            data: key
        }
    });

  // Initialize autocomplete here with lookup data
});
```
