### ISSUE TITLE
triggerSelectOnValidInput: false - Results Flickering

### ISSUE THREAD

**Issue by tylercubell** [devbridge/jQuery-Autocomplete#540]
https://jsfiddle.net/21ws9a9x/
1. Type 'a' into text box.
2. Select 'Andorra'.
3. Click inside text box. Results appear for only a moment then flicker off.
4. Click on document body.
5. Click inside text box. No flicker.

Alternatively:
1. Type 'a' into text box.
2. Select 'Andorra'.
3. Click on document body.
4. Click inside text box. No flicker.

**Comment by tkirda** [comment]
Looks like this has been resolved with #552
