### ISSUE TITLE
Retaining autocomplete results after no matches occurs

### ISSUE THREAD

**Issue by midget2000x** [devbridge/jQuery-Autocomplete#553]
I really like this plugin.  I realize this might be somewhat unreasonable, but I thought I'd ask...

Is there a way to keep the autocomplete results appearing even after no matches begins to occur?  example:

quick (5 hits)
quick brown (3 hits)
quick brown fox (0 hits) <--retain the 3 previous hits in window

Also, how can I access the "raw" search specification that the plugin processes?

**Comment by tkirda** [comment]
You can implement your own `lookup` function and cache results. Plugin just display whatever lookup service returns. In your own `lookup` you can manipulate logic to be whatever you wish.
