### ISSUE TITLE
Use anchor links in dropdown

### ISSUE THREAD

**Issue by jivanshr** [devbridge/jQuery-Autocomplete#554]
I need to show names of staff with links to respective detail page. 
Is it possible with this plugin? If yes tell me know more.

<img width="301" alt="screen shot 2016-11-10 at 3 06 25 pm" src="https://cloud.githubusercontent.com/assets/4607569/20172960/562c94a4-a75f-11e6-94a6-b985ee51b0db.png">

**Comment by tkirda** [comment]
You need to provide custom filtering `lookupFilter` and custom rendering `formatResult` functions. See the docs.
