### ISSUE TITLE
Selecting a suggestion that is a substring of another suggestion doesn't trigger onSelect

### ISSUE THREAD

**Issue by badjer** [devbridge/jQuery-Autocomplete#555]
For example, if I've got the following in my set of suggestions: ``Fit`` ``Fit_EV``

Then clicking on ``Fit`` in the list won't trigger the call to the ``onSelect`` callback. Clicking on ``Fit_EV`` however does. Changing this line https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L511 from

```
return (suggestions.length === 1 && suggestions[0].value.toLowerCase() === query.toLowerCase());
```
to 
```
return (suggestions.length > 0 && suggestions[0].value.toLowerCase() === query.toLowerCase());
```

fixes my use-case, but I don't know that it's safe to assume that the substring match is always first on the list.

**Comment by tkirda** [comment]
You are right. This is used only when `triggerSelectOnValidInput` is set to `true`. This was on purpose so that it does not automatically select item if there are more than one suggestion.
