### ISSUE TITLE
Not Working With Array of Objects

### ISSUE THREAD

**Issue by Amir313** [devbridge/jQuery-Autocomplete#556]
i am using this plugin to autocomplete its working when i am using array like this 
var currencies = [
    { value: 'Afghan afghani', data: 'AFN' },
    { value: 'Albanian lek', data: 'ALL' },
    { value: 'Algerian dinar', data: 'DZD' },
    { value: 'European euro', data: 'EUR' },
    { value: 'Angolan kwanza', data: 'AOA' },
    { value: 'East Caribbean dollar', data: 'XCD' },
            { value: 'Vietnamese dong', data: 'VND' },
    { value: 'Yemeni rial', data: 'YER' },
    { value: 'Zambian kwacha', data: 'ZMK' },
    { value: 'Zimbabwean dollar', data: 'ZWD' },
                    ];
but it is not working when i set lookup source to my array which containing array of objects returned in Ajax Response.and i have different properties in each object of array.you can see there are may objects in my array . Picture is attached below. this is my code .. kindly guide me what am i doing wrong.

 $('#autocomplete').autocomplete({
                    lookup: MenuList,
                    onSelect: function (suggestion) {
                        $('#selection').html('You selected: ' + suggestion.Name + ' ' + suggestion.Id);
                    },
                    showNoSuggestionNotice: true,
                    noSuggestionNotice: 'Sorry, no matching result found'
                });
![not working](https://cloud.githubusercontent.com/assets/23402317/20217642/a11dd0f6-a7d5-11e6-9739-c2a81c81c6e7.PNG)

**Comment by tkirda** [comment]
You need to transform data that matches format that is in the documentation or implement your own `lookup` function.
