### ISSUE TITLE
Option params as callback

### ISSUE THREAD

**Issue by jurkust** [devbridge/jQuery-Autocomplete#557]
It would be nice, if "params" option could accept callback. In my case I want to change category filter, I know that I can change "serviceUrl", but I'm using post, so this produces not nice solution.

**Comment by tkirda** [comment]
You can manipulate params using `onSearchStart` callback.

**Comment by jurkust** [comment]
Thanks it worked, but documentation is outdated. `onSearchStart` is called with `params` as argument and not `query`.

**Comment by tkirda** [comment]
Feel free to submit pull request with updated documentation.
