### ISSUE TITLE
After suggestion is selected, suggestion box dissapears after 1 second

### ISSUE THREAD

**Issue by SoroTrestal** [devbridge/jQuery-Autocomplete#558]
Hi Perhaps i'm doing something wrong, but when I make a selection from the suggestions provided, and I re-select the input text, the suggestion box shows for about 1 second and then dissapears.

Regards

**Comment by tkirda** [comment]
This should be fixed in #552

Just released patched version (v1.2.27) to NPM

**Comment by SoroTrestal** [comment]
Awesome, it works, this is by far the best autocomplete lib. out there, thanks.
