### ISSUE TITLE
I want to get the element to the trigger

### ISSUE THREAD

**Issue by hwb2167sq** [devbridge/jQuery-Autocomplete#559]
Hello,your plugin is very easy to use, but I am now experiencing a problem,I want to get the element to the trigger! Thanks!

**Comment by tkirda** [comment]
Not quite sure what you are trying to do.

**Comment by vittorbraga** [comment]
Hi tkirda, i have a select and when the event onchenge is running i want run the $('#autocomplete').autocomplete({ ..., but it not work for me.

$(document).on("change", "#ufComarca", function() {
    $('#autocomplete').autocomplete({
	serviceUrl: getCidadesAc&idUf='+document.getElementById("ufComarca").value,
	paramName: 'searchstr',
	minLength:1,
	onSelect: function (suggestion) {
		alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
	}
   });	
});

**Comment by tkirda** [comment]
`$(document).on("change")`? I don't such an event on a document.

**Comment by vittorbraga** [comment]
This is a event for select in materializecss.

**Comment by tkirda** [comment]
Closing this because it is not actual issue with the library.
