### ISSUE TITLE
How to request in server once and store the result locally for further lookup

### ISSUE THREAD

**Issue by sopnopriyo** [devbridge/jQuery-Autocomplete#560]
It is not efficient to send request in server after each character is added.  What I would like to do is, send one request in the server with the query parameter and store it locally then all the subsequent filter will be done from local data. 

Just wondering, if that scenario is supported by this plugin or not. If yes, please provide an example .

Thanks

**Comment by tkirda** [comment]
Not out of the box. It is built with assumption that data set is very large, and with extra data it would return different results.

You can implement your own `lookup` function and simply cache responses, so that when extra character are typed just return data from your own cache in memory.

**Comment by ibrierley** [comment]
Interesting. I was just looking for this feature..

Can you give me an example when extra data would return different results ?

Eg if I type 'lond' and the only result is London, is there any need to query the remote url further ? May have a bash at implementing this, but maybe I'm missing some edge cases which would be incorrect.

Thanks for the autocomplete!
