### ISSUE TITLE
Is there any to set default selection programatically?

### ISSUE THREAD

**Issue by cstyle** [devbridge/jQuery-Autocomplete#562]
Is there any to set default selection programmatically?

I am using this awesome plugin. First of all , Thank you so much.

The question is literaly title. When I set list that has 5 array's data to lookup option.
then I want to set default selection to second data.

Is there way for current options? 

Kind regards.

**Comment by tkirda** [comment]
What is default selection? Library does not have a state.

**Comment by cstyle** [comment]
Good morning, Tkirda.
Thank you for reply.

If autocomplete has countries as below
Canada
Australia
Japan

I would like to set Australia at first view by programmatically.

I could set a first one by using autoSelectFirst option.  
Thanks :)

**Comment by tkirda** [comment]
It is up to you how you order your suggestions. It will be displayed in an order that you provide.

**Comment by cstyle** [comment]
Humm!
probably, the best way for me is that I will order the lookup data like below
Australia
Canada
Japan

Then I will use autoSelectFirst option.

Thank you :)
