### ISSUE TITLE
How to display image with formatResult?

### ISSUE THREAD

**Issue by sentiasa** [devbridge/jQuery-Autocomplete#563]
Thanks for the great library!

I am trying to put an image next to the text for each item in the dropdown. As far as I understand, it is possible by doing it in `formatResult`, however I couldn't understand how I will create my `formatResult` section.

```
$('#autocomplete').autocomplete({
        lookup: function (query, done) {
            // here I retrieved the results with ajax and by looping through my results, 
            // pushed inside suggestions. I also have an image for each item, however
            // I couldn't figure out how I will pass the image and how to add it in formatResult

            var object = { "value" : name, "data" : id }
            result.suggestions.push(object);

            done(result);
       }
```

Should I pass the image inside object? I am very confused what I should do at this point.

**Comment by tkirda** [comment]
Make data an object and attach any information that you want to pass to formatResult:

```
data : { id: id, imageUrl: imageUrl }
```

Format result function will get this object and you can read imageUrl that was passed to it.

**Comment by sentiasa** [comment]
Thanks for the super-quick answer.

I read that approach somewhere else, but I couldn't figure out how I can catch it in formatResult and display inside the row. Can you please please provide a more detailed answer? I am sure it will save another newbie of the library too.

**Comment by tkirda** [comment]
Here is how you get data inside `formatResult`:

```javascript
formatResult: function (suggestion) {
    return '<div><img src="' + suggestion.data.imageUrl+'" /> '  + suggestion.value + '</div>';
}
```

**Comment by sentiasa** [comment]
Works awesome Thanks a lot!

I have one quick question. On default it was making the entered query bold in the row, and now it seems like it is gone when I added my formatResult. How can I bring it back so it highlights the input value in the rows' text?

Thanks again

**Comment by tkirda** [comment]
Native implementation highlights result, you can try this:

```javascript
formatResult: function (suggestion, currentValue) {
    return '<div>' + 
              '<img src="' + suggestion.data.imageUrl+'" /> ' +
              $.Autocomplete.formatResult(suggestion, currentValue) + 
           '</div>';
}
```

**Comment by sentiasa** [comment]
Thanks a lot!

**Comment by charlak** [comment]
Updated formatResult call for latest version. 

this.$.Autocomplete.defaults.formatResult(suggestion, currentValue);
