### ISSUE TITLE
onNoSelect event listener

### ISSUE THREAD

**Issue by gideonapollob** [devbridge/jQuery-Autocomplete#564]
Is there a handler when the user leave/blur the autocomplete field without choosing a suggestion? I need to catch that `event` because I need to reset the value of another hidden field if no suggestion has been selected.

Right now, I'm performing another separate ajax call to check if the current value is a valid suggestion and updates that hidden field accordingly.

**Comment by rothschild86** [comment]
I've been using this in the context of LightSwitch framework:

```
        $(element).on('focusout', function (e) { //if ddl was not used. update value only on focus out and not after each char

                contentItem.value = $(control).val();
        });
```

That snippet might not be too useful. But the key is jQuery's focusout event.

**Comment by tkirda** [comment]
There is callback `onInvalidateSelection`. See in the docs.

**Comment by rothschild86** [comment]
Thank you. Somehow missed that :)
