### ISSUE TITLE
Multiples parameters

### ISSUE THREAD

**Issue by jemdev** [devbridge/jQuery-Autocomplete#572]
Hi,
I'm trying to send multiples parameters in a ajax request to complete a field, but can't succeed.

To complete a city name, i want to check two other fields for the coutry ans the zip code. I've found the option « params » but the values are not checked just before sending the request but long before, while loading the script, so the values are not thoose i've writen or choosen in a list.

May i suggest an improvment : in the « params » option, it coul'd be usefull to send an object with the param name an the id of the filed to check, then to send the right value, somthing like this : 
`...
params: {
    'country': '#coutry_select',
    'zipcode': '#zip_input'
},
...`
Then, thoose fields coul'd be checked before sendig the request ans tu URL completed with the right values.

By the way, the doc coul'd be improved for many options...

Thanks for any tips if any.
Regards.

**Comment by Shnoulle** [comment]
Currently i use 

```
            ajaxSettings:{
                beforeSend : function(jqXHR, settings) {
                    // Update you settings url
                    }
                }
```

See : https://api.jquery.com/Ajax_Events/ + https://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings

**Comment by jemdev** [comment]
Thank's Shnoulle,
In fact, I've just found a way to do that.

First, I'v created a callback function to get the right values. That function return a string to complet the serviceUrl.

`...,
			onSearchStart: function()
			{
				var input = $(this);
				var instance = input.data('autocomplete');
				sParams = getAdrParams(ne);
				instance.options.serviceUrl = urlcmn + sParams;
			},
,,,`
Where getAdrParams is my callback function ans urlcmn the serviceURL.

Thanks for your support.
Regards

And now this works as i want.
