### ISSUE TITLE
Clear textfield if no data found or no data selected when lost focus/focusout

### ISSUE THREAD

**Issue by cyberzilla** [devbridge/jQuery-Autocomplete#573]
How to implement with this plugin if no data found or no data selected, the input text/textfield automatically clear when focusout /lost focus

Thanks For Help

**Comment by Shnoulle** [comment]
https://github.com/devbridge/jQuery-Autocomplete/issues/564#issuecomment-271328758 ?

**Comment by cyberzilla** [comment]
i have add 

```
onInvalidateSelection:function (){
		$(this).on("focusout blur",function(){
			$(this).val('');
		});
	}
```

but still nothing happen...

**Comment by tkirda** [comment]
`onInvalidateSelection` is useful to keep track if anything was selected or not. Plugin does not provide functionality that you are asking. You have to figure this our yourself. You can also implement custom your on `lookup` method, where you can clean data when there is no results. 

Although it seems that it would be working as disappearing text for the user.

**Comment by cyberzilla** [comment]
i have found temporary solution

```
onSearchComplete: function (query, suggestions) {
			//count value from array = suggestions.length
			if(suggestions.length===0){
				var focusValue = '' , blurValue ='';
			}else{
				var focusValue = suggestions[0].value , blurValue =suggestions[0].value;
			}
			$(this).on('focus', function() {
				$(this).autocomplete("clear");
        $(this).val(focusValue);
	    });
    	$(this).on('blur focusout', function() {
				$(this).autocomplete("clear");
        $(this).val(blurValue);
    	});
}
```

**Comment by lucabartoli** [comment]
For any future visitors: we solved like this.

```
test = $('.autocomplete').autocomplete({
	maxHeight: 500,
	serviceUrl: '/autocomplete/endopoint',
	triggerSelectOnValidInput: true,
	onInvalidateSelection:function (){
		test.invalid = true;
	},
	onSearchComplete: function (query, suggestions) {
		test.invalid = true;
	}
});
test.on('select', function(e){
	test.invalid = false;
});
test.on('blur', function(e){
	if(true == test.invalid) test.val('');
});
```

**Comment by VaskarBanerjee** [comment]
change: function (ev, ui) {
    if (!ui.item) {
        $(this).val('');
    }
}
