### ISSUE TITLE
Match unordered words

### ISSUE THREAD

**Issue by cirofeitosa** [devbridge/jQuery-Autocomplete#576]
Is there a option to match unordered words in a list?

Example of available list:

`list = ['sun in the sky', 'mood day opening', 'shows at night']`

If I search for "sun sky", the autocomplete didn't find anything.

Is there a option to match the words, even the user type unordered? Needs to intersect all words. 

Thanks a lot.

**Comment by tkirda** [comment]
Out of the box no. You can write your own `lookupFilter` or `lookup` functions to do just that.

**Comment by cirofeitosa** [comment]
Thanks for your response.

I've written a callback with regex in "lookupFilter", and now it search for unordered words. Nice!

However, the highlight does not work. It seems that the plugin does not offer a way to customize the highlight (callback).

Example:

My array os suggestions: ["sun is green", "sun is blue", "sun is yellow"]

If I look for "sun yellow", now it finds, after the function inserted in lookupFilter.

But the highlight does not work, it shows everything without highlighting, rather than highlighting the words "sun" and "yellow."

Is there a way to customize this? 

Regards!
