### ISSUE TITLE
Passing other data to "value"  

### ISSUE THREAD

**Issue by jvpumilia** [devbridge/jQuery-Autocomplete#577]
I am querying a "contacts" table would like to retrieve both the name and the unique id of each contact from the table.  However, I cannot figure out how to pass the unique id to the "value" for form submission so that the contact id is posted to the database while still displaying the full name in the textbox.  I have tried the formatResult to display a "name" which contains the name of the contact.  However, when the name is selected, the textbox changes to display the "value", which is the id, rather than continuing to display the name.

Javascript:
$('#autocomplete').devbridgeAutocomplete({
		serviceUrl:"read_people.php",
		minLength: 2,
		formatResult: function (suggestion, currentValue)	{
			return suggestion.name;
		}
	});	

PHP:
foreach($results as $result)	{
	$suggestions[] = array(
	"value" => $result->people_id,
	"name" => $result->first_name . ' ' . $result->last_name,
	);
	}

I would greatly appreciate it if you could advise me as to whether or not there is a way to make the text box always display the "name" label while the "value" is passed to the form.  

Thank you.

**Comment by tkirda** [comment]
When returning suggestions use following format:

```javascript
{ "value": "john doe", "data": { "id": 1, "name": "John Doe" } }

// Then in formatResult:
formatResult: function (suggestion, currentValue) {
    return suggestion.data.name;
}

// In the onSelect callback you need to remember id that is attached to your data:
onSelect: function (suggestion) {
        $('#input_id').val(suggestion.data.id);
    }

// If user changes value in the input:
onInvalidateSelection: function() {
        $('#input_id').val('');
}
```

**Comment by jvpumilia** [comment]
Thank you for the prompt reply.  Unfortunately, I implemented the suggestions you made but am still experiencing the same problem.  After the suggestion is selected, it changes the text box value from the name to the id.  If i use the onInvalidateSelection option, it resets the textbox to no value.

Again, any help you can offer is greatly appreciated.  (I am just learning PHP and Javascript and this is my first project).

JSON Response: {"suggestions":[{"value":"Al Capone","data":{"id":"1","name":"Al Capone"}}

Javascript: 
$('#autocomplete').devbridgeAutocomplete({
		serviceUrl:"read_people.php",
		minChars: 2,
		formatResult: function (suggestion, currentValue)	{
			return suggestion.data.name;
		},
		onSelect: function (suggestion)	{
			$('#autocomplete').val(suggestion.data.id);
		},
		onInvalidateSelection: function()	{
			$('#autocomplete').val('');
		}, 										 
	});	

PHP:
$suggestions = array();
foreach($results as $result)	{
	$suggestions[] = array(				
	"value" => $result->first_name . ' ' . $result->last_name,
	"data" => array(
		"id" => $result->people_id,
		"name" => $result->first_name . ' ' . $result->last_name,
		)
	);
}

echo json_encode(array('suggestions' => $suggestions));
