### ISSUE TITLE
How should i use lookup in json file?

### ISSUE THREAD

**Issue by JamesJGoodwin** [devbridge/jQuery-Autocomplete#578]
Hey. I have a json file in this format:
```json
[{
   "code":"SCE", 
   "name":"State College",
   "coordinates":{
      "lon":-77.84823,
      "lat":40.85372
   },
   "time_zone":"America/New_York",
   "name_translations":{
      "de":"State College",
      "en":"State College",
      "zh-CN":"大学城",
      "tr":"State College",
      "ru":"Стейт Колледж",
      "it":"State College",
      "es":"State College",
      "fr":"State College",
      "th":"สเตทคอลเลจ"
   },
   "country_code":"US"
}]
```

Code:
```javascript
$('.autocomplete').autocomplete({
	serviceUrl: '/json/cities.json',
	transformResult: function(response){
		return {
			suggestions: $.map(response, function(i) {
				return { value: i.name_translations.ru, data: i.name_translations.ru };
			})
		};
	}
});
```

 And i need to make a lookup at every array element in `name_translations.ru` field, but when i trying to get this, the page just lagged out and tab in browser crashed. How should i make an ajax lookup in my .json file with `name_translations.ru` field? 

Thank you in advance for helping me out

**Comment by tkirda** [comment]
Use server side lookups for this, so you don't have to send lot's of data to the client. Programming questions should be asked on StackOverflow.

Closing this because it is not an issue.
