### ISSUE TITLE
disable() or enable() doesn't work

### ISSUE THREAD

**Issue by Pickuper** [devbridge/jQuery-Autocomplete#58]
...
var ac = $('#query').autocomplete(options);
...
ac.disable();
ac.enable();
- doesn't work! i got errors like "Uncaught TypeError: Object [object Object] has no method 'disable'" in Chrome or "TypeError: ac.disable is not a function" in Firefox

**Comment by patrickbjohnson** [comment]
Is this still the case? Doesn't seem as though called `$('#foo').autocomplete('disable')` actually disables input.
