### ISSUE TITLE
Keywords highlight fix for FULLTEXT indexes 

### ISSUE THREAD

**Issue by SuN-80** [devbridge/jQuery-Autocomplete#588]
Default formatting works great on `%LIKE%` queries, but fails to highlight all keywords on a `MATCH/AGAINST` query. 
Here is how to change this behaviour using optional `formatResult` setting:

```
formatResult: function (suggestion, currentValue) {
      var keywords = currentValue.split(" ");
      var suggest = suggestion.value;
      $(keywords).each(function() {
          suggest = suggest.replace(new RegExp('(' + this + ')(?![^<]*>|[^<>]*</)', 'gi'), '<strong>' + this + '</strong>');  
      });
      return suggest;
    }
```
I think this should be the new default setting because it works in both `%LIKE%` or `MATCH/AGAINST` queries. It is also more a fix than a real custom formatting.

edit: i'm too lazy to create a pull request, but I created a gist: https://gist.github.com/SuN-80/e7bf93956529eea9334e7fad59f4563f

**Comment by tkirda** [comment]
Because there is no universal formatting `formatResult` can be overridden by users.

Your sample has flaws, if special regexp character are used it will fail.

**Comment by SuN-80** [comment]
Well, by default matching keywords are highlighted, but it fails in the case of a `MATCH/AGAINST` query (which is common). It looks like a (trivial) issue to me. It's really nothing specific, I'm not re-formatting anything here, just quick-fixing this default behaviour using available options...
Regex is used to prevent suggestions from matching `<strong/>` tags wrapping keywords added in the loop. It's not 100% reliable, I agree, but it's working great on alphanumeric characters. Tweaking it should not be complicated anyway ;)
