### ISSUE TITLE
set selected item

### ISSUE THREAD

**Issue by vittorbraga** [devbridge/jQuery-Autocomplete#589]
How do I set a selected item when I start autocomplete object?

**Comment by tkirda** [comment]
Not quite sure what you mean, there is no way to preselect item when suggestions are displayed. It is up to the user.

**Comment by vittorbraga** [comment]
I mean when I open a screen in editing.

**Comment by akousmata** [comment]
I know this is closed, but I'm actually looking to do this as well.  The use case is where a user is returning to a form they have already filled out (such as their user profile) and one of the form inputs needs to be an autocomplete.  The initial value of the input field is whatever they filled out last time they submitted the form.  If they highlight the value and start typing, the autocomplete kicks in.  Perhaps I'm overthinking this but seems like it should be possible.

**Comment by tkirda** [comment]
@akousmata autocomplete does not have a state, so there is no such thing as the selected item.

**Comment by akousmata** [comment]
Fair enough.  For my case I can set the input value server side and achieve the same results, but for situations with local lookups or where `setOptions` is called with a new `lookup` array, allowing devs to default the selection either with a separate `defaultValue` options property or an `isDefault` in one of the lookup objects would be a nice-to-have.
