### ISSUE TITLE
Callback for Highlight

### ISSUE THREAD

**Issue by cirofeitosa** [devbridge/jQuery-Autocomplete#592]
I've written a callback with regex in "lookupFilter", and now it search for unordered words. Nice!

However, the highlight does not work. It seems that the plugin does not offer a way to customize the highlight (callback).

Example:

My array of suggestions: ["sun is green", "sun is blue", "sun is yellow"]

If I search for "sun yellow", now it finds, after the function inserted in lookupFilter.

But the highlight does not work, it shows everything without highlighting, rather than highlighting the words "sun" and "yellow."

Is there a way to customize this?

Regards!

**Comment by tkirda** [comment]
You need to write your own highlighter. Here is the concept:

```javascript
var value = 'The sky is blue';
var query = 'blue sky';
var words = query.split(' ').join('|');

var re = new RegExp(`\\b(${words})`, 'gi');

value.replace(re, (match) => `<strong>${match}</strong>`);
// The <strong>sky</strong> is <strong>blue</strong>
```
You can paste and run this in Chrome console.

To be fully functional after you split query, you need to escape special regexp characters, before joining them.

https://lodash.com/docs/4.17.4#escapeRegExp

**Comment by repoles** [comment]
Maybe this can be useful for someone: 

```javascript
var utils = {
  escapeRegExChars: function (value) {
    return value.replace(/[|\\{}()[\]^$+*?.]/g, "\\$&");
  }
};

$('#yourInputId').autocomplete({
  formatResult: function (suggestion, currentValue) {
    var pattern, words;

    if (!currentValue) {
      return suggestion.value;
    }

    words = utils.escapeRegExChars(currentValue);
    words = words.split(' ').join('|');

    pattern = '(' + words + ')';

    return suggestion.value
      .replace(new RegExp(pattern, 'gi'), '<strong>$1<\/strong>')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/&lt;(\/?strong)&gt;/g, '<$1>');
  }
});
```
