### ISSUE TITLE
Support Promise-based extension point

### ISSUE THREAD

**Issue by ErikSchierboom** [devbridge/jQuery-Autocomplete#593]
For my application, the AJAX request that is being sent requires an authorization header to be sent along with the request. There are several extension points that I can use, with the `ajaxSettings` option being the most obvious choice. However, retrieving the token to be sent in the authorization header is an asynchronous operation, and there are no asynchronous extension points in the library. A naive attempt would be to retrieve the token before doing the request, but as the token expires relatively quick, there is q very reasonable possibility that the token will be invalid at some point. How would I best approach this situation?

Having looked at the code, I think there is one relatively easy solution: allow the function to do the actual AJAX call to be passed as an option. This callback function would receive the `ajaxSettings` instance and return a `jqXHR` instance. This would solve my use case, as I now have an extension point that returns a promise, which means that I can prepend my asynchronous call before doing the actual request.

I'd love to see this feature added and would absolutely be willing to submit a PR for this feature.

Hope to hear from you.

**Comment by tkirda** [comment]
In this case I suggest you implement your own `lookup` function, where you handle ajax call yourself and just return results when ready. See **custom lookup** under [usage](https://github.com/devbridge/jQuery-Autocomplete#usage). It can be asynchronous, just call `done` once you have suggestion results.

**Comment by ErikSchierboom** [comment]
@tkirda Ah thanks, I totally missed that. Thanks!
