### ISSUE TITLE
Conflict with jquery-ui-autocomplete with devbridgeAutocomplete

### ISSUE THREAD

**Issue by 5ulo** [devbridge/jQuery-Autocomplete#599]
In WordPress there's native `jquey-ui-autocomplete`. This `devbridgeAutocomplete` is loading after `ui` and still causes errors in `jquery-ui` and then native wordpress autocomplete tags (terms) won't work.

```Uncaught SyntaxError: Unexpected token < in JSON at position 0```

This is causing the chaining function almost at the end of the script

```a.fn.autocomplete=a.fn.devbridgeAutocomplete=function(c,d){```

when I rename the function it suddenly works as expected

```a.fn.autocompleteX=a.fn.devbridgeAutocomplete=function(c,d){```

I know this is not nice solution but works without any conflict.

**Comment by tkirda** [comment]
I will try to change it so that if autotomplete plugin already exists, it would not overwrite.

**Comment by ozcan-durak** [comment]
Hi i have same problem, getting multipledefine error when try to use with Jquery-UI.
