### ISSUE TITLE
Pass data to input

### ISSUE THREAD

**Issue by JPYamamoto** [devbridge/jQuery-Autocomplete#606]
I'm returning the suggestions like this:
`"suggestions":[{"value":"User1","data":"Data1"},{"value":"User2","data":"Data2"}]`
And I'm using this input:
```
<input id="user" type="text" name="user" class="validate">
<label for="user">User</label>
```
It is working just fine.
It is in a form, and when I send the form, I get the value, for example 'User1', 'User2', etc.
I'd like to know if there's a way to display the value, but send the data when I submit my form.
So, instead of sending 'User1', I send 'Data1'.

**Comment by tkirda** [comment]
You need to store `data` field value in a hidden field. You can put value into hidden field via `onSelect` callback.
