### ISSUE TITLE
How to post a json instead of a form data?

### ISSUE THREAD

**Issue by qiansen1386** [devbridge/jQuery-Autocomplete#613]
I have an autocomplete ajax call, should looks like this, but doesn't:
``` js
$.ajax({url:'city.aspx/GetCityList',
            data:"{'city': 'san f'}",
            type:'POST',
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success:function(data){console.log(data.d)}
})
```
When I set `paramName: 'city'`, the payload of the HTTP request looks like `city=san f` instead of `{'city': 'san f'}`, which is not desired.
Because of it, the API server complains about 'Invalid Parameter...blahblahblah'.
Is there a way we can make the payload json, or simply let us manually control the ajax process?
Thanks

**Comment by tkirda** [comment]
Read jQuery documenation on this.

Shouldn't data be simply JSON object and not string?
