### ISSUE TITLE
How to set default value based on particular ID?

### ISSUE THREAD

**Issue by jay4smile** [devbridge/jQuery-Autocomplete#615]
HI,
I have one page, where I have Country select option, based on Country, user can search the states.
to search the states I have used autocompleter. The selected stateid will be stored in DB.
Now, user coming back to same page and if user select the same Country again, it should show the selected state as a default.
I am fetching stateid from DB.

How can I achieve this using jQuery-Autocomplete?

my GET request, returns the response like [{'stateid': 2, stateName: 'ALABAMA'}]. 

I want to provide default selection.

**Comment by tkirda** [comment]
This looks like a programming question rather than issue with a plugin. You may want to ask this question on StackOverflow, you will get answer faster.
