### ISSUE TITLE
inserting the suggestion.value in the input, but displaying the suggestion.data

### ISSUE THREAD

**Issue by lingtalfi** [devbridge/jQuery-Autocomplete#616]
Is it possible to insert the suggestion.value in the input but display the suggestion.data?

My use case is that I fetch a country list from an ajax service, which returns the suggestions.
For instance:

- [data: France, value: FR]
- [data: Bahamas, value: BS]
- ...

And the value I'm interested in when the user posts the form is the suggestion value (FR, BS).
However, it's best for the user to deal with the data (France, Bahamas), so is there an option to inject the data in the autocomplete results list, while having the value posted when the form is posted?

**Comment by tkirda** [comment]
You can store country code in the hidden field and in the input field inside onSelect put country name.
