### ISSUE TITLE
maxHeight + suggestions doesn't show suggestion

### ISSUE THREAD

**Issue by buffpojken** [devbridge/jQuery-Autocomplete#617]
If there are more suggestions than the height of the suggestion box allow, stepping with arrow keys will suggest the item selected, but it won't be scrolled into view in the suggestion box? 

A casual browse through https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L877 suggest to me that it's supposed to? 

![screen shot 2017-05-11 at 17 26 05](https://cloud.githubusercontent.com/assets/47125/25957565/f095a14a-366e-11e7-8663-fee59f06629b.png)

"Klass 11" is now selected by arrow-key, and is below "Daniel Sundström".

**Comment by tkirda** [comment]
Yes it should, see working sample http://devbridge.github.io/jQuery-Autocomplete/

It could be that you need to adjust CSS to overflow auto.

**Comment by buffpojken** [comment]
Thanks for the superquick reply!

I'll check and update here accordingly.

**Comment by buffpojken** [comment]
Works just like intended, thanks for the help!
