### ISSUE TITLE
Width computation problem

### ISSUE THREAD

**Issue by azhuchkov** [devbridge/jQuery-Autocomplete#618]
It seems that computed suggestion box width is a little wider than it should be.

It can be seen here: https://www.devbridge.com/sourcery/components/jquery-autocomplete/ if hide input selection border.

![image](https://cloud.githubusercontent.com/assets/765471/26469550/0f407608-41a3-11e7-918c-6b4d0da41661.png)

The reason is unconsidered border width, so if you set 1px width for suggestion box, you have 2 additional pixels of width that overflows input's one.

**Comment by tkirda** [comment]
It is up to people that use the plugin to style it and match the width. 

You may choose to use `flex` option if `auto` is not good enough for you or simply set width yourself.

**Comment by azhuchkov** [comment]
Yeah, it's cool that there is option to set manually, but your demo has inaccurate width :)
