### ISSUE TITLE
How can pre-filled autocomplete value

### ISSUE THREAD

**Issue by surindersammy** [devbridge/jQuery-Autocomplete#619]
I have value(String) and id(numberic). There any way to make a autocomplete pre-filled. like for edit form.

**Comment by tkirda** [comment]
Not sure I understand what you are trying to accomplish. Prefilling autocomplete would be same as using local lookup. You can load data in advance and store in local lookup array.

See **local lookup** under usage in readme.

**Comment by i108** [comment]
Perhaps the OP wonders about a way the autocomplete field may be presented with one of the local suggestions already pre-filled based on a url parameter for example.

Is there a way to do this? one way to support this would be by specifying selectedIndex on init maybe.
