### ISSUE TITLE
Open all autocomplete-suggestion

### ISSUE THREAD

**Issue by leslie-UFT** [devbridge/jQuery-Autocomplete#620]
Good evening! I have following environment:
A table that in each line has input (hidden and text) and select, when I clone the line a field where I use autocomplete search, there is a problem of opening all suggestion on the page. Regarding the search and selecting are correct, but it makes visible all suggestion. Because of line 264:
```
$ (That.suggestionsContainer) .css ({
                'Max-height': options.maxHeight + 'px',
                'Width': options.width + 'px',
                'Z-index': options.zIndex
            });
```
I've tried getting the ID that I created the most the same problem occurs because it seems to apply to every gift that has class

**Comment by tkirda** [comment]
I don't think there is issue with a plugin. You need to figure out how to instantiate new instance after cloning. 

After cloning you may try to `dispose` existing instance and then instantiate new one. See docs on `dispose`
