### ISSUE TITLE
I need to add class for some condition.

### ISSUE THREAD

**Issue by Arunvelvj** [devbridge/jQuery-Autocomplete#622]
transformResult: function(response) {
        	 var res = JSON.parse(response);
        	 return {
                suggestions: $.map($. parseJSON(response).searchList, function(item) {
               /***********************
                if(item.status == 'INACTIVE'){
                	  
                }
              *******************************/
                var lName = item.lastName != null ? item.lastName : "";
                return { value: item.firstName+" "+lName, data: item.id+","+item.type};
                })
         };
	    }

I need to add class for if item status is inactive.

**Comment by tkirda** [comment]
Use `formatResult` callback for this. See documentation.
