### ISSUE TITLE
Nested JSON in JQUERY autocomplete with cache

### ISSUE THREAD

**Issue by steb86** [devbridge/jQuery-Autocomplete#623]
Hi guys!
I'm not sure how to use properly [jquery autcomplete with caching example](https://jqueryui.com/autocomplete/#remote-with-cache)  in my scenario.

This is a small result of mine JSON (it takes 2 millions results)
```
{  
   "row":[  
      {  
         "LAST_NAME":"PENN"
      },
      {  
         "LAST_NAME":"PENN-LYNCH"
      },
      {  
         "LAST_NAME":"PENNA"
      },
      {  
         "LAST_NAME":"PENNA REIS"
      },
      .......
   ]
}
```

Once I inserted the first value (let say "PENN") and get some results (as example before), I need to use the cached values instead of a new ajax request in order to save time.

Here my JS:

```
var customerCache = {};

$("#last_name").autocomplete({			
	source: function (request, response) {				
					
	if ( request.term in customerCache ) {
		console.log( "In cache" );
	  
		response( $.map( customerCache[request.term], function( item ) {
			return {
				label: item.LAST_NAME,
				value: item.LAST_NAME
			}
		}));		  
		return;
	}					 

	 $.ajax({
		url: "WEB SERVICE URL",
		data: { parmvalues: request.term },
		dataType: "json",
		success: function( data, status, xhr ) {
			
			customerCache[request.term] = data.row;

			response($.map(data.row, function(item) {
				return {
					label: item.LAST_NAME,
					value: item.LAST_NAME
				};
			}));						

		},
		error: function () {
			response([]);
		}
	 });
	},
	minLength: 2,
	delay: 800, 
	select: function( event, ui ) {
		var s_last_name = ui.item.value;
		console.log( "Last Name Selected: " + s_last_name );
	}
});
```

But it never enters into the statement `if ( request.term in customerCache )`, it executes all the time a new ajax request.

What am I missing?

Thank you!
Ciao,
Stefano

**Comment by tkirda** [comment]
Looks like you are using jQuery UI autocomplete and not this one.

http://api.jqueryui.com/autocomplete/

**Comment by steb86** [comment]
Sorry,
my mystake.

Thanks tkirda.

Bye!
