### ISSUE TITLE
unity webgl JSON.parse question

### ISSUE THREAD

**Issue by mic0419** [devbridge/jQuery-Autocomplete#627]
[
![default](https://user-images.githubusercontent.com/24643177/28048015-b5055c60-6620-11e7-8273-5373130ca4ef.png)
](url)

Would like to ask how to solve the problem
Has been tried for a long time

**Comment by tkirda** [comment]
Seems like JSON that is returned is not valid. You may need to use `transformResult` callback and handle string parsing yourself.

**Comment by mic0419** [comment]
@tkirda 
Hello, I have only a little understanding of json and javascript
Where can I get help?

**Comment by tkirda** [comment]
It is best to find someone knowledgeable. Since there is no issue with the plugin itself, I'm closing this issue.
