### ISSUE TITLE
Problems with numerical values

### ISSUE THREAD

**Issue by kokujin** [devbridge/jQuery-Autocomplete#628]
There are problems with numerical values, for example

```````
"Bathroom 25"

jquery.autocomplete.js:749 Uncaught TypeError: suggestion.value.toLowerCase is not a function

```````
A quick fix would be to cast the input value always to a string, as in;

`````` 
 var foundMatch = String(suggestion.value).toLowerCase().indexOf(value) === 0;
``````

**Comment by tkirda** [comment]
All values are expected as strings. If you can not or don't want to change how data is returend, then you can use `transformResponse` and transform values to string before you start working with them.

**Comment by kokujin** [comment]
Can you point me to the place where "transformResponse" is documented? I did not find it. Thanks

**Comment by tkirda** [comment]
All methods are documented in [readme](https://github.com/devbridge/jQuery-Autocomplete/blob/master/readme.md).

**Comment by kokujin** [comment]
@tkirda , no it is'nt. I have read the docs several times. Maybe this issue should be re-opened

**Comment by Shnoulle** [comment]
Just a little error `transformResult` . Still close

**Comment by kokujin** [comment]
"transformResponse" transforms the response, after the fact that the autocompleter has taken the input values into consideration. Why was this ticket closed?

**Comment by tkirda** [comment]
`transformResult` is applied when data is received from the server. It was closed because it works as expected. It also provides a mechanism to transform values into supported format.

**Comment by kokujin** [comment]
It seems as if there is a misunderstanding here. The combination of a string and numerical value typed in BEFORE suggestions are created causes problems. 

if I type in "Bathroom 123", Bathroom is detected and I get suggestions, but breaks when it reaches 123 because it is interpreted as numerical, nothing to trans form here because it does'nt get that far.

**Comment by tkirda** [comment]
Not sure what you mean by _interpreted_, value inside input field is always of type string.

**Comment by kokujin** [comment]
From my debugging, the value inside the is not always a string, as in "Bathroom 123", tested in the latest Chrome browser.
