### ISSUE TITLE
The widget is not filtering suggestions

### ISSUE THREAD

**Issue by eddywm** [devbridge/jQuery-Autocomplete#631]
It keeps showing a list of all available suggestion elements instead of keeping filtering specific elements.
The most matching element is not getting into the top of the suggestions.
Here is the code I am using.

            $('#search_autocomplete').autocomplete({
                serviceUrl: '/search_data'
            });
     
Here is my json response from the server.
![json_response](https://user-images.githubusercontent.com/25495376/28459698-2fda5cda-6e17-11e7-8d1e-e8cf4830c128.png)

**Comment by tkirda** [comment]
If you are returning full data set the you should not be using server side suggestions. Server side suggestions used only for large result sets. 

You can load data and use local lookup. See documentation.

**Comment by eddywm** [comment]
The documentation is not  clear on which **param name**  that can be used on the server to get the current typed string and make the filtering action on the server side.
