### ISSUE TITLE
Drop in replacement for jQuery UI autocomplete?

### ISSUE THREAD

**Issue by oshihirii** [devbridge/jQuery-Autocomplete#634]
Apologies for any note of desperation in this question, but is `devbridge/jQuery-Autocomplete` a drop in replacement for jQuery UI autocomplete?

Production code has started crashing occasionally and "unpredictably" on tablet in chrome (when *selecting* the desired item or *scrolling through* the list of results) and am thinking it is a memory issue and I need to find something lighter.  

The dataset is a variable assigned the value of an array of ~5,500 objects with 5 properties each.  

Thank You.  

Edit: [jsFiddle of implementation](http://jsfiddle.net/rwone/ga4xqtzy)

Edit:  For more context, current implementation is essentially as follows:

    // BEGIN autocomplete
    $(".pi_number").autocomplete({
        // only show 5 results with scrollbar
        // from:  http://anseki.github.io/jquery-ui-autocomplete-scroll
        maxShowItems: 3,
        // look up on two values solution
        // see:  https://stackoverflow.com/a/15849692
        source: lightwell,
        minLength: 4,
        // called on input blur if value has changed
        change: function(event, ui) {

        // do things

        },
        // called when selecting an option
        select: function(event, ui) {

        // do things

        },
        // called when search starts
        search: function(event, ui) {

        // show fontawesome loading animation

        },
        // called when search finishes
        response: function(event, ui) {
        
        // hide fontawesome loading animation

        },

        // BEGIN add styles to results
        // from:  https://gist.github.com/DBasic/9545690
        create: function() {
                $(this).data('ui-autocomplete')._renderItem = function(ul, item) {

                    // create a new 'value' string for match highlighting
                    // see: https://stackoverflow.com/a/9889056/1063287
                    var newValueText = String(item.value).replace(
                        // changed "gi" to i so that the match on instance of search term is limited to the first match, see:  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp
                        new RegExp(this.term, "i"),
                        "<span class='ui-state-highlight'>$&</span>");

                    // create a new 'description' string for match highlighting
                    var newDescText = String(item.ProdDescr.toUpperCase()).replace(
                        new RegExp(this.term, "gi"),
                        "<span class='ui-state-highlight'>$&</span>");

                    return $("<li></li>")
                        .data("ui-autocomplete-item", item)
                        .append("<div class=\"my_product_lookup_result\"><span class=\"my_product_lookup_helper\"></span><div class=\"my_product_lookup_result_img\"></div>" + newValueText + " - " + newDescText + "</div>")
                        .appendTo(ul);
                }
            }
            // END add styles to results

    });
    // END autocomplete

**Comment by tkirda** [comment]
No it is not drop in replacement, but fairly straightforward to setup. Read docs and look at the samples inside the `scripts/demo.js`.
