### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by btn-ninja** [devbridge/jQuery-Autocomplete#636]
hi,
Demo appears not to work (windows Chrome)
https://www.devbridge.com/sourcery/components/jquery-autocomplete/

Error in console related to sourcery.

**Comment by Aleksandr-ru** [comment]
+1 in Firefox on ubuntu linux

> TypeError: t.slick is not a function[Подробнее]  sourcery-main.min.js:58:13016

**Comment by oshihirii** [comment]
Also in Chrome on Ubuntu.  
Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by oshihirii** [comment]
Update: It seems disabling any adblocker plugins enables demo.

**Comment by hosein2398** [comment]
In my computer it works fine (Chrome 60.0.3112.113 (Official Build) (64-bit) and Win-8) , but in my colleague's one not so.
He is on Chrome and Win10 and this error appears on console.
![photo_2017-09-02_10-17-51](https://user-images.githubusercontent.com/17067774/29993582-73c697a8-8fd0-11e7-9862-7b04b0e68e97.jpg)

**Comment by hosein2398** [comment]
@oshihirii  Nope, I ask my friend he said he has some plugins on chrome but no adblocker.
And also we figured out that it's not working on his laptop in MS Edge too.

**Comment by oshihirii** [comment]
Performance on demo site is intermittent for me, sometimes autocomplete doesn't work, then I reload page and it does.

**Comment by tkirda** [comment]
Demo site is outdated. Please check latest docs and demo here: 

http://devbridge.github.io/jQuery-Autocomplete/

**Comment by oshihirii** [comment]
For reference, I'm working on a highly commented version of the demo, discussed in this thread: 
 https://github.com/devbridge/jQuery-Autocomplete/issues/646

**Comment by btn-ninja** [comment]
I got the link from the very top of your github page:
https://github.com/devbridge/jQuery-Autocomplete

Update link to avoid more people like me. :)
