### ISSUE TITLE
Typings not installed through NPM

### ISSUE THREAD

**Issue by ErikSchierboom** [devbridge/jQuery-Autocomplete#637]
When installing using NPM, the typings are not found. Upon inspection, this is due to the typings file not being published in the NPM package. These are the files included in the NPM package:

<pre>
- dist/jquery.autocomplete.js
- dist/jquery.autocomplete.min.js
- license.txt
- license.txt
- package.json
- readme.md
</pre>

It thus makes sense that the typings cannot be found, as the typings file is not included in the package.

**Comment by martinduparc** [comment]
This provides more information on how to bundle the typings: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by x-abdelbasset** [comment]
try to add `"main": "dist/jquery.autocomplete.js"` to package.json

**Comment by KimPrince** [comment]
I installed through NPM and I am getting a TypeError.  `Suggestions` is undefined.  Is this the likely cause?  What's the work around?

**Comment by tkirda** [comment]
Published new version with Typings included from PR: #651
