### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by lezhiro** [devbridge/jQuery-Autocomplete#640]
HI,

When doing a query typing "Servo" throws the following error:
```

Uncaught TypeError: Can not read property 'replace' of undefined
    At _formatResult (jquery.autocomplete.js: 145)
    At Object. <Anonymous> (jquery.autocomplete.js: 668)
```

`
return suggestion.value

            .replace(new RegExp(pattern, 'gi'), '<strong>$1<\/strong>')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/&lt;(\/?strong)&gt;/g, '<$1>');
    };
`
But if I type "servom" it generates the query correctly.

I am using Ajax Autocomplete for jQuery, version 1.4.2 and jQuery JavaScript Library v2.1.1

**Comment by tkirda** [comment]
This means that your results contain suggestion that is undefined. Maybe you have a trailing comma at the end.

**Comment by lezhiro** [comment]
Hello,

Here is an example that implements with servlets:

[Example](http://132.148.7.92/test/)

But check and I do not have any "," or special characters.

But the detail is that they are only "servo" and "servov" because as I commented with "servom" everything works perfectly.

Replace the line

`return value.replace (/ [| \\ {} () [\] ^ $ + * ?.] / g, "\\ $ &");`

by

` return value.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");`

But, I still generate the same error.

You think that at the time of writing the string in JSON, I use the following code.

```
 Q = request.getParameter ("query");
 ArrayList <Products> o = ProductsDB.getProduct (q);
 Gson gson = new Gson ();
 //System.out.println(request.getParameter("query "));
 // String json = gson.toJson (o);
 //System.out.println(q);
  // System.out.println (json);

   response.setContentType ("application / json");
   response.setCharacterEncoding ("UTF-8");
   response.getWriter (). write ("{\" suggestions \ ":" + gson.toJson (o) + "}");
```

 I use the gson-2.8.1 library](url)

**Comment by tkirda** [comment]
Just inspect your response returned by the server and check if every suggestion has expected format.

**Comment by lezhiro** [comment]
Thanks, it was correct that I was returning something wrong, since I was able to correct my problem, it was a function in the query I was using.

Was wearing :

```
pst = con.getConexion().prepareStatement("SELECT idproducto, CONCAT(nombre_producto,' // ',trim(tipo)) "
                    + "FROM indice where nombre_producto like ? order by nombre_producto limit 80;");
            pst.setString(1, "%" + id + "%");
            resultSet = pst.executeQuery();
            while (resultSet.next()) {
                Productos c = new Productos();
                c.setData(resultSet.getInt(1));
                c.setValue(resultSet.getString(2));
                data.add(c);
            }
```

And to correct it just use another function:

```
pst = con.getConexion().prepareStatement("SELECT idproducto, CONCAT(nombre_producto,' // ',IF(tipo='PRODUCTO','PRODUCTO','EMPRESA')) "
                    + "FROM indice where nombre_producto like ? order by nombre_producto limit 80;");
            pst.setString(1, "%" + id + "%");
            resultSet = pst.executeQuery();
            while (resultSet.next()) {
                Productos c = new Productos();
                c.setData(resultSet.getInt(1));
                c.setValue(resultSet.getString(2));
                data.add(c);
            }
```


Already working properly.

Thanks.
