### ISSUE TITLE
Demo site ajax lookup using local lookup (and not jquery-mockjax)?  

### ISSUE THREAD

**Issue by oshihirii** [devbridge/jQuery-Autocomplete#646]
I am referring to the demo site:  

http://devbridge.github.io/jQuery-Autocomplete

which utilises [jquery-mockjax](https://github.com/jakerella/jquery-mockjax).

The demo source for the ajax lookup shows that it is using a local lookup and not the `serviceUrl` option (which I imagine is intended to work with `jquery-mockjax`):
```js
// Initialize ajax autocomplete:
$('#autocomplete-ajax').autocomplete({
    // serviceUrl: '/autosuggest/service/url',
    lookup: countriesArray,
    lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
        var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
        return re.test(suggestion.value);
    },
    onSelect: function(suggestion) {
        $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
    },
    onHint: function(hint) {
        $('#autocomplete-ajax-x').val(hint);
    },
    onInvalidateSelection: function() {
        $('#selction-ajax').html('You selected: none');
    }
});
```
I'm working on a highly commented version of the demo here ([codepen](https://codepen.io/oshihirii/pen/EvMjZm)) and cannot get the `serviceUrl` version working, can you please tell me how to get the ajax lookup example working without using the local `lookup` option?  

Thanks!

**Comment by oshihirii** [comment]
Update: jQuery 3.2.1 works with:

https://cdn.jsdelivr.net/npm/jquery-mockjax@2.2.2/src/jquery.mockjax.min.js

**Comment by itsmekps** [comment]
I am new to mockjax can u pls tell me how to use it against data coming from url instead of countries array

`    
var countries = {
     "AD": "Andorra",
    "A2": "Andorra Test",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla"
}
var countriesArray = $.map(countries, function (value, key) { return { value: value, data: key }; });

    // Setup jQuery ajax mock:
    $.mockjax({
        url: '*',
        responseTime: 2000,
        response: function (settings) {
            var query = settings.data.query,
                queryLowerCase = query.toLowerCase(),
                re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi'),
                suggestions = $.grep(countriesArray, function (country) {
                     // return country.value.toLowerCase().indexOf(queryLowerCase) === 0;
                    return re.test(country.value);
                }),
                response = {
                    query: query,
                    suggestions: suggestions
                };

            this.responseText = JSON.stringify(response);
        }
    });

    // Initialize ajax autocomplete:
	
    $('#autocomplete-ajax').autocomplete({
        // serviceUrl: '/autosuggest/service/url',
        lookup: countriesArray,
        lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
            var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
            return re.test(suggestion.value);
        },
        onSelect: function(suggestion) {
						alert(suggestion.value + ', ' + suggestion.data);
            $('#selction-ajax').html('You selected: ' + suggestion.value + ', ' + suggestion.data);
        },
        onHint: function (hint) {
            $('#autocomplete-ajax-x').val(hint);
        },
        onInvalidateSelection: function() {
            $('#selction-ajax').html('You selected: none');
        }
    });`

Pls Help...
