### ISSUE TITLE
What does onHint do?

### ISSUE THREAD

**Issue by oshihirii** [devbridge/jQuery-Autocomplete#647]
In the demo code there is:
```js
onHint: function(hint) {
    $("#autocomplete-ajax-x").val(hint);
  },
```
but it it not described in readme.

What does `onHint` do?

**Comment by tkirda** [comment]
See first sample on [demo page](http://devbridge.github.io/jQuery-Autocomplete/).

Hint is when value is displayed in the background. Need special setup to support this functionality.

**Comment by oshihirii** [comment]
Ah, I was confused because it is called with:
```js
$('#autocomplete-ajax').autocomplete({
...
onHint: function (hint) {
$('#autocomplete-ajax-x').val(hint);
}
```
ie, the div id is `autocomplete-ajax` (but the `onHint` uses an id with a `-x` suffix).  

Then I saw the double input in the HTML - excellent idea!
