### ISSUE TITLE
How to display selected value differently from suggestion list

### ISSUE THREAD

**Issue by Mushr0000m** [devbridge/jQuery-Autocomplete#650]
Hi,

I'm using AJAX request to display a list of suggestion, but when the user select one I want to keep only a part of the suggestion clicked. For exemple in the suggestion if he click on "Ford mustang - Car", I want to only display "Ford mustang" in the input field.

I'm using `transformResult`to format my suggestions from the AJAX call. But If I alter the value in the input (in the example to remove "- Car"), then if the user click again on the autocomplete or use left right arrow the suggestion appear again and the callback `onInvalidateSelection` is called.

Any Idea how can i accomplish that ? Thanks

**Comment by tkirda** [comment]
Use `formatResult` to display value that is different. When user clicks, it will use actual value.
