### ISSUE TITLE
Start searching of the text from beginning

### ISSUE THREAD

**Issue by jai-singhal** [devbridge/jQuery-Autocomplete#654]
First, of all, I want to thank the developers of this awesome Jquery Plugin. I have implemented this plugin on my project.
I have two queries to ask
1. Can I start searching the text or shows the results from the first character onwards only? I want to search the text from the beginning of the text only and not from anywhere in the middle. I am doing this because some of my results do not show because it searches from anywhere.

2. I am searching the text from a JSON data, and the JSON data is of almost 1.5 MB. So can I cache the data and store that data at client side and re-create the cache according to the need?

**Comment by djkraz** [comment]
actually it's pretty easy to make it search from the beginning.  Just use the lookupFilter parameter like so:

`
lookupFilter: function (suggestion, query, queryLowerCase) {
  return suggestion.data.toLowerCase().indexOf(queryLowerCase) == 0;
},
`
