### ISSUE TITLE
Broken setOptions method

### ISSUE THREAD

**Issue by thadin** [devbridge/jQuery-Autocomplete#655]
Since issue #600 the `setOptions` method no longer works correctly, see also the comment on commit cadd05f.

The new `$.extend` syntax creates a new `this.options` object, which looses the reference from `options` to `that.options`. Any changes made in the `setOptions` method to the `options` object aren't updated in `that.options`.

**Comment by tkirda** [comment]
This has been fix in latest in **v1.4.3** with: https://github.com/devbridge/jQuery-Autocomplete/commit/37bf4627f20fd3446b2802dd2653380b805f8757
