### ISSUE TITLE
Call ajax without query - Enhancement

### ISSUE THREAD

**Issue by Gouigouix** [devbridge/jQuery-Autocomplete#656]
Hi,

When I use Autocomplete with internal API service it's ok. But today I have an external API service with query parameter like this "http://external-api.com/test", test is a query equal to "http://internal-api.com?query=test".

You can add this freature ;o)
Thank you.

**Comment by tkirda** [comment]
Pass to `serviceUrl`  function which returns URL that you want to hit:

```javascript
serviceUrl: (query) => 'http://external-api.com/' + encodeURIComponent(query)
```

**Comment by Gouigouix** [comment]
@tkirda Very cool, great job ;)
