### ISSUE TITLE
Issue while using Devanagari characters

### ISSUE THREAD

**Issue by rohitsahasrabudhe** [devbridge/jQuery-Autocomplete#657]
The list does not display Devanagari script properly. Attaching image to explain the difference.

There are two lists in the image - one on the right is from jQuery-Autocomplete and one on the left is from bootstrap-select, which displays Devanagari characters properly.
![autocomplete display problem](https://user-images.githubusercontent.com/10877336/30701141-27fbf5de-9f07-11e7-9691-707d217db34b.png)

**Comment by tkirda** [comment]
There is nothing special done that may affect how characters are rendered. Those depend on selected font and text encoding.

If you setup sample on a single page to be able to reproduce that I may be able to look into this.

**Comment by rohitsahasrabudhe** [comment]
This seems to be an issue with the older version which I am using. Attaching a sample html file that I tried out with v1.2.8 and 1.4.2. The issue is reproducible in v1.2.8 but not in v1.4.2.

With v1.4.2. however, it gives an error when lookup is given as a string array instead of a suggestions (data, value) array.
[Autocomplete Sample.zip](https://github.com/devbridge/jQuery-Autocomplete/files/1322489/Autocomplete.Sample.zip)

**Comment by tkirda** [comment]
If this is not reproducible in 1.4.2 then there is nothing to look at.

I can confirm that there is an issue with string array. Will patch that.

**Comment by rohitsahasrabudhe** [comment]
Thanks for the patch, Tomas. The string array works in v1.4.3. This is an awesome tool btw, thanks for that too :)
