### ISSUE TITLE
Hide not matching results

### ISSUE THREAD

**Issue by auchri** [devbridge/jQuery-Autocomplete#658]
Hi,

thanks for the great library!

I've tried the example from the readme:

```js
$('#autocomplete').autocomplete({
    lookup: function (query, done) {
        // Do Ajax call or lookup locally, when done,
        // call the callback and pass your results:
        var result = {
            suggestions: [
                { "value": "United Arab Emirates", "data": "AE" },
                { "value": "United Kingdom",       "data": "UK" },
                { "value": "United States",        "data": "US" }
            ]
        };

        done(result);
    },
    onSelect: function (suggestion) {
        alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
    }
});
```

However, if I enter for example `Kingdom`, the other two suggestions (which have nothing to do with the query) are still visible.
Is there an option available to hide these invalid suggestions?

**Comment by tkirda** [comment]
As you can see, you lookup function receives query value. So you should filter your set and return only those that need to be displayed. This function is executed as user types into input box.
