### ISSUE TITLE
Positioning issue with css zoom on body when scrolling

### ISSUE THREAD

**Issue by vinroy89** [devbridge/jQuery-Autocomplete#663]
Hi,
I have a weird issue and I'm wondering is anyone has seen it. In one of our project, we have a css zoom attribute of 0.9 on the body. The autocomplete suggestion are positioned correctly when there's no scroll applied on the page, however, since the app is responsive the control moves up and down. As soon as I scroll down, the suggestions won't be positioned correctly.

I tested also reproduced on this site: http://devbridge.github.io/jQuery-Autocomplete/
If a zoom > 1 is applied to the page, the suggestions will be positioned below the control and if a zoom < 1 is applied, depending on the amount scrolled on the page the suggestions will gradually be over and then above the control.

Please see attached print screen. For the sake of the test i added a 1500px padding on the body to generate some "scroll"

Thanks!

![zoom05](https://user-images.githubusercontent.com/32554081/31249603-f8983e4e-a9e5-11e7-9f82-dd25595644ca.png)
![zoom15](https://user-images.githubusercontent.com/32554081/31249606-fb3455b6-a9e5-11e7-835c-c0ad0c184d19.png)

**Comment by tkirda** [comment]
It may be best four you to render suggestions into container that is positioned correctly and plugin does not need to track of it's position. Check `appendTo` option.
