### ISSUE TITLE
Make triggerSelectOnValidInput trigger on similar input too

### ISSUE THREAD

**Issue by zenichanin** [devbridge/jQuery-Autocomplete#664]
Is there a built-in way of making `triggerSelectOnValidInput` trigger on input that's very similar?

For example, let's say they type in "Roberts" or "Robert" but the actual value is "Robert's". Obviously they can click on it, but is there a way to make it auto select?

**Comment by tkirda** [comment]
No, there is no built in way to accomplish this.
