### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by verglor** [devbridge/jQuery-Autocomplete#665]
Live demo on page https://www.devbridge.com/sourcery/components/jquery-autocomplete/ is not working - there is error in js console: `Uncaught TypeError: t.slick is not a function`

**Comment by paulm17** [comment]
Try turning off your ad blocker, I had this exact same issue.

**Comment by imemohit** [comment]
Can confirm, works fine when ad blocker is disabled.

**Comment by molfar** [comment]
Any fixes? I'm afraid to use this plugin in production...

**Comment by tkirda** [comment]
Issues are not related to plugin. Plugin demo can be found here: http://devbridge.github.io/jQuery-Autocomplete/

If afraid, don't use it.
