### ISSUE TITLE
How to get suggestion's data from focused/on hover suggestion?

### ISSUE THREAD

**Issue by Firman95** [devbridge/jQuery-Autocomplete#666]
Is there a way to get suggestion.data? Something like this:
`onFocus: function (focusedSuggestion) {
    console.log(focusedSuggestion.data);
 },`

**Comment by tkirda** [comment]
There is no simple way to get this. You would need to modify source, easiest would be to fire event inside `activate` method.

**Comment by Firman95** [comment]
Ok thanks
