### ISSUE TITLE
TypeError: b is undefined

### ISSUE THREAD

**Issue by AdrianBiakov** [devbridge/jQuery-Autocomplete#668]
Method which return json data:
[HttpGet]
public ActionResult GetTags()
{
    using (var stream = new FileStream("tags.json", FileMode.Open))
    using (var streamReader = new StreamReader(stream))
    {
        string json = streamReader.ReadToEnd();
        return Json(json);
    }
}

tags.json file:
[
  { "value": "USA" },
  { "value": "Germany" }
]

Script in view:
<script>
    $('#tagInput').autocomplete({
        serviceUrl: '/Home/GetTags'
    });
</script>

**Comment by tkirda** [comment]
Result should be an object with suggestions property:
```
{
        suggestions: [
                { "value": "United Arab Emirates", "data": "AE" },
                { "value": "United Kingdom",       "data": "UK" },
                { "value": "United States",        "data": "US" }
            ]
}
```

**Comment by AdrianBiakov** [comment]
@tkirda Same problem. I tried
`{
        suggestions: [
                { "value": "United Arab Emirates", "data": "AE" },
                { "value": "United Kingdom",       "data": "UK" },
                { "value": "United States",        "data": "US" }
            ]
}`
and
`{
  "suggestions": [ "United Arab Emirates", "United Kingdom", "United States" ]
 }`
