### ISSUE TITLE
Event onSelect bug

### ISSUE THREAD

**Issue by vanilevsky** [devbridge/jQuery-Autocomplete#669]
Hello! I found an error in the event onSelect. I will describe the sequence of actions leading to an error.

1. I enter a search query in input search field.
2. The drop-down list displays for example 15 lines.
3. First use the arrow buttons to select the fifth item.
4. Then click on the tenth element with the mouse pointer.
5. In the event handler for the onSelect event, the fifth element appears in suggestion, instead of the tenth.

```
$('#employee').autocomplete({
    minChars: 3,
    maxHeight: 500,
    serviceUrl: '/mySearch',
    type: 'GET',
    dataType: 'text',
    paramName: 'q',
    onSelect: function (suggestion) {
        $("form#employee_search").submit();
    }
});
```

**Comment by tkirda** [comment]
This is very interesting. Good catch, I can confirm that there is an issue. Browser will trigger "change" event for the value that was set by the plugin when navigating using keyboard.
