### ISSUE TITLE
undefined value brake autocomplete

### ISSUE THREAD

**Issue by gg4u** [devbridge/jQuery-Autocomplete#670]
i am trying to map results form a server.

It works, but as soon as I type a combination of letter for which there is no result, autocomplete brakes and does not fetch results anymore.

There is another thread that says it is due because value of `value` is undefined.
I tried the following , but still breaks.

How to solve  it?

```

transformResult: function(response) {
return {
            suggestions: $.map(JSON.parse(response), function(dataItem) {

                console.log('response', dataItem, typeof dataItem);

               // console.log correctly shows:
              // response no results string
              // for the first missing results (response is without results)
             // but Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
            // breaks the code

                var value, data;

                if (dataItem) {
                   value = dataItem.id,
                   data = dataItem
                }
                else {

                   value = '',
                   data = ''
                }



                return { value: value, data: data };
                
                
            })
} 

```
> Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
>     at b.isExactMatch (jquery.autocomplete.min.js:8)
>     at b.suggest (jquery.autocomplete.min.js:8)
>     at b.processResponse (jquery.autocomplete.min.js:8)
>     at Object.<anonymous> (jquery.autocomplete.min.js:8)
>     at i (jquery.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery.min.js:2)
>     at A (jquery.min.js:4)
>     at XMLHttpRequest.<anonymous> (jquery.min.js:4)

**Comment by tkirda** [comment]
I there is no results, response should be an empty array:
```javascript
{ suggestions: [] }
```
