### ISSUE TITLE
Few default suggestions on focus

### ISSUE THREAD

**Issue by LukSkywookie** [devbridge/jQuery-Autocomplete#671]
Hi.
First I want to say how good this plugin is and how much it's helping me ;).

Now it's time for question :P.
Is there an option to show the list of default options on focus? 
This is the only thing missing for me.

Regards,
SkyWookie

**Comment by tkirda** [comment]
No such option. But you can set `maxChars` to zero. This will trigger auto suggest on focus even with empty query. For empty query you can return list that you consider default.

**Comment by LukSkywookie** [comment]
Thanks a lot!
It was `minChars` combined with `lookup` event ;)

**Comment by rajitha-bandara** [comment]
`minChars: 0`, worked for me also.
