### ISSUE TITLE
How to trigger a new match after changing input

### ISSUE THREAD

**Issue by snowpilot** [devbridge/jQuery-Autocomplete#672]
I am building a registration-office search with jQuery-Autocomplete. When a user enters a zip code with no matching office the list is hidden because it is empty. Then I slice off the last digit of the zip code in the form input to perform an new match. Unfortunately no new match is  being performed. How can I trigger a new match after the input has been changed with the jQuery .slice() method? I tried .trigger('keyup') and other events but none are working for me. 

Only extending the findMatch() function in the jQuery-Autocomplete plugin works for me (but changing a library is no option):

```
// No match for area code: slice last digit and perform new match
  while (preparedList.length === 0 && !isNaN(phrase)) {
         phrase = phrase.slice(0, -1);
          for(var i = 0, length = list.length; i < length; i += 1) {
               value = config.get("getValue")(list[i]);

                if (match(value, phrase)) {
                     preparedList.push(list[i]);
                 }
           }
  }
```

Do you have any ideas?

**Comment by tkirda** [comment]
If you update value inside input box, you can call `onValueChange()` method on autocomplete instance. This is not documented because it is internal code:

```javascript
$('#zipcode').val('123');
$('#zipcode').autocomplete().onValueChange();
```

**Comment by snowpilot** [comment]
Thank you!
