### ISSUE TITLE
Am I using ajax wrong.

### ISSUE THREAD

**Issue by rgfx** [devbridge/jQuery-Autocomplete#674]
This works but its slow. Ajax post the info fast but it take some time for autocomplete to pick it up. I think am doing something wrong since its my first time using ajax. 

Can someone please take a look at my script and let me know if there is something obviously wrong. 

```javascript
$(".search-input").autocomplete({
  minChars: 3,
  showNoSuggestionNotice: true,
  noSuggestionNotice: "no results",
  lookup: function(name, done) {
    $.ajax({
      type: "POST",
      dataType: "json",
      url: magicalData.siteURL + "/wp-admin/admin-ajax.php",
      data: {
        action: "get_listing_names",
        name: name
      },
      success: function(data) {
        titles = data;
        cb(titles);
      }
    });

    function cb(titles) {
      result = titles;
      return result;
    }

    done(result);

  }
});
```

**Comment by tkirda** [comment]
Make sure server responds quickly and suggestion list is relatively short. 

Slowest part usually is network. You can inspect speed in the network tab in chrome developer tools.

**Comment by rgfx** [comment]
Everything looks alright? I console log titles and results from the server come faster and more often then autocomplete. That's the reason I asked. let me know, thanks.

**Comment by tkirda** [comment]
Looks OK, unless there are any errors in response.

**Comment by rgfx** [comment]
OK? Is there a better way? I get a "result is not defined" with my first character, I assumed this was because I haven't recieved a server response yet. 

Tried below things went even slower 

```javascript
if (typeof result === "undefined") {
return;
} else {
done(result);
```

**Comment by tkirda** [comment]
You should call `done` in ajax callback function:

```javascript
$(".search-input").autocomplete({
  minChars: 3,
  showNoSuggestionNotice: true,
  noSuggestionNotice: "no results",
  lookup: function(name, done) {
    $.ajax({
      type: "POST",
      dataType: "json",
      url: magicalData.siteURL + "/wp-admin/admin-ajax.php",
      data: {
        action: "get_listing_names",
        name: name
      },
      success: function(data) {
        titles = data;
        done(data)
      }
    });
  }
});
```

**Comment by rgfx** [comment]
I swear I tried that before and got an error, works fine now. Thanks for taking the time to help me.
