### ISSUE TITLE
multiple autocompletes on page

### ISSUE THREAD

**Issue by fdkevin** [devbridge/jQuery-Autocomplete#679]
I have multiple autocompletes on the same page, but the first one sometimes doesn't work, but when it does work it opens the autosuggest list then never updates as you continue to type in the box. 

here is some of the code

`$(function(){

    // setup autocomplete function pulling from currencies[] array
    $('.locationTxt').autocomplete({
        serviceUrl: "remote/call/to/data",
        type: "POST",
        dataType: "json",
        noCache: true,
        onSelect: function (suggestion) {
            $(this).val(suggestion.data);
        }
    });

    // setup autocomplete function for practice area box
    $('.practiceTxt').autocomplete({
        serviceUrl: "remote/call/to/data",
        type: "POST",
        dataType: "json",
        noCache: true,
        onSelect: function (suggestion) {
            $(this).val(suggestion.data);
        }
    });`

and the html of the autocomplete text fields

`<div class="search-form-group">
                    <label for="practiceTxt" class="txt-for">for</label>

                    <input type="text"
                           class="form-control icon-bg practiceTxt"
                           placeholder="Practice or Attorney"
                           name="practiceTxt"
                           value="">

                    <input type="hidden"
                           id="practiceAreaSelected"
                           name="practiceAreaSelected"
                           value="" >
                </div>

                <div class="search-form-group">
                    <label for="location" class="txt-in">in</label>

                    <input type="text"
                           class="form-control icon-bg locationTxt"
                           placeholder="City, State or Attorney"
                           name="location"
                           value="">             
                </div>`

**Comment by tkirda** [comment]
You may have errors, check if everything is fine in developer tools. 

Multiple autocompletes on one page are perfectly fine:

http://devbridge.github.io/jQuery-Autocomplete/

Your code looks fine. Just strange that you are setting input value in the `onSelect. Plugin already does that.

**Comment by fdkevin** [comment]
I see a js error coming from the autocomplete library TypeError: suggestion.value.replace is not a function. my value was an integer, not a string.

**Comment by tkirda** [comment]
Sounds like you figured out the issue. `value` always expected to be a string.
