### ISSUE TITLE
use   e like ë and q like ç 

### ISSUE THREAD

**Issue by d00nn1** [devbridge/jQuery-Autocomplete#680]
hello i am sory my english is not so good i use jur autocomplete and its great the best autocomplete ever  but   whenn in sugest are example        (është) and i tip in my phone (eshte) dont show the (është) sugest , it is posible to meack it ?

**Comment by tkirda** [comment]
You need to adjust filtering algorithm. Similar issue is discussed here: https://github.com/devbridge/jQuery-Autocomplete/issues/155
