### ISSUE TITLE
Highlight, when presents, more than one words

### ISSUE THREAD

**Issue by luX0r-reload** [devbridge/jQuery-Autocomplete#682]
Hi,
Thanks for your useful works, I'm using autocomplete for a project and it works very well.
Suggests box in my project works like the eBay one, and my db query retrieve suggestions through one or more keywords.
E.g. writing "nvidia 4000" my query retrieve "nvidia quadro 4000" results too.
In this case your autocomplete highlight (make bold) only the nvidia word.
It's possible highlight the other keywords too?

Thanks in advance.

L.

**Comment by tkirda** [comment]
You need to implement custom `formatResult`. Sample how to match multiple words can be found here: https://github.com/devbridge/jQuery-Autocomplete/issues/592
