### ISSUE TITLE
onInvalidateSelection not working

### ISSUE THREAD

**Issue by slier81** [devbridge/jQuery-Autocomplete#684]
When user select the suggestion list using keyboard, then loose the focus (click outside the input), then click inside the input again the `onInvalidateSelection` work as expected.

But when user select the suggestion list using mouse, then loose the focus (click outside the input), then click inside the input again the `onInvalidateSelection` simply not working

Here is my code:

```
$(function () {
    $(document).on('focus', '.item-name', function () {
        $(this).autocomplete({
            minChars: 1,
            preventBadQueries: false,
            serviceUrl: "/ajax/inventory/goods/search",
            showNoSuggestionNotice: true,
            dataType: "json",
            onInvalidateSelection: function (suggestion) {
                console.log('on invalidate');
            },
            onSelect: function (suggestion) {
                console.log("on select");
            },
            onHide: function () {
                console.log("on hide")
            }
        });
    });

});
```

**Looks like this problem only occur if autofocus is being used with dynamically loaded element**
Is there any workaround?

**Comment by gongph** [comment]
Hi， I didn't find the above problem your said.  Here's my code:
```html
<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="demo">
        <input type="text" class="form-control" id="autocomplete"/>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>
</div>
<script src="js/jquery-3.1.0.js" type="text/javascript" charset="utf-8"></script>
<script src="assets/autocomplete/1.4.7/jquery.autocomplete.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
$(function () {
  $('#autocomplete').autocomplete({
    serviceUrl: './db.json',
    dataType: 'json',
    onSelect: function (suggestions) {
      console.log('onSelect...', suggestions);
     },
    onInvalidateSelection: function () {
      console.log('onInvalidateSelection...', this);
    }
  });
});
</script>
```
`db.json`

```json
{
    "suggestions": ["United Arab Emirates", "United Kingdom", "United States", "United Owen", "United Zssna"]
}
```

**Comment by slier81** [comment]
@gongph Hi..Your autocomplete is not on dynamically injected element

And one more, i think to reflect my issue, you have to have suggestion that have quite the same value like:

`db.json`
```
{
    "suggestions": ["User 1", "User 11", "User 12", "User 13", "User 14"]
}
```

**Comment by gongph** [comment]
I think it's nothing to do with the server data, right?

**Comment by slier81** [comment]
@gongph Nop..Dont think so.I have another input with autocomplete too..The `onInvalidateSelection` works just fine.The only differences with the one i have problem is, the input is not dynamically injected element

**Comment by gongph** [comment]
@slier81  You are right， 确实有问题。

**Comment by slier81** [comment]
@gongph so its confirm bug?

**Comment by gongph** [comment]
In fact, when the suggestion is selected by `keyup` or `keydown` , then loose the focus (click outside the input), then click inside the input again the onInvalidateSelection also not working.

**Comment by slier81** [comment]
@gongph Yep, as long u loose the focus.. the `onInvalidateSelection` simply stop working

**Comment by gongph** [comment]
@slier81  At present, I have found that there is only one way to work properly, and the steps are as follows:

1. Enter query keywords in the text box
2. Use the upper and lower keyboard to select suggestion
3. Press the confirmation key (`Enter`)
3. Change the value in the text box

This time triggers  `onInvalidateSelection ` events

**Comment by slier81** [comment]
>     1.Enter query keywords in the text box
>     2.Use the upper and lower keyboard to select suggestion
>     3.Press the confirmation key (Enter)
>     4.Change the value in the text box
@tkirda @gongph This only work if the user not loose the focus from the input..If the user loose the focus, this step will not workd

**Comment by gongph** [comment]
@slier81  Looking at the 471 lines of the source code.
```js
// `that.selection` is null when input element lose focus
// so， the code inside of  `if` will not excute
if (that.selection && that.currentValue !== query) {
   that.selection = null;
   (options.onInvalidateSelection || $.noop).call(that.element);
}
```

**Comment by slier81** [comment]
@gongph Interesting finding.. hope @tkirda can fix it

**Comment by netmou** [comment]
step 1: input some word in order to make suggestion showing
step 2: click the  outside by mouse  to make the elem lose focus
step 3：click the the input-elem ,but onInvalidateSelection do not work
so how to make sure the element's value must be one of suggestions

my way:
 change the order between the container's hide action and onselect at line 851 in file jquery.autocomplete.js
```
// implements the onHide
onHide:function(){
				var selection = $(this).autocomplete().selection;
				if(selection == null ||selection.value != $(this).val()){
					$(this).val("");
				}
			}
```

**Comment by elektronika-ba** [comment]
Problem:
When using external source of data, the `onInvalidateSelection` is called only after the data has been fetched. In situations when there is a defer timeout and use blurs before the search is executed, the `onInvalidateSelection` is never called.

Fix:
In the source code find onBlur function:

        onBlur: function () {
            var that = this;

            // If user clicked on a suggestion, hide() will
            // be canceled, otherwise close suggestions
            that.blurTimeoutId = setTimeout(function () {
                that.hide();
            }, 200);
        },

and change to:

        onBlur: function () {
            var that = this,
                options = that.options,
                value = that.el.val(),
                query = that.getQuery(value);

            // If user clicked on a suggestion, hide() will
            // be canceled, otherwise close suggestions
            that.blurTimeoutId = setTimeout(function () {
                that.hide();
                if (that.selection && that.currentValue !== query) {
                    (options.onInvalidateSelection || $.noop).call(that.element);
                }
            }, 200);
        },

It works for me.

**Comment by netmou** [comment]
i think the follow code is better for people type but do not select
```
        onBlur: function () {
            var that = this,
                options = that.options,
                value = that.el.val(),
                query = that.getQuery(value);

            // If user clicked on a suggestion, hide() will
            // be canceled, otherwise close suggestions
            that.blurTimeoutId = setTimeout(function () {
                that.hide();
              if (that.selection == null) {
                    var is_matched = false;
                    for (var index in that.suggestions) {
                        var itVal = that.getValue(that.suggestions[index].value);
                        if (itVal == query) {
                            that.onSelect(index);
                            is_matched = true;
                            break;
                        }
                    }
                    if (!is_matched) { 
                      (options.onInvalidateSelection || $.noop).call(that.element);
                    }
                } else if (that.selection && that.currentValue !== query) {
                    (options.onInvalidateSelection || $.noop).call(that.element);
                }
            }, 200);
        },
```
