### ISSUE TITLE
Can I use jQuery UI Autocomplete?

### ISSUE THREAD

**Issue by nroose** [devbridge/jQuery-Autocomplete#687]
We have devbridge autocomplete installed in our app. I want to use the regular jQuery UI autocomplete. I understand that I can refer to the devbridge autocomplete as devbridgeAutocomplete, but when I say `.autocomplete` it uses devbrige. Thanks.

**Comment by tkirda** [comment]
You have to change order of scripts, include jQuery UI after devbrdge autocomplete and you should be OK.
