### ISSUE TITLE
Inject the typed text as the first option of the results

### ISSUE THREAD

**Issue by rpbaltazar** [devbridge/jQuery-Autocomplete#688]
We have a use case where it would be useful to suggest the user that he can select what he has just typed.
From a UX point of view it seems a clearer indication.

Would such thing be possible?

I've tried updating the autocomplete suggestions and clearing the cache but results appear too fast and only after the results are being displayed my new suggestion is there.

**Comment by tkirda** [comment]
You can always modify suggestions array, you always know query before displaying the results.
