### ISSUE TITLE
Using value from one input to autocomplete another

### ISSUE THREAD

**Issue by nefilim** [devbridge/jQuery-Autocomplete#690]
Hi
I have a form with multiple line items (added dynamically), each with a manufacturer and a model, both fields are autocompleting. 
After filling in the manufacturer, I want the autocomplete query for the model to be scoped within the manufacturer, ie only return models by the chosen manufacturer. So for my autocomplete AJAX call I'd like to pass the manufacturer from the same line item along with the query. 
I can get to the value of the applicable manufacturer in the onSearchStart for instance but how can I add that to the query being sent? Is there a way to transform the query? 
Great work and thanks!

**Comment by nefilim** [comment]
It would be great if onSearchStart could transform params?

**Comment by tkirda** [comment]
You are getting `params` passed by reference inside `onSearchStart`. So any manipulations would change them.
