### ISSUE TITLE
Repeating Categories

### ISSUE THREAD

**Issue by codecreate** [devbridge/jQuery-Autocomplete#698]
Hi,

I have an issue where categories are repeated. The specific use case is for Australian Suburbs grouped by state. If you look at the suggestions where the string town is entered you can see two groups for South Australia and Queensland

`<div class="autocomplete-suggestions" style="position: absolute; max-height: 300px; z-index: 9999; top: 312.188px; left: 479.5px; width: 280px; display: none;"><div class="autocomplete-group">New South Wales</div><div class="autocomplete-suggestion" data-index="0">New<strong>town</strong> (2042)</div><div class="autocomplete-suggestion" data-index="1">Black<strong>town</strong> (2148)</div><div class="autocomplete-suggestion" data-index="2">Fiddle<strong>town</strong> (2159)</div><div class="autocomplete-suggestion" data-index="3">Banks<strong>town</strong> (2200)</div><div class="autocomplete-suggestion" data-index="4">Banks<strong>town</strong> Aerodrome (2200)</div><div class="autocomplete-suggestion" data-index="5">Davis<strong>town</strong> (2251)</div><div class="autocomplete-suggestion" data-index="6">Adams<strong>town</strong> (2289)</div><div class="autocomplete-suggestion" data-index="7">Adams<strong>town</strong> Heights (2289)</div><div class="autocomplete-suggestion" data-index="8">Charles<strong>town</strong> (2290)</div><div class="autocomplete-suggestion" data-index="9">George<strong>town</strong> (2298)</div><div class="autocomplete-suggestion" data-index="10">William<strong>town</strong> (2318)</div><div class="autocomplete-suggestion" data-index="11">Clarence <strong>Town</strong> (2321)</div><div class="autocomplete-suggestion" data-index="12">Cundle<strong>town</strong> (2430)</div><div class="autocomplete-suggestion" data-index="13">Smith-<strong>Town</strong> (2440)</div><div class="autocomplete-suggestion" data-index="14">Smith<strong>town</strong> (2440)</div><div class="autocomplete-suggestion" data-index="15">Of Cooma <strong>Town</strong> (2630)</div><div class="autocomplete-suggestion" data-index="16">Alfred<strong>town</strong> (2650)</div><div class="autocomplete-suggestion" data-index="17">Jamison<strong>town</strong> (2750)</div><div class="autocomplete-suggestion" data-index="18">Pitt <strong>Town</strong> (2756)</div><div class="autocomplete-suggestion" data-index="19">Corney <strong>Town</strong> (2790)</div><div class="autocomplete-group">Victoria</div><div class="autocomplete-suggestion" data-index="20">Williams<strong>town</strong> (3016)</div><div class="autocomplete-suggestion" data-index="21">Williams<strong>town</strong> North (3016)</div><div class="autocomplete-suggestion" data-index="22">Thomas<strong>town</strong> (3074)</div><div class="autocomplete-suggestion" data-index="23">New<strong>town</strong> (3220)</div><div class="autocomplete-suggestion" data-index="24">Violet <strong>Town</strong> (3669)</div><div class="autocomplete-group">Queensland</div><div class="autocomplete-suggestion" data-index="25">New<strong>town</strong> (4305)</div><div class="autocomplete-suggestion" data-index="26">Allens<strong>town</strong> (4700)</div><div class="autocomplete-suggestion" data-index="27">South <strong>Town</strong>sville (4810)</div><div class="autocomplete-suggestion" data-index="28"><strong>Town</strong> Common (4810)</div><div class="autocomplete-suggestion" data-index="29"><strong>Town</strong>view (4825)</div><div class="autocomplete-suggestion" data-index="30">Burke<strong>town</strong> (4830)</div><div class="autocomplete-suggestion" data-index="31">George<strong>town</strong> (4871)</div><div class="autocomplete-suggestion" data-index="32">Cook<strong>town</strong> (4895)</div><div class="autocomplete-group">South Australia</div><div class="autocomplete-suggestion" data-index="33">Queens<strong>town</strong> (5014)</div><div class="autocomplete-suggestion" data-index="34">Edwards<strong>town</strong> (5039)</div><div class="autocomplete-suggestion" data-index="35">Kent <strong>Town</strong> (5067)</div><div class="autocomplete-suggestion" data-index="36">Summer<strong>town</strong> (5141)</div><div class="autocomplete-suggestion" data-index="37">Border<strong>town</strong> (5268)</div><div class="autocomplete-suggestion" data-index="38">Williams<strong>town</strong> (5351)</div><div class="autocomplete-suggestion" data-index="39">Blanche<strong>town</strong> (5357)</div><div class="autocomplete-suggestion" data-index="40">James<strong>town</strong> (5491)</div><div class="autocomplete-suggestion" data-index="41">Snow<strong>town</strong> (5520)</div><div class="autocomplete-suggestion" data-index="42">Solomon<strong>town</strong> (5540)</div><div class="autocomplete-suggestion" data-index="43">Yorke<strong>town</strong> (5576)</div><div class="autocomplete-group">Western Australia</div><div class="autocomplete-suggestion" data-index="44">Kwinana <strong>Town</strong> Centre (6167)</div><div class="autocomplete-suggestion" data-index="45">Bridge<strong>town</strong> (6255)</div><div class="autocomplete-suggestion" data-index="46">Williams<strong>town</strong> (6430)</div><div class="autocomplete-suggestion" data-index="47">Castle<strong>town</strong> (6450)</div><div class="autocomplete-suggestion" data-index="48">Morgan<strong>town</strong> (6701)</div><div class="autocomplete-group">Tasmania</div><div class="autocomplete-suggestion" data-index="49">New <strong>Town</strong> (7009)</div><div class="autocomplete-suggestion" data-index="50">Campbell <strong>Town</strong> (7210)</div><div class="autocomplete-suggestion" data-index="51">Young<strong>town</strong> (7249)</div><div class="autocomplete-suggestion" data-index="52">George <strong>Town</strong> (7253)</div><div class="autocomplete-suggestion" data-index="53">Queens<strong>town</strong> (7467)</div><div class="autocomplete-group">South Australia</div><div class="autocomplete-suggestion" data-index="54">Campbell<strong>town</strong> (5074)</div><div class="autocomplete-suggestion" data-index="55">Murray <strong>Town</strong> (5481)</div><div class="autocomplete-group">Queensland</div><div class="autocomplete-suggestion" data-index="56"><strong>Town</strong>sville (4810)</div></div>`

**Comment by singhofmarco** [comment]
Having the same issue.

**Comment by thetuningspoon** [comment]
Same issue here

**Comment by tkirda** [comment]
Can not comment without knowing the input data.

**Comment by thetuningspoon** [comment]
{"suggestions":[{"value":"100383: Cubicle1 PC Not Able To Update To Latest Version Of Windows","data":{"id":"100383","category":"Active"}},{"value":"101598: Add button on Testimonials page to scroll down to form","data":{"id":"101598","category":"Complete"}},{"value":"69424: Confirm computers are updated with the latest Windows updates & patches","data":{"id":"69424","category":"Active"}},{"value":"98360: Testing is requiring larger server instance","data":{"id":"98360","category":"Complete"}},{"value":"92420: Perform test restore from backup","data":{"id":"92420","category":"Complete"}},{"value":"98424: CMR: Perform test restore from backup","data":{"id":"98424","category":"Active"}},{"value":"92217: Check Server, ESXi, & Install latest Practice Partner Updates - July 2019","data":{"id":"92217","category":"Complete"}},{"value":"97465: Check Server, ESXi, & Install latest Practice Partner Updates","data":{"id":"97465","category":"Active"}},{"value":"54915: Migrate from Aerohive HMOL Classic to new HMOL NG Connect platform and upgrade access point firmware to latest version","data":{"id":"54915","category":"Complete"}},{"value":"88420: Perform test restore from backup","data":{"id":"88420","category":"Complete"}}]}
