### ISSUE TITLE
Please, I have an object set and would like to retrieve it in the onSelect

### ISSUE THREAD

**Issue by tosipaulo** [devbridge/jQuery-Autocomplete#707]
Please, I have an object set and would like to retrieve it in the onSelect click callback all my property. Is it possible to put an object set in the lookup option? How can I recover all my properties?

 

Thank you

 

`

const countries = [

        {

            value: 'Chicago Blackhawks',

            _id: "xxxx",

            data: '2018-04-11',

            data: { category: 'NHL' }

        },

        {

            value: 'teste01',

            _id: "xxxx",

            data: '2018-04-11',

            data: { category: 'NHL' }

        },

        {

            value: 'ppppppbul',

            _id: "xxxx",

            data: '2018-04-11',

            data: { category: 'NBA' }

        },

        {

            value: 'Chicago Bulls',

            _id: "xxxx",

            data: '2018-04-11',

            data: { category: 'NBA' }

        }

    ];

 

$('#autocomplete').autocomplete({

        minChars: 3,

        lookup: countries,

        groupBy: 'category',

        onSelect: function (suggestion) {

           /* Here I need to recover all my property from the selected */

        }

    });

`

**Comment by Rajiii4u** [comment]
transformResult: function (rt, qy) {
            return {suggestions: jQuery.map(rt, function (it) {
                    return {value: it.value, data: it.data};
                })};
        },
        onSelect: function (rt) {
            alert(rt.link);
        }
u can use like this with transform result

**Comment by tosipaulo** [comment]
Thank you very much, mine is working without needing the transformResult option.
`onSelect: function (suggestion) { console.log(suggestion) }
`

return is: ` Object {value: "Chicago Blackhawks", _id: "xxxx", date: "2018-04-11", data: Object}`

Thank you very much!!!
