### ISSUE TITLE
replace text with wordpress title

### ISSUE THREAD

**Issue by d00nn1** [devbridge/jQuery-Autocomplete#716]
i am traying to find information or to meak  load  post title for sugest but find nothing in  this way 
in this link down is a autocomplete like this but its slower but the point is thets load the data from post and page wordpress
https://gist.github.com/jaredatch/79e57c68438841b6c09b3ad4c12600f6

pleas help me if you can 
my momental sugest ar loading from a special file  example.js
var countries = {
"example1": "example1",
"example2": "example2",
"example3": "example3"
}

only to load text from post and page 

sory for my english is not so good

**Comment by tkirda** [comment]
This is place for issues with the plugin. For help or programming questions use [stackoverflow.com](https://stackoverflow.com/)
