### ISSUE TITLE
autocomplete='nope' doesn't work

### ISSUE THREAD

**Issue by fschiettecatte** [devbridge/jQuery-Autocomplete#729]
The [1.4.8 release](https://github.com/devbridge/jQuery-Autocomplete/releases/tag/v1.4.8) broke turning off 'autocomplete' on fields, [the 'off' was replaced by 'nope'] (https://github.com/devbridge/jQuery-Autocomplete/commit/fc5cdb93b82130fe69dcf3b6d4647451c7e8fc99) as recommended by 
[https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion), but this does not work on the current releases of Chrome (68.0.3440.106 on Mac) and Firefox (61.0.2 on Mac). Setting it back to 'off' on both works.

**Comment by BlingPiece** [comment]
Got the same problem

**Comment by tkirda** [comment]
I think will have to revert to official autocomplete="off". You can also set this attribute yourself after initializing autocomplete, until it is updated.

**Comment by tkirda** [comment]
It was already changed in https://github.com/devbridge/jQuery-Autocomplete/commit/fc5cdb93b82130fe69dcf3b6d4647451c7e8fc99, just published latest version on NPM.
