### ISSUE TITLE
OnSelect fires up automatically

### ISSUE THREAD

**Issue by edwvee** [devbridge/jQuery-Autocomplete#735]
Got a problem when there is a string in a field initialized with this plugin. If this string matches only one suggestion OnSelect fires up when you click on the field. Somehow plugin thinks that result is selected when suggestions (only one that case) are loaded.

**Comment by edwvee** [comment]
Or even when you paste string in the field, when there would be only one suggestion, OnSelect fires up.

**Comment by edwvee** [comment]
triggerSelectOnValidInput: false helped

**Comment by hmzlam** [comment]
thanks
