### ISSUE TITLE
Tracking infested demo site doesn't allow to see it in action without getting your privacy raped

### ISSUE THREAD

**Issue by AdrianVerde** [devbridge/jQuery-Autocomplete#737]
The demo website won't work because it tries to track users heavily making user-protecting extensions like uBlock Origin block it.
Maybe the website could be more respectful with the privacy of individuals who want to check how it works.
https://www.devbridge.com/sourcery/components/jquery-autocomplete/

**Comment by renegadeofunk** [comment]
Wow. Highly uncool.

**Comment by tkirda** [comment]
You can see demo here: https://devbridge.github.io/jQuery-Autocomplete/
