### ISSUE TITLE
result is dissapearing

### ISSUE THREAD

**Issue by AaronDasani** [devbridge/jQuery-Autocomplete#740]
Hey guys,

I been trying to use your jQuery-autocomplete, but I am stuck and would like some advise...
So when I am searching a list of users, I am able to get the info but the result is not being display in the screen. The result seem to appear in the screen but disappear immediately. it is like a flicker !!

What can cause that problem???? Any insight would be appreciated :)

**Comment by tkirda** [comment]
No idea what wrong based on information you provided.
