### ISSUE TITLE
it will auto change to toLowerCase()

### ISSUE THREAD

**Issue by shuhankuang** [devbridge/jQuery-Autocomplete#743]
when I set serverUrl, then I paste the url 'https://www.youtube.com/watch?v=xYtsL9znopI',
the input will auto change to lower case. how can I dissable the feature.

https://www.youtube.com/watch?v=xYtsL9znopI
to 
https://www.youtube.com/watch?v=xytsl9znopi

**Comment by tkirda** [comment]
Plugin is not changing values to lowercase. There is something else that you may be using.

**Comment by shuhankuang** [comment]
@tkirda 

here is an example.

https://jsfiddle.net/shuhankuang/xpvt214o/992236/

you can paste to the input element.

https://www.youtube.com/watch?v=xYtsL9znopI

it will change to lowercase.
