### ISSUE TITLE
it will auto change to toLowerCase() 

### ISSUE THREAD

**Issue by shuhankuang** [devbridge/jQuery-Autocomplete#744]
here is an example.

https://jsfiddle.net/shuhankuang/xpvt214o/992236/

you can paste to the input element.

https://www.youtube.com/watch?v=xYtsL9znopI

it will change to lowercase.

_Originally posted by @shuhankuang in https://github.com/devbridge/jQuery-Autocomplete/issues/743#issuecomment-446039200_

**Comment by tkirda** [comment]
It is because suggestions are coming in lowercase. So it will just take suggested item that is returned from the server.

You can inspect suggestion results in network panel.
