### ISSUE TITLE
throttle requests?

### ISSUE THREAD

**Issue by Adam-78** [devbridge/jQuery-Autocomplete#758]
Is there a way to throttle requests?

I was thinking of using the _throttle() function from underscore.js (https://underscorejs.org/#throttle)
but not sure how I can call it from my settings.

My settings are as follows:

     window.locationAutoCompleteSettings = {
        serviceUrl: "/location-lookup",
        minChars: 2,
        paramName: "term",
        showNoSuggestionNotice: false,
        onSearchStart: function (query) {
            $(this).closest(".js-clear-input").find(".js-clear-input-trigger").addClass("clear-input-spinner")
        },
    };

**Comment by tkirda** [comment]
It currently works like lodash debounce. There is no way to change the behavior without modifying source code.
