### ISSUE TITLE
How to add more items to suggestion list after control is initiliazed

### ISSUE THREAD

**Issue by mattmyers789** [devbridge/jQuery-Autocomplete#761]
Hi,

I'm sorry if this has already been answered somewhere.  Is it possible to initialize an input with an array of local data (just like the 'countries' example in the documentation) and then later on ADD an additional item to the suggestion list?

Thanks!

**Comment by tkirda** [comment]
You can user `setOptions` to update lookup array.

```javascript
$('#autocomplete').autocomplete().setOptions({
  lookup: [ /* updated lookup array */ ]
});
```

**Comment by mattmyers789** [comment]
Hi Tomas,

Does this replace the ENTIRE suggestion list array?  I was looking for a way to update just a single item in the array?  Or append a single new item to the array?

Would the approach be that you 'get' a copy of the entire array, store it locally, make adjustments to the array, and then update the entire updated/modified array back to control?

Thanks

Matt
