### ISSUE TITLE
error suggestion.value is undefined

### ISSUE THREAD

**Issue by migliori** [devbridge/jQuery-Autocomplete#762]
Hi,

Thanks for your great & useful plugin.

In the documentation you say 

> Alternatively, if there is no data you can supply just a string array for suggestions

But this currently doesn't work: several functions are using suggestion.value and throw an error if the suggestions are not in the default format with value & data.

**Comment by tkirda** [comment]
If you provide array of string values it is converted into the default format. It is just for convenience.
