### ISSUE TITLE
error suggestion.value is undefined (again, sorry)

### ISSUE THREAD

**Issue by migliori** [devbridge/jQuery-Autocomplete#764]
You closed my previous issue but I guess you didn't test: when I say it throws an error it means that it really doesn't work.

Don't mark "solved" what is not.

Anyway, I used the default format to get rid of this, and just opened the issue to let you know that your script has a problem.

**Comment by tkirda** [comment]
You can still comment on closed issue. Also when reporting issue please provide code to reproduce it.

Conversion is done here: https://github.com/devbridge/jQuery-Autocomplete/blob/master/src/jquery.autocomplete.js#L261
