### ISSUE TITLE
appendTo don't shows results list anymore

### ISSUE THREAD

**Issue by Johnny99211** [devbridge/jQuery-Autocomplete#765]
I've a problem with the `appendTo` parameter. This is my code:

```
let searchInput = jQuery( 'input[type=search]' );
searchInput.devbridgeAutocomplete( {
    serviceUrl: "my-results.php?action=search_autocomplete",
    minLength: 3,
    appendTo: searchInput.parent()
} );
```

I need to use this parameter to append the results list to the parent because the sizing within the body changes on scroll. In this case the autocomplete list will be change the position too. 

Sadly, when I use this appendTo parameter, the result list seems to be gone when I start typing. I've added a relative position to the parent but still no results. This is the DOM after using appendTo:

```
<form role="search" method="get" class="search-form" action="my-page.de">
    <input type="search" placeholder="" name="s" autocomplete="off">
    <div class="autocomplete-suggestions" style="position: absolute; display: none;"></div>
    <div class="autocomplete-suggestions" style="position: absolute; display: none;"></div>
</form>
```

I've absolutely no idea why it's not working. I've also tried to use the force position parameter but still no result list. Maybe I'm doing something wrong?

**Comment by tkirda** [comment]
I suggest you add container under input:
```html
<form role="search" method="get" class="search-form" action="my-page.de">
    <input type="search" placeholder="" name="s" autocomplete="off">
    <div class="suggestions" style="position: relative;"></div>
</form>
```
And then:
```javascript
let searchInput = jQuery( 'input[type=search]' );
searchInput.devbridgeAutocomplete( {
    serviceUrl: "my-results.php?action=search_autocomplete",
    minLength: 3,
    appendTo: jQuery('.suggestions')
} );
```

**Comment by Johnny99211** [comment]
It worked without using jQuery at the appendTo. I've used now `#search-form` and added this as an id to the form. Now it works. Maybe a bug?

**Comment by tkirda** [comment]
I don't think this is a bug. It's something with your setup.
