### ISSUE TITLE
missing tag for v1.4.10

### ISSUE THREAD

**Issue by jrochkind** [devbridge/jQuery-Autocomplete#768]
There are tags in the repo for most releases, up to [v1.4.9](https://github.com/devbridge/jQuery-Autocomplete/tree/v1.4.9). 

However there is no tag for the latest release to github, `v1.4.10`. 

Tags in the repo make it easier for developers to see for sure what changes exist between versions. I am not sure if you have an automated build/release process that normally tags in github, but failed in this case?

Commit 43b2953ab7c is the one that changed versions in various manifest files to `1.4.10`. And it looks like... [that commit is actually current master](https://github.com/devbridge/jQuery-Autocomplete/compare/43b2953ab7ca5cb372d2463851b0c502dbe702da...master)?

So tagging current master v1.4.10 might be a quick rescue?

I am generally unsure of the current maintenance status of this project. It seems to have slowed down, but on the other hand v1.4.10 was released only last February not too long ago, and there is maintainer activity on the GH issues, so it still seems to be alive?

**Comment by tkirda** [comment]
It was tagged, just did not include tags when pushing. It's up to date now.

**Comment by jrochkind** [comment]
Thanks!
