### ISSUE TITLE
disable suggest onFocus?

### ISSUE THREAD

**Issue by jrochkind** [devbridge/jQuery-Autocomplete#769]
I kind of want to disable suggest onFocus. 

For instance, right now, if I load HTML with an input with a `value` attribute already, and have the autocomplete attached to it: The first time the user clicks in there they'll get suggestions (for the thing that was already entered). 

For my use case, I don't want that, I don't really want suggestions unless they change the text. 

Right now, if they enter some new text, and choose something from a suggestion, and then go focus somewhere else and come back to focus -- the suggestions don't show up again, cause there's something smart in the onFocus code. 

But if they enter some new text and _don't_ choose from the suggestions, and go focus somewhere else and then focus back -- they get suggestions. In my use case, they are allowed to choose things other than suggestions, I don't really want suggestions to show up again on focus, when they haven't changed their input. 

For my needs, I hacked this out by doing `$("selector").autocomplete().onFocus = function() {};`

But I realize this is kind of reaching into non-public API hack, and not a great way to do it. (On the other hand, it doesn't look like the code in devbridge-autocomplete changes much lately, so this kind of hack probably won't break for the foreseeable future!). 

Would it make sense  to have some kind of configuration to turn off the onFocus suggestions entirely?

### As an aside: This project?

I spent quite a while looking around for a Javascript autocomplete component that would meet my needs, that was not React/Vue/Angular/etc.  And that was open source (ideally on github) and didn't seem to have been _entirely_ abandoned by its maintainers. And ideally with code i could read/understand. With jquery dependency or without, I'd take either one. 

This was the best I found!

But it's not clear to me what it's current maintenance status or prospects are. Am I annoying you by filing feature requests, is this project basically just on life support and not looking for new features? I can stop! (And consider forking for my own use, although I'd try to avoid it). 

Otherwise, I am ready and able to file pull requests for the feature(s) I'm asking for (and have one or two more I could ask for too). 

But I don't want to spend time doing that if they are likely to languish! And in an ideal world, first get some feedback on best way to implement things when I can think of several ways, but if that's impossible just getting feedback that a feature I'm asking for actually could get reviewed/merged/new-version-released if my code is okay, would be enough motivation to do it!

**Comment by tkirda** [comment]
Hi @jrochkind, this project is in maintenance mode. If there are PR's that resolve actual bug, I usually review and merge those. However not planing to add any new features.

You approach overriding onFocus is fine if you really don't need it.

**Comment by jrochkind** [comment]
OK, thanks!

Recommend adding that info to README (that it is getting maintenance for bugs, but not interested in new features). 

I will close this Issue, and not file additional feature requests!

(Although a release with the recent bugfix PR would be appreciated!)

What I'm really doing in my thing is having a list of things in the suggestions, where when you click on one, something _else_ (taken from data) gets put into the text field, not the exact text that was in the suggestion. 

I find this really confuses the jquery-autosuggest plugin, it's got a lot of code for tracking "Did the entry in the text box really change? do we really need to show new suggestions?", that assumes the string of the suggestion you click in is identical to the string in the text input.  And doesn't really like it -- as far as keeping track of "has the text changed needing suggestions" --  when you set `preserveInput: true` but then go ahead and manually set the value of the text input. 

I have it kind of sort of mostly working with the right combination of options and hacks. 

It sounds like if I wanted to improve this situation further, I would and could just fork your code, because feature changes like that aren't gonna happen here. OK, thanks!
