### ISSUE TITLE
Your demo isn't working...

### ISSUE THREAD

**Issue by adamthedeveloper** [devbridge/jQuery-Autocomplete#771]
https://www.devbridge.com/sourcery/components/jquery-autocomplete/

A non-working demo is a bad look ;)

**Comment by tkirda** [comment]
Works for me.

**Comment by adamthedeveloper** [comment]
Still not for me - Chrome v 76.0.3809.132
Attached "France" as a search term and the errors displayed in console.
![Screen Shot 2019-09-19 at 12 54 09 PM](https://user-images.githubusercontent.com/159400/65276540-ca1bf180-dadc-11e9-8c66-32746f680823.png)

**Comment by adamthedeveloper** [comment]
I tried through an incognito window and it worked. Not sure what's happening. Feel free to keep it closed if you aren't worried.

**Comment by tkirda** [comment]
There may be other scripts that are causing the issue. There is no issue with a plugin itself.

You can run demo locally by opening `index.htm` file in your browser.

**Comment by adamthedeveloper** [comment]
I know it works. I've implemented it. I just wanted to raise the possibility that the demo may not be working for everyone. Thanks!

**Comment by Jendoliver** [comment]
It happened to me as well although it's pretty random, looks like sometimes the element of class `.js-academy-slider` is not loading properly and the `.slick` call fails (so as @tkirda says it's not an error from the plugin). In my case it appeared the first time, refreshing got it away and after some more refreshes it reappeared...

![image](https://user-images.githubusercontent.com/23485344/65311529-cf3a7880-db90-11e9-9881-9e2334b09977.png)

**Comment by adamthedeveloper** [comment]
Yeah. The demo isn't working. Library is ok. I personally almost passed on
trying the library because the demo didn't run. The team isn't concerned so
- that's that.

**Comment by tkirda** [comment]
Issue on the demo page involving other scripts was resolved.
