### ISSUE TITLE
why not is `this.data` on here ? 

### ISSUE THREAD

**Issue by Jamlee** [devbridge/jQuery-Autocomplete#774]
i really need something like `label`, so i use value instead.

https://github.com/devbridge/jQuery-Autocomplete/blob/0ba256501bc365814f43066999f51f0619e739a9/src/jquery.autocomplete.js#L875

response like below:
```

{
    "query": "Unit",
    "suggestions": [
		{"value": "<span class=\"s-content\">nginx</span><span class=\"s-info\">[07/15 12:13 - 20M]</span>", "data": "nginx"},
		{"value": "<span class=\"s-content\">index.rancher.cc/library/mongo:3</span><span class=\"s-info\">[07/15 12:13 - 200M]</span>", "data": "index.rancher.cc/library/mongo:3"},
		{"value": "<span class=\"s-content\">index.rancher.cc/library/java:3</span><span class=\"s-info\">[07/15 12:13 - 250M]</span>", "data": "index.rancher.cc/library/java:3"},
		{"value": "<span class=\"s-content\">index.rancher.cc/library/nginx:3</span><span class=\"s-info\">[07/15 12:13 - 30M]</span>", "data": "index.rancher.cc/library/nginx:3"}
    ]
}
```

when i use arrow up and arrow down:

![image](https://user-images.githubusercontent.com/5196641/66905163-ea859000-f037-11e9-954f-2fa3971a0ec1.png)

finally, i disable the moveUp and moveDown:

                        $.Autocomplete.prototype.moveUp = function(){};
                        $.Autocomplete.prototype.moveDown = function(){};

**Comment by tkirda** [comment]
Set `preserveInput` to `true` when initializing autocomplete.
