### ISSUE TITLE
Autocomplete's menu items mouseover behavior

### ISSUE THREAD

**Issue by vikramdadwal** [devbridge/jQuery-Autocomplete#776]
The Autocomplete behavior shouldn't change the input text on mouseover/hover. It's too obtrusive.

"If my mouse pointer happens to be positioned where the menu will be shown and it happen to focus an item, and when user press enter it actually select that focused item. This should not be the default behaviors and there should be an option to override."

**Comment by tkirda** [comment]
Set option `preserveInput` to `true`, it will not change input on hover.

**Comment by vikramdadwal** [comment]
@tkirda : Still not working. Here are the settings:


```
orientation: 'auto',
minChars: 4,
maxHeight: 200,
forceFixPosition: false,
preserveInput: true
```
