### ISSUE TITLE
[Bug] onSelect with ajax

### ISSUE THREAD

**Issue by prusmarcin** [devbridge/jQuery-Autocomplete#778]
In the onSelect event, I want to insert the content of the  suggestion.data variable into input by method append() jquery but as variable is inserted suggestion.value. If I comment on all the code in onSelect event then it will still be injected into the input from variable suggestion.value.
Please look at the configuration:

```javascript
$('#schemat').autocompleteMedical({
    minChars: 3,
    width: 'flex',
    type: 'GET',
    delimiter: ';',
    paramName: 'pat',
    serviceUrl: 'inc/autocomplete/icd10.php?pesel='+$('#id_pd_pid').val(),
    transformResult: function(response) {
        return {
            suggestions: $.map(jQuery.parseJSON(response), function(item) {
                return { value: item.k + ' ' + item.o, data: item.k};
            })
        };
    },
    onSelect: function (suggestion) {
        $('#schemat').append(suggestion.data);
        $('#schemat').addClass('is-valid');
    }
});
```

I think there are several ways to fix this.
The first example is to display suggestions from variable data instead value or modify the onClick event so that it doesn't perform too many operations in the background.
The error may be in the display of suggestions because the search works correctly based on the data but displays only content of suggestion based on the value variable. Example: [{"value":"1", "Car"}]
If I enter chars "Ca" in the input field then will show a suggest with option "1" but should be displayed "Car" and then onClick event will insert "1" to input field. 
Only on append() jquery can you see this error.

Thanks for your help.

**Comment by tkirda** [comment]
Try setting `preserveInput` option to `true`.

**Comment by prusmarcin** [comment]
I tested with the option set as: preserveInput: true but then the search works a little differently. Entering the characters "Ca" as I choose, the word "Car" will be left to me and it should insert "1". By typing the word "Ca" as I choose "Car" suggestions, I get Car into the input. Should insert the value "1".
I m using delimiter: ';' and for this purpose I do not want to erase the previous value from the input. That's why I don't want to use input val().
Thanks for your help.

**Comment by tkirda** [comment]
Try, this if you want to manage input values yourself:

```javascript
var input = $('#schemat');

input .val(input.val() + '; ' + suggestion.data);
```

**Comment by prusmarcin** [comment]
I also tested it. The problem is that it puts from suggestion.value. In the onSelect event I have no influence on it because I always insert. Something in the background except onSelect inserts suggestion.value to my input. If we use alert('test') in the first line for onSelect event then we can see that first inserts is suggestion.data, second insert to input suggestion.value. Therefore, this cannot be seen on input val() only on the input append() and I don't know how to handle this 1 insert that takes place outside of onSelect.
