### ISSUE TITLE
appendTo option made top and left style disappear

### ISSUE THREAD

**Issue by huongvu2312** [devbridge/jQuery-Autocomplete#781]
I applied autocomplete function in an input in bootstrap modal form and used `appendTo` to fix the scrolling issue. However, the div `autocomplete-suggestions`'s location didn't align with input.
Below is the code:
```html
<div class="input text autocomplete">
    <label for="softwareList">Artikel</label>
    <input type="text" name="artikel_input" id="softwareList">
</div>
```
```javascript
$('#softwareList').autocomplete({
    serviceUrl: current_url + '/softwareList',
    appendTo: $('#softwareList').parent()
});
```
and issue screenshot:
![1](https://user-images.githubusercontent.com/37365828/71315954-3e618a80-2468-11ea-98a5-6185778667eb.png)

Notice how top and left styles were missing from the code.

After some reading, I found out that by commenting out the section:
```javascript
if (containerParent !== document.body && !that.options.forceFixPosition) {
    return;
}
```
in jquery.autocomplete.js, the alignment fitted perfectly like normal.

I just want to know if this will create unnecessary problems in the future.

**Comment by tkirda** [comment]
When you specify `appendTo` option, suggestion are appended as children of that container. I suggest adding and positioning container where you want suggestions to be rendered:

```html
<div class="input text autocomplete">
    <label for="softwareList">Artikel</label>
    <input type="text" name="artikel_input" id="softwareList">
    <div id="suggestions" style="postion: relative; margin-left: 100px;"></div>
</div>
```

```javascript
$('#softwareList').autocomplete({
    serviceUrl: current_url + '/softwareList',
    appendTo: $('#suggestions')
});
```
