### ISSUE TITLE
Fire onSelect when input lose focus

### ISSUE THREAD

**Issue by hibinoh** [devbridge/jQuery-Autocomplete#787]
Currently when a user typed few chars in the input box and clicked away using mouse, the chars will be remain in the input box but the onSelect will not be fired(user tab away will fire the onSelect). 

I am wondering if there is anyway to call the onSelect when the input lose focus?
 - If there is any suggestions, automatically select the first one
 - if no selections then clear the input box instead of leaving the chars in the input box. 

Thank you

**Comment by tkirda** [comment]
You can listen to onBlur event and then add custom logic by interacting with autocomplete instance attached to input. All available methods are listed in documentation.

May try calling `onValueChange` method. However, do you know what is preventing suggestions to be displayed?

**Comment by hibinoh** [comment]
Thanks for the reply. 

The suggestions displays fine. But when the input field lose focus the suggestions will hide and leave the characters in the input field. For example, user typed 'ab', the suggestion shows 'aba, abb, abc, abd'. If user hit Enter or Tab, the Autocomplete will select the first suggestion 'aba' and insert into input field. But if user use mouse click another input field or button etc, the suggestions will hide and leave the 'ab' in the input field.

I was trying to call the onSelect in the documented onHide event function setting, but it seems the onSelect will also call onHide so it creates a loop that never ends. I'll try to create a onBlur event on the input field and see if I can have it solved. Thank you.

**Comment by tkirda** [comment]
You may try to call `onSelect(0)` inside `onHide`, just before calling it need to check if suggestions array is not empty:

```js
onHide: () => {
  if(autocomplete.suggestions.length) {
    automcomplete.onSelect(0);
  }
}
```

**Comment by hibinoh** [comment]
Thank you very much! This actually worked! 

BTW, currently I am using $(this).autocomplete() or $('#input_id').autocomplete() to get the autocomplete object inside onHide/onSelect/onSearchComplete events, I am wondering is there a shortcut to refer to the autocomplete object inside the events?

**Comment by tkirda** [comment]
There is no way to get instance inside the event. You are doing it right.

**Comment by hibinoh** [comment]
Thanks again :-)
