### ISSUE TITLE
onFocus should respect disabled changes didnt make it into /dist

### ISSUE THREAD

**Issue by drownload** [devbridge/jQuery-Autocomplete#789]
These lines of code are NOT in the /dist files

            if (that.disabled) {
                return;
            }

https://drive.google.com/file/d/1NdfW-ZszaEgYbDDofWcahTcO2iIh4S47/view?usp=sharing

**Comment by tkirda** [comment]
Looks like in dist `this` is mapped to a variable:
```js
var b=this;if(!b.disabled){...}
```

**Comment by tkirda** [comment]
You were right, it was missing latest changes. Just published patched version.
