### ISSUE TITLE
replace is not a function

### ISSUE THREAD

**Issue by rohit-web** [devbridge/jQuery-Autocomplete#790]
Hi Team,
getting a replace is not a function also toLowerCase. Please find attached screenshot.
SourceCode - 
``
$('#autocomplete').autocomplete({
            serviceUrl: '/search',            
            onSelect: function (suggestion) {
                alert('You selected: ' + suggestion.value + ', ' + suggestion.data);
            }
        });
``
Remote Response -
``
 {"suggestions":[{"value":3,"data":"test 1"},{"value":4,"data":"test 4"},{"value":5,"data":"test 5"}]}
``

![autocomplete-error](https://user-images.githubusercontent.com/16443285/80703051-b10e0100-8aff-11ea-8de2-68e91d21a88e.png)

**Comment by tkirda** [comment]
Hi, I suspect because `value` data type is number, must be string. Instead:
```
{"value":3,"data":"test 1"}
```
try:
```
{"value":"3","data":"test 1"}
```
