### ISSUE TITLE
Broken when using serviceUrl over local file lookup? Does not filter at all?

### ISSUE THREAD

**Issue by crazyserb** [devbridge/jQuery-Autocomplete#791]
Weird, but if I use the exact same data locally, within the code, as in the given example with countries and lookup: countries, this works fine.

The minute I change that to serviceUrl and remote call, same data comes through, but the script does no filtering whatsoever - no matter what I type in it just returns all the results as suggestions, regardless if they fit the search criteria or not.

What/why?!

Any ideas?

**Comment by tkirda** [comment]
When you use serviceUrl, then service endpoint should be filtering the data. 

This is by design and targeted to be used with large data sets where it does not make sense to send all data to the client.
