### ISSUE TITLE
How do I bind this to multiple input fields with the same class name?

### ISSUE THREAD

**Issue by crazyserb** [devbridge/jQuery-Autocomplete#792]
I see you bind it to an element with the ID #autocomplete, but if I try to bind it to more than one input field with the same class name (say ".autocomp" for example), it doesn't work at all. 

What am I missing?

Is this even possible, and how?

**Comment by tkirda** [comment]
This should be working. If you look at the source it is creating instance for each matched element:

https://github.com/devbridge/jQuery-Autocomplete/blob/9b30e414dd8b87e1831f9f28870b88d646f3553c/src/jquery.autocomplete.js#L977

**Comment by crazyserb** [comment]
It *should be*, but it's not... anyone tested it on their end?

If I bind it to multiple IDs, like this, it works:

`$('#autocomplete1, #autocomplete2, #autocomplete3').autocomplete({...`

But if I try and bind it to an unspecified number of input fields/elements (as some of the sections have variable number of these fields, and it's impossible to get the exact number and IDs for each) like this, none of them work:

`$('.autocomp').autocomplete({...`

**Comment by tkirda** [comment]
It should work unless you have overlooked something on your end.
