### ISSUE TITLE
Delay time to call

### ISSUE THREAD

**Issue by renatossa** [devbridge/jQuery-Autocomplete#795]
Hy,

I would to know if exists any possible to call the ajax call after any seconds... something like a paramater called "delay".

Thank you

**Comment by IraNostraEst** [comment]
Hey, 

yes there is! 

deferRequestBy | 0 | Number of miliseconds to defer Ajax request

**Comment by top-master** [comment]
I suggest to at least add the word "delay" in the description of "deferRequestBy".

For example, I was just about to install "JQuery UI" instead of this repo's script (because that has delay support), but found this issue-thread here.
