### ISSUE TITLE
Default result list

### ISSUE THREAD

**Issue by sukiyanen85** [devbridge/jQuery-Autocomplete#796]
I have an autocomplete input, and I want to show the user a default list of results when he click on the icon 

![image](https://user-images.githubusercontent.com/39272982/84136696-922a5500-aa43-11ea-818b-44de4ffa8300.png)

Can't seem to find out how to achieve this through the documentation, any one have an idea?

**Comment by sukiyanen85** [comment]
Thank you for taking the time to reply, this is my code at the moment:

```javascript
const instance = $('#from').autocomplete({
        serviceUrl: '/autocomplete'
    });

    $('.autocomplete_location').click(function(){
        if(! $('#from').val().length){
            instance.suggestions = [];
            instance.suggest();
        }
    });
```

When I click on the icon, it shows the following error on the console

```
Uncaught TypeError: instance.suggest is not a function
```

**Comment by tkirda** [comment]
To get instance you need to call `autocomplete()` without parameters. Otherwise it returns jQuery object.
