### ISSUE TITLE
ajaxSettings doesn't change Request Headers

### ISSUE THREAD

**Issue by agostinhodev** [devbridge/jQuery-Autocomplete#798]
Hi, folks.

I'm trying to send some personalizated `headers` in `ajaxSettings `to my endpoint in autocomplete, but this don't works fine.

```
$("#autocomplete").autocomplete({

            serviceUrl: "resources/autocomplete/autocomplete.php",

            ajaxSettings: {

                //Here is the problem

                headers:{

                    'resource': 'Autocomplete',
                    'subresource': 'execute'

                }

            },
            deferRequestBy: 350,

            type: 'GET',
            width: 'auto',
            autoSelectFirst: true,
            params: {
    
                "type": "technical",
    
            },
            minChars: 3,
            
            noCache: true,
            appendTo: $('#autocompleteShowResults'),  
           
            onSelect: function (suggestion) {
    
                mountSuggestion(suggestion.id);
                
            }
    
          
        });
```

When i inspect element on dev options, i'm getting something like this in console: 

![whatImGetting](https://user-images.githubusercontent.com/45676811/86065659-93e5a800-ba46-11ea-8d27-89297e4beca3.png)

However, i need to send something like this: 

![whatINeedToSend](https://user-images.githubusercontent.com/45676811/86065678-9fd16a00-ba46-11ea-8f58-ffd83a1c1c39.png)

**Comment by tkirda** [comment]
This looks right. Maybe try using **beforeSend** option.

**Comment by agostinhodev** [comment]
**SOLVED**

I was using a depreciated version of this lib: **1.2.7**

But now I did a `git clone` and changed to version [ **1.4.11**](https://github.com/devbridge/jQuery-Autocomplete/blob/master/dist/jquery.autocomplete.min.js)

All work fine now
