### ISSUE TITLE
formatResult: styling item Container?

### ISSUE THREAD

**Issue by fuxifex** [devbridge/jQuery-Autocomplete#822]
i read about formatResult - but how would i style the item's parent container (which would be div.autocomplete-suggestion)?
i want to colorize certain items .. thanks!

**Comment by tkirda** [comment]
In **formatResult** you can wrap your item with node with custom classes based on suggestion value/data:

```javascript
formatResult: function (suggestion) {
  // You can also reuse original formatResult
  return '<div class="my-class">' + this._formatResult(suggestion.value) + '</div>';
}
```

Currently, there is no option to style a container, but you can always use custom CSS to change styles.
