### ISSUE TITLE
Include images in suggestion

### ISSUE THREAD

**Issue by mhoganid8** [devbridge/jQuery-Autocomplete#824]
In a previous version, I was able to include images in the dropdown suggestion list by returning the following value string:

`<img src="/itemimages/50x50/Tz_1049_t12hossend.jpg" height="auto" width="50" alt="WW-1230-9" />&nbsp;&nbsp;WW-1230-9`

The current version displays the <img> tag as text instead. Is there a way to send the value in a way that will be interpreted as an image?

![image](https://user-images.githubusercontent.com/56976474/112654303-3fc4f400-8e1d-11eb-8871-082c5dba2f7c.png)

![image](https://user-images.githubusercontent.com/56976474/112654362-4fdcd380-8e1d-11eb-9f9a-8540288f073b.png)

**Comment by tkirda** [comment]
Provide `formatResult` function to format the result. See in the docs.
