### ISSUE TITLE
I want to remove Spaces at the beginning and end of the input values

### ISSUE THREAD

**Issue by YSZeng** [devbridge/jQuery-Autocomplete#833]
I want to remove Spaces at the beginning and end of the input values
For example, when typing ‘ Search Text  ’, you can decide whether to handle leading and trailing whitespace in a text box.
Sometimes you want to keep whitespace, but sometimes you want to delete whitespace.

**Comment by merabchik** [comment]
You can override style properties with CSS using class selector ".autocomplete-suggestions" by "!important" keyword in CSS

**Comment by tkirda** [comment]
You should be able to manipulate those values with JavaScript. Not sure what is the issue that you are describing here.
