### ISSUE TITLE
Searching in Cyrillic

### ISSUE THREAD

**Issue by Behruz17** [devbridge/jQuery-Autocomplete#839]
Hello, 

I am using this awesome plugin for autocomplete. But in doesn't work with Cyrillic.  Although I'm using UTF-8 encoding.
Can u help me with this?

Thanks in advance,
Behruz

**Comment by tkirda** [comment]
It does not have anything specific in terms of what encoding should be used. It should work with Cyrillic. Can you be more specific what is it that does not work?

**Comment by Behruz17** [comment]
It doesn't show any suggestions and hints when I type Cyrillic letters. 
![auto1](https://user-images.githubusercontent.com/71710568/181064252-a7323dab-b819-4787-a3f4-1a4bc7be445c.PNG)
![auto2](https://user-images.githubusercontent.com/71710568/181064356-7deb9ced-1436-4393-be17-dcf4cb4a810a.PNG)
![auto3](https://user-images.githubusercontent.com/71710568/181064383-5006d042-6253-4462-85c5-0b7ac356c90d.PNG)

**Comment by Behruz17** [comment]
@tkirda  Can u help me please? It doesn't show any suggestions and hints when I type Cyrillic letters. But when first letter is English and the rest id Cyrillic it works

**Comment by rivalhw** [comment]
try change the code demos.js  line 51 as following :
>return suggestion.value.toLowerCase().indexOf(queryLowerCase) === 0;

to as following:
>return suggestion.value.toLowerCase().indexOf(queryLowerCase) === 0;

now can support as Chinese、Cyrillic  etc.

**Comment by Behruz17** [comment]
@rivalhw  this function is in 18 line. But it doesn't work
![image](https://user-images.githubusercontent.com/71710568/181740472-057b410b-5515-4920-8566-4a47b13702c2.png)

**Comment by Behruz17** [comment]
@rivalhw  Can you please send me your version (file) ?
