### ISSUE TITLE
No item selected on ExactMatch

### ISSUE THREAD

**Issue by noskill24** [devbridge/jQuery-Autocomplete#841]
onSelect-event doesn't firing if array of suggestions contains similar values:

```
var countries = [
    "Andorra",
    "Andorra 1",
    "Andorra 12",
    "Andorra 123",
[;
```

If I type **"Andorra 123"** (using keyboard, not select) - onSelect event will fire because there is ONE exact match!
If I type for example **"Andorra"** - onSelect event will not fire because there are FOUR matches! 

But there is STILL ONE exact match - **"Andorra"** from four total matches (three other are not exact)!

This bug happens because **isExactMatch**-function checks exact match when one and only one match is found.

      isExactMatch: function (query) {
        var suggestions = this.suggestions;
        return (suggestions.length === 1 && suggestions[0].value.toLowerCase() === query.toLowerCase());
      },

**Comment by svennd** [comment]
> If user just types"Andorra", why it is not equal to **select** "Andora"? I think it is poor design. User selected this value by typing. Ok, how can I detect **Exact Match** in this case?

I think you should be able to figure out why ...

The user can just press enter to select it.

**Comment by tkirda** [comment]
That is by design.
