### ISSUE TITLE
cache previous request

### ISSUE THREAD

**Issue by flash1nho** [devbridge/jQuery-Autocomplete#847]
how about `.trim()` function for `q` param value ?

I think spaces without words can not be passed and we will not execute an extra request
add after https://github.com/devbridge/jQuery-Autocomplete/blob/master/dist/jquery.autocomplete.js#L545 `q = q.trim(),`

request example without fix:
```
Parameters: {"query"=>"test "}
```

but request does not executing after fix

**Comment by tkirda** [comment]
This is only an assumption that it is useful for everyone. You may easy trim server side or provide `onSearchStart` where you can trim the query.
