### ISSUE TITLE
modify query before performing ajax lookup

### ISSUE THREAD

**Issue by kvonspiczak** [devbridge/jQuery-Autocomplete#849]
i'm trying to modify the submitted query **before** showing the suggestions. so in my specific case: if someone enters a query and it ends with a `-`, I want the autocomplete to treat the query as if it was without the `-` at the end.
any tips, how to accomplish that?

**Comment by gongph** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by tkirda** [comment]
You can manipulate query by updating it using onSearchStart (this is for Ajax lookup):

```js
onSearchStart: (params) => {
  params.query = _.trimEnd(params.query, '-');
}
```
